### ISSUE TITLE
UI onHover event

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#100]
Many UI designs could greatly benefit from responding to when the cursor passes over them, to for example hint that something is clickable, or to display tooltips.

Today, UI elements only have an onClick property. It would be great to also add an optional onHover property.

Like the in-world on-hover component, this should have two lambdas: one for when the cursor enters and one for when it leaves

```ts

clickableImage.onHover = new OnHover(() => {
  // DO SOMETHING WHEN HOVER ENTERS
},
{
  // DO SOMETHING WHEN HOVER LEAVES
}
)
```

**Comment by menduz** [comment]
Handled in SDK7 PointerEvents
