### ISSUE TITLE
Tweens and Trigger areas don't work together

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1001]
If I use a Tween and a Trigger Area form the utils library on a same entity, I can't get the trigger area to work, it doesn't detect that the player stands inside it.

Probably it's something to do with how the trigger area works and how it calculates the current position of the entity.

**Comment by pravusjif** [comment]
tackled at https://github.com/decentraland/unity-renderer/pull/6037, will reach production with next explorer's release and subsequent SDK release

**Comment by pravusjif** [comment]
Fix released with [@dcl/sdk@7.3.36](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.3.36)
