### ISSUE TITLE
UI elements support pointerUp events

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#101]
Support on UI elements for Pointer UP events

This is especially useful for drag-and-drop mechanics

We could add a property similar to OnClick on the UI elements, that responds when the mouse button is released while on that element

```ts
clickableImage.onPointerUp = new OnPointerUp(() => {
  // DO SOMETHING WHEN POINTER GOES UP
}
)
```

**Comment by menduz** [comment]
Handled in SDK7 PointerEvents
