### ISSUE TITLE
Cyclic dependencies in `decentraland-ecs` -> `@dcl/kernel` -> `decentraland-ecs`

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#102]
To remove cyclic dependencies, remove common parts into a new package, and make `decentraland-ecs` consume that package. Those reusable parts may also be used for the next gen ECSv7

Things to move outside `decentraland-ecs`:
- Math libraries
- Event library
- Observables
- Common types (scout usage in dcl/kernel)

`decentraland-ecs` is bundled using rollup, therefore, this new libs should be a devDependency because those will be bundled inside the final .js

**Comment by menduz** [comment]
@gonpombo8 I think we can close this right?

**Comment by gonpombo8** [comment]
almost. We are still using decentraland-ecs but for the test scenes. Need to remove them or update those ones to the legacy-ecs package.
