### ISSUE TITLE
Multiline text in UI

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1040]
Currently it's not possible to make a text adjust its number of lines to the size of its parents. You have to explicitly add line breaks with \n 

The whole point of using flexbox was to have the UI adjust dynamically to different screens and contents. Without this feature, any text with more than 6 words is a pain to handle.
It also makes it more complicated to do libraries that handle any prompt or NPC text.

In SDK6 this was not something creators needed to think about, the text just adapted to the size of the container.

**Comment by AlejandroAlvarezMelucciDCL** [comment]
@nearnshaw I can't remember if I worked on this or not, do you know if this is done and we can close this issue?

**Comment by nearnshaw** [comment]
Yes, this is already fixed :)
closing it
