### ISSUE TITLE
In VSCode can't upload models by dragging

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1041]
When using the Inspector inside the VS Code extension, if I click to add new models to the scene I see this message:

![Image](https://github.com/decentraland/sdk/assets/3507907/937f5d53-cad2-493b-a3c5-78d46c15ebe5)

It tells me I can upload a model by just dragging it there. However, if I do that, I don't upload the model. Instead I open a new window to see this model in 3D.

I can still upload the model if I click the icon with the plus arrow and select it from the explorer.

If there's any limitation in VS Studio that doesn't allow us to just drag the file into the screen, then we should at least change the text, to not mislead users.

**Comment by cazala** [comment]
Yes, that does work on the Web Editor, but in VSCode it gets overriden by the default behavior of VSCode which is opening the file in a new tab. We should try to identify when running within VSCode, or passing a parameter from outside to tell the inspector to change the copy in that part.

**Comment by nearnshaw** [comment]
only on VS extension, won't fix
