### ISSUE TITLE
[BUG] movePlayer renders teleport screen and gets stuck

### ISSUE THREAD

**Issue by cazala** [decentraland/sdk#1043]
### **Issue Description:**

When using the `movePlayer` function, the client renders the 'teleporting' screen and it gets stuck there. This happens when using this feature in a world.

Here's an example scene: [link](https://play.decentraland.zone/?realm=builder-api.decentraland.zone%2Fv1%2Fprojects%2F0c8b9ce2-a4e3-4cfc-845f-c3be683f6be1&NETWORK=sepolia&DEBUG_SCENE_LOG=&position=0%2C0) 

In that scene there's a button that when clicked, it calls the `movePlayer` function with the options `{ newRelativePosition: { x: 8, y: 1, z: 8 }}`. 

This throws no errors but the client gets stuck in a loading screen.

### **SDK:**

- [ ] SDK6
- [x] SDK7

### **Steps to reproduce:**

1. Deploy a wolrd that makes use of `movePlayer`

### **Expected behaviour:**

It moves the player to the target position

### **Current behaviour:**

It shows the 'teleport' loading screen and gets stuck there

**Comment by gonpombo8** [comment]
Closed via https://github.com/decentraland/builder-server/pull/729

**Comment by gonpombo8** [comment]
https://github.com/decentraland/builder-server/pull/729
