### ISSUE TITLE
[BUG] Imported assets cannot be deleted in the Web Editor

### ISSUE THREAD

**Issue by meyaradcl** [decentraland/sdk#1057]
### **Issue Description:**

Imported assets cannot be deleted in the Web Editor.

### **SDK:**
- [ ] SDK6
- [X] SDK7

### **Tool:**
- [X] Editor
- [ ] CLI

### **Steps to reproduce:**
1. Import an asset
2. Try to delete the asset (it doesn't work)

This is particularly critical when it comes to deployment, as unused assets occupy space and could lead to a blockage due to size limit issues.

### **Expected behaviour:**

When accessing Local Assets, I should be able to delete the items I wish, and after being deleted these should not occupy space in the scene project.

### **Current behaviour:**

The menu for deleting items appear, but it seems to do nothing.

### **Reproduction rate:**

Always

### **Platforms:**
- [ ] Windows
- [ ] Mac
- [X] Not platform specific

### **Browser:**
- [ ] Google Chrome
- [ ] Microsoft Edge
- [ ] Firefox
- [ ] Desktop
- [ ] Brave
- [ ] Safari
- [X] Not Browser Specific

### **Environment:**
- [] production - web client
- [ ] production - desktop client
- [ ] local preview
- [X] web editor
- [ ] desktop editor

### **Evidence:**

![builder-delete-error](https://github.com/decentraland/sdk/assets/126520407/2229b922-a92f-4726-8b16-87a10eb19e4d)

### **Additional Notes:**

This issue has been reported a while ago for a user, but we couldn't tackle yet. Since this could block deployments, this should be fix ASAP.

**Comment by cazala** [comment]
Fixed on version `v7.3.35` of `@dcl/sdk`.
Released on Editor v1.37.0 and Builder v6.69.0 today.
Marking this issue as resolved.
