### ISSUE TITLE
Tween rotation weirdness

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1063]
In this simple scene, a cube is meant to do the following each time it's clicked:

- Pick a new random position
- Rotate with a tween to that position
- Wait
- Move to that new position

Instead, it does some weird things, teleporting back and forth between previous positions.

https://github.com/decentraland/sdk/assets/3507907/5a2fc650-46ad-4063-a243-cfe491fcb322

If I remove the lines that do the rotation tween, it works well. It never rotates, but it always moves from one point to another smoothly, never defying the laws of physics.

This also happens using explorer-branch=dev, which includes the latest fixes to tween movement.  Movement works great with that, but rotation seems to still mess things up

If I make a scale tween instead of a rotation tween before the movement, I have the same problems. So scale is being affected the same as rotation. (There are some lines in the file you can comment out to try this)

https://github.com/decentraland/sdk/assets/3507907/bf33a578-2176-46c6-b55e-bb25af5dedb8

This is the scene:

[tween-rotations 2.zip](https://github.com/decentraland/sdk/files/13845467/tween-rotations.2.zip)

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-renderer/pull/6057

**Comment by pravusjif** [comment]
Should reach production with next explorer release and subsequent sdk release (most likely 7.3.37).
