### ISSUE TITLE
Search Bar and Enhancements in the Assets Pack Catalog

### ISSUE THREAD

**Issue by cyaiox** [decentraland/sdk#1070]
1. Redistribute the Asset Pack cards so the layout is more balanced.
- 6 per row.
- When scaling down, the cards should have a min-width of 180 and then start stacking.
- The content should have a max-width of 1440px to avoid extending too much the width of the cards in ultra wide resolutions. 

![Image](https://github.com/decentraland/sdk/assets/126520407/b602ad88-2f4b-491c-b203-1d6415163cc5)

- Font sizes and style are updated. 
- If possible, we are adding the count of items inside each pack.

2. Add a search bar at the top right of this section.
![Image](https://github.com/decentraland/sdk/assets/126520407/0b1d300e-3ab7-4213-aace-6084b3753292)

- This search bar searches across all asset packs. 
- There are 2 cases: Results and No Results.

![Image](https://github.com/decentraland/sdk/assets/126520407/1f226570-fc5b-4565-9ded-cda331762b23)

![Image](https://github.com/decentraland/sdk/assets/126520407/e280e61f-8382-4b71-adce-d0a6c7be5204)

3. When inside a category, the title and the back button are located at the top left. 
![Image](https://github.com/decentraland/sdk/assets/126520407/f4244cd4-09bb-4917-b5c3-34cd24d2ba1b)

4. The search bar inside a category only searches inside the given category.
- There are also 2 cases: Results and No Results (they are very similar to the general search but the copy and links change)

![Image](https://github.com/decentraland/sdk/assets/126520407/3427587c-e28d-4e0a-bae9-209697a50f59)

![Image](https://github.com/decentraland/sdk/assets/126520407/18435ad9-8c9d-45e6-a65d-beacd7c1ab1f)

5. Items should show a tooltip with the name of the item.
- There is no delay between the hovering and showing the tooltip. It should be displayed automatically. 
- Only Smart items will have a description. 

![Image](https://github.com/decentraland/sdk/assets/126520407/6aef2959-f260-46fb-9427-8a7158fd3580)

Link to Figma: https://www.figma.com/file/1pTu82yhmYGAKa3h7eaPoz/%F0%9F%A7%B0-Decentraland-Web-Editor-%7C-Builder-%7C-04%2F23?type=design&node-id=1991%3A98135&mode=design&t=AFDtXAUN1TdGkTqM-1

**Comment by nearnshaw** [comment]
Grammar OCD comment:
In the no results message

"Try using another words ..." > "Try using another word ..."

Or I think better:
"Try different words ..."
