### ISSUE TITLE
[BUG] Error in transport locks up entire scene

### ISSUE THREAD

**Issue by wacaine** [decentraland/sdk#1083]
### **Issue Description:**

I have a bug that may or may not be related to my code BUT feels like in part could be improved on the client side.  I cannot consistently reproduce it but once it happens the entire scene stops processing.  I can walk around but cannot interact with anything.  Point downs system, triggers etc. nothing that was working before continues to work.

I understand if my code does something to throw an error, but how is it is stopping processing of the scene as a whole.  I think a try/catch is missing somewhere in the client to allow it to recover.     I have yet been able to isolate it.  It maybe a race condition but when this error does appear,  nothing in my scene works again until I reload it.

"Error: Uncaught Error: [create] Component core::Transform for 131086 already exists
    at Worker.<anonymous> (https://cdn.decentraland.org/@dcl/explorer/1.0.160612-20240226145831.commit-52cf906/index.js:63296:123523)
    at Worker.gr (https://cdn.decentraland.org/@dcl/explorer-website/2.1.1/assets/index-lLmTeOCG.js:225:1961)

### **SDK:**

- [ ] SDK6
- [x ] SDK7

### **Tool:**

- [ ] Editor
- [ ] CLI

CLI Version:  
Node Version:

### **Steps to reproduce:**

I have yet to isolate a cause.

### **Expected behaviour:**

Scene not to become unresponsive.

### **Current behaviour:**

 I can walk around but cannot interact with anything.  Point downs system, triggers etc. nothing that was working before continues to work.

### **Reproduction rate:**

Intermittent.

### **Code Snippets:**

I have checked my code for poor usage of Transfom.create.  I have not spotted one.  Maybe its still there but my point is the entire scene should not become unusable due to this.

### **Platforms:**

- [ ] Windows
- [ ] Mac
- [x ] Not platform specific

### **Browser:**

- [x ] Google Chrome
- [ ] Microsoft Edge
- [ ] Firefox
- [ ] Desktop
- [ ] Brave
- [ ] Safari
- [ ] Not Browser Specific

### **Environment:**

- [x ] production - web client
- [ ] production - desktop client
- [ ] local preview - Have not been able to reproduce here
- [ ] web editor
- [ ] desktop editor

### **Evidence:**

![Screen Shot 2024-03-01 at 10 55 12 AM](https://github.com/decentraland/sdk/assets/2999141/14e58c1d-59df-442d-b616-b6624064833f)

### **Additional Notes:**

Can be reproduced here https://decentraland.org/play/?position=148%2C60&DEBUG_SCENE_LOG=&realm=main&island=default5k at random.   Not sure exact steps.  Related to clicking relogin, collecting coins etc.

**Comment by gonpombo8** [comment]
I solved this on the latest release. Can you try using @dcl/sdk@latest and see if still happens ?
@wacaine

**Comment by wacaine** [comment]
@gonpombo8 I have been unable to recreate it locally and I thought that anything deployed automatically inherits latest SDK?  is that not true?  Or am I confusing that with the engine

**Comment by nearnshaw** [comment]
@wacaine  everything deployed inherits the latest version of the engine, but not of the SDK
The change we're discussing here is very much on the side of the SDK, so in order to fix this in production, it would require updating the SDK version to the latest and redeploying.
I'm quite confident that the changes that Gonzalo recently introduced (last week I believe) should prevent this kind of thing from happening. 
The scene likely is making some mistake (like attempting to fetch a component that doesn't yet exist, or re-adding a component that is already there), but that shouldn't have so dire consequences as completely crashing the entire scene.

**Comment by wacaine** [comment]
@nearnshaw  @gonpombo8  we deployed our scene maybe 24 hours ago (https://peer.decentraland.org/content/entities/scenes?pointer=145,60) 
with this in our package-lock file

```
 "@dcl/js-runtime": "7.4.7",
    "@dcl/sdk": "^7.4.7".
```

Which version is it fixed on? II just got the error again today.  Th whole scene becomes unresponsive when this happens.  I see this error message mentioned Component core 2.2.0 vs last screen shot of 2.1.1.    Is the issue in this referenced component core file or somewhere else?  

<img width="1078" alt="Screen Shot 2024-03-05 at 5 20 04 PM" src="https://github.com/decentraland/sdk/assets/2999141/9afc3d12-4849-4c20-8dbb-531b603d27d7">

We are using some libraries.   Do all libraries have to be patched with latest SDK too or can the library still be susceptible to the bug?  sdk7-utils for example?

I have audited all usages of Transform.create within the scene.  Only time we use create is during when the entity is created.  All follow up use is Transorm.createOrReplace.   For good measure I could mass find/replace createOrReplace EVERYWHERE.   That would rule out it being any kind of problem related to our immediate code.  At that point libraries are to blame possible?

**Comment by wacaine** [comment]
Issue is no longer a problem.  I can't recall the SDK version but at some point you fixed this error from crashing the entire scene.   So at this point I dont know if its still an error in the underpinnings or not and cannot tell.  This is because of the fix to not let the SDK crash the scene on the error, it wont crash the scene anymore :) works for me :)
