### ISSUE TITLE
Z order for UI elements

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#111]
When UI elements overlap, there aren't clear ways to define which one displays on top of the other 

You can parent one UI element to another, so that the child is always on top, but that type of hierarchies aren't always enough.  We should have a `z` property, to define which element should be displayed over which.

UI elements of the explorer should always appear on top of those of a scene, we shouldn't expose any way for devs to cover the global UI with their own.

**Comment by menduz** [comment]
Won't fix, SDK7 solves the issue
