### ISSUE TITLE
Remove UI element from engine

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#112]
There currently is no function or way to remove a UI element from the engine.

UI elements are components that don't belong to any entity. Unlike entities that need to be added to the engine to start being rendered, UI elements are added to the engine as soon as they're created. But there is no way to remove them from the engine. One can only make them invisible, but they remain in memory.

This poses a problem in scenes with dynamic UIs, for example if they must load thumbnails from an API to scroll through menus, or show the thumbnail of every other player that jumps into the scene. Eventually, this becomes a memory leak in the scene, as more images are loaded.

There should be a way to remove UI elements

Maybe something like this?

`engine.removeUIComponent(<component>)`

**Comment by menduz** [comment]
Won't fix. SDK7 fixes the issue
