### ISSUE TITLE
Event when player enters/leaves scene

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#114]
Have an event triggered whenever the player enters or leaves the parcels that make up the scene

Something like this was already developed by Mateo, but it was never released as it only worked in production, not in preview. It can nevertheless be a good starting point

This can be used, for example, to pause the action in a scene, to connect a player to a websockets server for the scene only when on the scene, to start a video stream only when the player is on the scene, etc.

Currently it's possible to use a TriggerArea from the utils library for the same purposes. Doing that involves several more steps, and can get tricky for non-square scenes.

Important consideration: this should be able to contemplate cases where the scene is not necessarily square shaped.

**Comment by pbosio** [comment]
moving this back to the "to do" column.
me should need a message from the renderer when avatar enter o leave scene to make sure the event match with what user is seeing.
we can't use kernel events cause renderer is interpolating avatars' position

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1586
kernel: https://github.com/decentraland/kernel/pull/117
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/53
