### ISSUE TITLE
Broken images in Creator Hub screens

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#1158]
Some images in the UI layouts aren't loading

![Image](https://github.com/user-attachments/assets/eea1a2fa-4ca0-4968-a6f1-20c366bdde1b)
![Image](https://github.com/user-attachments/assets/aee1e820-db95-4cbb-8afc-ca0c6f5a8bb6)

**Comment by nicoecheza** [comment]
fixed in https://github.com/decentraland/creator-hub/pull/97
