### ISSUE TITLE
Log my position

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#116]
I very often find myself copying this same chunk of code to my scenes, pretty much to all of them, to log the player postion when I press E.

```ts
Input.instance.subscribe('BUTTON_DOWN', ActionButton.PRIMARY, false, (e) => {
  log('POS: ', Camera.instance.feetPosition)
  log('ROT: ', Camera.instance.rotation)
})
```

Newbies that don't know this trick may find it really hard to position items in the scene, and the chunk of code itself doesn't look all that friendly either.

I propose adding another option to the preview-UI menu for "log my position" that prints the current player position to the log, without needing to go through the steps of adding this bit of code.

---

Option 2: Print position in label in debug UI

**Comment by leanmendoza** [comment]
Is Option2 considered the final?

**Comment by menduz** [comment]
How was this resolved? It is marked as done in the board
