### ISSUE TITLE
BOUNCER CODE NO LONGER WORKS

### ISSUE THREAD

**Issue by ProteanCoding** [decentraland/sdk#1173]
C.f. https://github.com/decentraland/protocol/blob/main/proto/decentraland/kernel/apis/communications_controller.proto#L19.

There is no indication whatsoever as to how the binary stream is supposed to be used in the stead of the former text stream.
Now that the deprecated functionality is actually no longer working, some very critical scene tools are unavailable.
Notably the possibility of kicking disruptive users from a scene.

_Originally posted by @ProteanCoding in https://github.com/decentraland/sdk/issues/582#issuecomment-2540309523_

**Comment by gonpombo8** [comment]
Bouncer UI is working for both client & web versions for me. Can you explain a bit more what the `no longer works` means ?
Also the code line that you are pointing is not valid, its deprecated but still working.

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/c7bd2ea1-1073-4b1e-8162-b737bcc5a5b5" />

**Comment by gonpombo8** [comment]
Closing the issue for now.
Feel free to open it again with some repro steps. That code is wokring as expected, and the communications_controller that we use for the messageBus too.
