### ISSUE TITLE
Attach entity to other players

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#118]
Names may vary.

The objective is to create a way to attach things to other avatars.
- The design of the feature must take into account both avatars created by the AvatarSystem (`dcl-gs-avatar` scene) and avatars created by scenes using AvatarShape.
- The feature must also offer the possibility to attach the entity to an end of a bone to enable use cases like holding a sword in the hands of the avatar. Or attaching rollers to the feet.

The suggested approach requires two components. 
1) `AvatarShape` would need a field named `id` to identify the avatars cross-scenes
2) A component `AttachToAvatar` to attach the holding entity to the identified avatar:
```ts
/**
 * AttachToAvatar is a component that allows any entity to be attached to an Avatar 
 * in the Renderer. It works for any AvatarShape in any scene.
 * 
 * The renderer ignores the Transform component in entities with AttachToAvatar. 
 * Similar to the BillboardComponent, the renderer changes the transformation of
 * the entity to copy the global position and rotation of the attaching point.
 * 
 */
@Component
class AttachToAvatar {
  // scene in which we will look for the avatar. to enable synthetic avatars created
  // by any scene
  parentSceneId?: string = 'dcl-gs-avatars'
  // avatarId to map against a scene[parentSceneId].avatars.get(avatarId)
  avatarId: string
  // attachingPoint is used to identify the bone, label, or other attaching points
  // attachingPoint also does not point to bones directly, instead an Enum is used to be extended with friendly names
  // and to prevent using strings which are heavier for the wire protocol
  attachingPoint?: AttachingPointsEnum
}

enum AttachingPointsEnum {
  FeetPosition = 0, // default
  // ... well-known bone attaching points,
  // other well-known attaching points
}
```

Developments from the renderer's end:

1. Create a component that is sent to the renderer `new AttachToAvatar(avatarId: string)`. 
    - When present, every time the Transform changes, the engine sets the parent to the `avatarId` entity of the AvatarScene (if exists).
    - If the `userAddress` entity doesn't exist, then the Transform follows its regular flow of parenting

---

Example of an Orb floating on top of the avatar with address `0xNico`:
```typescript

const avatarContainer = new Entity()
avatarContainer.setComponent(new AttachToAvatar('0xNico'))
//                           ^^^^^^^^^^^^^^^^^^ invalidates the transform

// this way you change the relative position of an entity attached to an avatar
const orb = new Entity()
orb.addComponent(Transform).position.y = 1
orb.setParent(avatarContainer)
```

**Comment by EibrielInv** [comment]
I think the idea is great, it would be super useful for games to show "Badges", equipped items, or dialogue of their players.

As for the technical side, is there a bone that is "main"? that is to say that is at ground level and that only rotates on the Y axis (height, direction of gaze)?
To be able to join things that don't "dance" with the movement of the bone.

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1638
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/59
posix: https://github.com/decentraland/posix/pull/8

**Comment by nearnshaw** [comment]
TODO: Hide the anchor points for hands

@pbosio

**Comment by pbosio** [comment]
hide anchor points for hands PR: https://github.com/decentraland/js-sdk-toolchain/pull/84
