### ISSUE TITLE
Force camera mode

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#123]
Force 1st person or 3rd person view in a particular region of a scene

This could be achieved by defining a new type of Avatar Modifier area
https://docs.decentraland.org/development-guide/avatar-modifiers/

The player's prior camera mode should be remembered, so as to revert back when the player leaves the area. This should also be the case if the player teleports away from the area, instead of stepping out of the area.

**Comment by pbosio** [comment]
should this area disable the input for the player to freely change the camera mode?
if that so, should we add a new scene permission for this?

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1725
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/75
