### ISSUE TITLE
Hide avatars selectively

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#124]
The existing avatar modifier area hides all avatars, including the player's own.
https://docs.decentraland.org/development-guide/avatar-modifiers/#hide-avatars

It would be great to have another type of avatar modifier area that allows to selectively only show certain other avatars.

For example: 
- see your own avatar but nobody else
- see only the players who are currently playing a multiplayer game with you
- A few scenes fake being larger than they are by teleporting and refurnishing the same rooms. In this case see only players that are in the same fake room as you, and hide players that are walking in a different imaginary space.

**Comment by menduz** [comment]
Consider allow list approach

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1853
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/101
