### ISSUE TITLE
Enable paste into UIInputBox

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#127]
The UI element UIInputBox doesn't let you paste text into it

There are use cases where this would be really useful, like pasting an address, or a code

**Comment by pbosio** [comment]
this is already possible, problem is that unity is using CTRL+V for paste shortcut instead of CMD+V for OSX

**Comment by nearnshaw** [comment]
This issue is invalid, as pasting does work currently. What's tricky is that pasting works in mac with Control + V instead of Command + V as it usually does everywhere else.

If this behavior must be changed, it should be done in Unity, not at the SDK level.
