### ISSUE TITLE
Know if player is using desktop/vr/etc

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#128]
Scenes could have a way to know if the player is running the scene from the browser, the desktop client, or eventually VR or mobile.

Scenes could run more expensive functionality or show heavier models, etc depending on what the player is using. Also when we have VR the usability would change a lot, and scenes could also react to that.

This could be implemented in an enum in the Kernel, via the EnvironmentAPI

**Comment by menduz** [comment]
Duplicated
