### ISSUE TITLE
Rename new action buttons

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#129]
Based on discussions with other teams, we decided to rename the new buttons we recently added
There was too much potential for confusion between Primary vs Action_1  & Secondary vs Action_2

So we would rename the following button events:

Action_1 > Action_3
Action_2 > Action_4
Action_3 > Action_5
Action_4 > Action_6

**Comment by pbosio** [comment]
PR renderer: https://github.com/decentraland/unity-renderer/pull/1515
PR sdk: https://github.com/decentraland/js-sdk-toolchain/pull/45
