### ISSUE TITLE
camera.CameraMode is incorrect on first start

### ISSUE THREAD

**Issue by dzsunyec** [decentraland/sdk#136]
Camera.instance.cameraMode seems to be always initializing with CameraMode.FirstPerson. 
When you run the attached game.ts you will see that the scene runs the "first person" branch when clicking, even though the player loads into third preson view by default.

Then after pressing 'V' twice the cameraMode is returned correctly. (see floating textShapes)

[https://app.zenhub.com/files/389651442/93218fb7-fd32-44bb-9c58-fb3b6971db7b/download](https://app.zenhub.com/files/389651442/93218fb7-fd32-44bb-9c58-fb3b6971db7b/download)

**Comment by nearnshaw** [comment]
Duplicate with #143
