### ISSUE TITLE
animation.play(false) resets from start

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#142]
Animations are supposed to be pausable and then playable from where they were left off

The .play() function includes an optional parameter (false by default) that if true plays the animation always from the start, if false plays the animation from where it was last paused.

https://docs.decentraland.org/development-guide/3d-model-animations/#play-an-animation

This doesn't seem to be the case. Here's an example reported by someone in the community where the animation always resets to the start, even when the parameter in play() is false. See the attached example.

[Example.zip](https://github.com/decentraland/sdk/files/7627946/Example.zip)

In the example the cube animates when you walk near it, and pauses when you walk away. But when you walk back close to it, it's supposed to keep from where it left off, but instead it jumps to the start of the animation again.

I was able to reproduce the issue on my machine, both with @latest and @next.

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1667
