### ISSUE TITLE
AttachToAvatar doesn't get replaced by Transform

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#159]
In theory, an entity can only have a AttachToAvatar component or a Transform component
but in practice, it is possible to have both, and it has unexpected results

See this example scene:
https://github.com/decentraland-scenes/beer-dispenser/tree/attach-to-player

in beerGlass.ts, when putting down a glass (line 177), I should in theory just need to do this, and that should replace the AttachToAvatar too

```ts
 this.addComponentOrReplace(
      new Transform({
        position: placePosition,
        rotation: Quaternion.Zero(),
      })
    )
```

But if I just do that, the entity remains attached to the other player, just shifted to the transform position

I need to also do
```ts
  if (this.hasComponent(AttachToAvatar)) {
      this.removeComponent(AttachToAvatar)
    }
```

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1730
