### ISSUE TITLE
movePlayerTo issue (relative/absolute position)

### ISSUE THREAD

**Issue by niakteemz** [decentraland/sdk#162]
I encounter issues with movePlayerTo() which sometimes seems to mix up player position (relative to scene/absolute to world).
Small example below to reproduce the issue

The scene is deployed in (10,20) : 
```
"scene": {
    "parcels": [
      "10,20"
    ],
    "base": "10,20"
  }
```

Code : 
```
import { movePlayerTo } from '@decentraland/RestrictedActions'
import * as utils from '@dcl/ecs-scene-utils'

// Move Player when "E" is pressed
const input = Input.instance
input.subscribe("BUTTON_DOWN", ActionButton.PRIMARY, false, (e) => {
  movePlayerTo(new Vector3(8, 8, 8))  
})

// check camera position every 10ms. Log when camera position is not anymore relative to the scene
const timerEntity = new Entity()
timerEntity.addComponent(
  new utils.Interval(10, () => {
    let posx = Camera.instance.position.x
    // >100 obviously not within the scene
    if (Math.abs(posx)>100) {
      log ("Weird Camera.instance.position.x : ",posx)
      log("   world position",Camera.instance.worldPosition.x)
    }   
  }) 
)
engine.addEntity(timerEntity)
```

- When pressing "E" the player is moved within scene (to 8,8,8)
- The browser URL appears to be modified : from http://127.0.0.1:8000/?SCENE_DEBUG_PANEL&position=**10%2C20**&realm=localhost-stub to http://127.0.0.1:8000/?SCENE_DEBUG_PANEL&position=**0%2C0**&realm=localhost-stub
- Pressing multiple times "E" sometimes invert Camera.instance.position and Camera.instance.worldPosition (see logs when it happens) :
```
10,20:  Weird Camera.instance.position.x :  -152
10,20:     world position 8
```

**Comment by menduz** [comment]
Thanks for reporting. Will look into it

**Comment by niakteemz** [comment]
Thanks @leanmendoza @menduz @gonpombo8 for your prompt reaction and fix 👍
