### ISSUE TITLE
Texture with unknown URLs

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#165]
While we are making an scene (the regular parcel scene or a portable experience) and we deploy it, the contents are fixed in its deployment. In the parcel scene case there is no curator to review it but when you get the scene you have a well-known list of files that you can predict are going to be used.

Also, it's possible use unknown urls and even outside from catalyst, for example: 
`http://random-domain.com/not-wished-texture.png`

The open question:
- Do we wish this behaviour or not?

Linked to https://github.com/decentraland/sdk/issues/64

**Comment by pbosio** [comment]
implemented here: https://github.com/decentraland/unity-renderer/pull/4401
