### ISSUE TITLE
Base wearables not being found

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#167]
When running preview, sometimes a few base wearables can't be loaded, and the player appears faceless

![image](https://user-images.githubusercontent.com/3507907/149816389-8e060240-9354-43ab-8e55-44dcdff6c273.png)

**Comment by menduz** [comment]
It may be related to the base-wearables that are downloaded during the compilation of kernel. Which is a small subset of all the base-wearables in this lines: https://github.com/decentraland/kernel/blob/main/static/default-profile/download_all.js#L29-L38

**Comment by leanmendoza** [comment]
It seems it has stopped to happen. I tried with @next version and many combinations of body shape and customization of avatar and every seems to work fine. Reopen the issue if you believe it's necessary.
