### ISSUE TITLE
BoxShape uvs affect all boxes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#168]
It seems that when changing uvs of a BoxShape, you're changing the uvs of all boxes in the scene, not just that specific box

Try this example with any texture (I'm using the scene-thumbnail.png image that comes by default in an empty project for simplicity)

Try commenting out the entity2, and see that the entity1 has the texture repeated a certain number of times. But bring back entity2 and you'll see that entity1 has changed too, and now has the texture repeated the same number of times as entity2.

Entity1 alone
<img width="778" alt="Screen Shot 2022-01-18 at 09 44 02" src="https://user-images.githubusercontent.com/3507907/149939666-18764ac2-86fe-4b4e-8d68-5115a2d22e07.png">

With entity2
<img width="832" alt="Screen Shot 2022-01-18 at 09 43 44" src="https://user-images.githubusercontent.com/3507907/149939705-4b14fbd3-6ec0-492a-a385-1a92d44ea6eb.png">

Here's a more complete example scene, where each time you click the entity, it spawns a new cube with a new random uv mapping, and changes all the other cubes

https://github.com/decentraland-scenes/testUVs

```ts
const paddedwallmaterial1 = new Material()
const entity1 = new Entity()

const box1 = new BoxShape()
box1.uvs = setUVs(new Vector3(100, 100, 40))

paddedwallmaterial1.roughness = 0.5
paddedwallmaterial1.albedoTexture = new Texture('images/scene-thumbnail.png', {
  wrap: 1,
})
entity1.addComponent(
  new Transform({
    position: new Vector3(14, 6, 2),
    scale: new Vector3(8, 4, 0.01 * 2),
  })
)
entity1.addComponentOrReplace(box1)
entity1.addComponentOrReplace(paddedwallmaterial1)

engine.addEntity(entity1)

// ################################################################################################

const entity2 = new Entity()
entity2.addComponent(
  new Transform({
    position: new Vector3(4, 1, 10),
    scale: new Vector3(1, 1, 1),
  })
)

const box2 = new BoxShape()
box2.uvs = setUVs(new Vector3(300, 300, 300))

const paddedwallmaterial2 = new Material()
paddedwallmaterial2.roughness = 0.5
paddedwallmaterial2.albedoTexture = new Texture('images/scene-thumbnail.png', {
  wrap: 1,
})

entity2.addComponentOrReplace(box2)
entity2.addComponentOrReplace(paddedwallmaterial2)
engine.addEntity(entity2)

// ################################################################################################

function setUVs(scale: Vector3) {
  const scalex = (1 / scale.x) * 100 * 2 * 4
  const scaley = (1 / scale.y) * 100 * 2 * 3
  return [
    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,

    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,

    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,

    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,

    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,

    0,
    0,
    0,
    1 * scaley,
    1 * scalex,
    1 * scaley,
    1 * scalex,
    0,
  ]
}
```

**Comment by Suduck** [comment]
Fixed with the new ECS7 box shape component. It was also happening to the plane shape
