### ISSUE TITLE
cli: create guidelines and linter for example scenes for CLI

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#176]
- Define and add github actions to ensure the project compiles
- Define and implement branching strategy to ensure examples always work based on Github Actions
- `.gitignore` to ignore `.js` files, `/bin` folder and `node_modules`

**Comment by nearnshaw** [comment]
@leanmendoza can we consider this one done? WDYT?

**Comment by leanmendoza** [comment]
Yep
