### ISSUE TITLE
`dcl export` not working. Find an alternative to vercel.

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#185]
`dcl export` not working at `decentraland@latest`.
Seems a problem with the renderer. If you use the query param renderer-branch=master works fine

We should document some viable alternative using docker and deploying elsewhere. There is one below in a comment.

**Comment by leanmendoza** [comment]
# Heroku Free Alternative
Heroku can be an alternative to run a preview mode, it only requires some steps and it wouldn't use the Dockerfile (there is also a docker alternative in heroku).


The steps are:
1. Of course, first you need to have a Heroku account
2. [Install Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli). An alternative that they don't recommend but I like is running `npm i -g heroku`. There is more robust way and for this one it's important to use the LTS node.
3. In the scene folder, start a git repository with `git init`, you'll need a `.gitignore` file, then commit your files with `git add . && git commit -m 'initial commit'`. Then set your current branch `main` with `git branch -m master main`
4. Log in your Heroku CLI with `heroku login`
5. Run `heroku git:remote -a example-dcl-init` to link your local git repositoy
6. Create your app from command line `heroku create -a example-dcl-init`
7. Change your `start` script from `package.json` to `npm i -g decentraland@latest && CI=true dcl start -p ${PORT:=8000}` and 
8. Finally deploy your preview server with `git push heroku main`

Then for each deploy you have to:
1. Commit your changes with `git commit -am 'your changes'`
2. Run `git push heroku main`

Recommended `.gitignore`
```
/node_modules
npm-debug.log
.DS_Store
/*.env
bin
```

With the push, you'll receive logs in your console with the deploy status and preview URL.
You can read the console logs of the preview server with `heroku logs --tail`

For any alternative it's important to not exceed free tier limits (and worsen dev experience):
1. Offer a mechanism to serve cached renderer and js big size files 
2. Offer a mechanism to serve renderer and js big size files from decentraland cdn or npm
