### ISSUE TITLE
OnClick on UI should not be deprecated

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#189]
![image](https://user-images.githubusercontent.com/3507907/152643078-43081a79-d2af-48c6-9ebc-e09fdd6c17f3.png)

The OnClick component that can be added to entities is deprecated, because we have OnPointerDown instead

However, UI elements also have an OnClick property that should not be deprecated. There is no OnPointerDown for UI elements
Probably this was done by accident when also deprecating the OnClick component

**Comment by menduz** [comment]
Did you consider instead "Enable OnPointerDown on UI elements"?
