### ISSUE TITLE
Create adaptation layer for ECS6

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#209]
- [ ] Ensure all funcions used by the ECS6 exist in ECS7
- [ ] With feature flag, enable runtime adaptation layer to convert old messages into new messages

**Comment by leanmendoza** [comment]
I think this issue is aligned with the following tasks:
- [ ] 1) Prepare the ground for the `scene-system` in the kernel repository to expose outside the `posix interface` a method that is a direct cable to renderer e.g.
```
const componentOperation = new PB_ComponentOperation()
componentOperation.setType(PUT_COMPONENT)
componentOperation.setTimestamp(t)
componentOperation.setEntityId(t)
componentOperation.setClassId(t)
componentOperation.setData(component.toBinary())
dcl.sendDirectToRenderer(componentOperation.toBinary())
```
- [ ] 2) Receive messages in `unity-renderer` with the Component-Operation protocol described in https://diagrams.menduz.com/#/notebook/2l3t8FEx6Yc4GyDvkdDe4EQKf2L2/-MiSDLMvharXiZu6Vfjl potentially using protobuf (like the code described above)
- [ ] 3) Write a test scene in preview mode, use the unity-renderer branch and kernel worked on 1) and 2) embedding the new ECS and CRDT code.
- [ ] 4) Make different scenes that use the code from 3) to measure performance


The goal of 1) is to build an approach (and not a final implementation) to be able to connect with 2). This would allow to interact with basic components and compare both ECS with respect to performance time (benchmarks).

**Comment by leanmendoza** [comment]
# Goal
Short description: one scene running with original implementation of the DecentralandInterface has to be the same behaviour and to show the the same rendering as the adapted.

# ECS6 and ECS7
It's probably that as the ecs7 turns bigger and more complete, there will be less compatibility of features, or more distance between their similarities.

With this in mind, I want to introduce the functions that we can hook into the old scenes:
```
function attachEntityComponent(entityId: string, componentName: string, id: string): void
function removeEntityComponent(entityId: string, componentName: string): void
function addEntity(entityId: EntityID): void
function setParent(entityId: string, parentId: string): void
function removeEntity(entityId: EntityID): void
function componentCreated(id: string, componentName: string, classId: number)
function componentDisposed(id: string)
function componentUpdated(id: string, json: string)
function updateEntityComponent(entityId: string, componentName: string, classId: number, json: string): void
```

Except the ones that start with `component`, the rest of them need the `entityId` parameter.

For example, for cube creation as the cube example scene, the message flow is:
```
componentCreated(id: 'Ce', componentName: 'engine.shape', classId: 16)
componentUpdated(id: 'Ce', json: '{"withCollisions": true, ....}')
addEntity(entityId: 'Ed')
updateEntityComponent(entityId: 'Ed', componentName: 'engine.transform', classId: 1, json:'{"position": {"x":1 , ....')
attachEntityComponent(entityId: 'Ed', componentName: 'engine.shape', id: 'Ce')
``` 
This code ilustrates how the creation component messages happen before the entity creation. And in the entity creation, we don't have information about its componet link until the last line.
In the ECS7, the entities are created with `entity.addEntity()` and its state begins to be defined with the component creation. That is the entity is just a number which identifies a set of components.

# Adaptation-layer
The idea of the adaptation-layer is to take the message sent to the `DecentralandInterface` and with them, to make an ECS7 scene that gets the goal at the top of this post. This adaptation-layer can be complete, semi-complete or hybrid as I define here:
- Complete adaptation: absolutely all the messages are processed to form a identical scene with the ECS7
- Hybrid adaptation: the identical scene is formed with some ECS7 messages and with some ECS6 message following the original and old path.
- Semi-complete adaptation: all the message are ECS7 messages, but the renderer-side implements this ecs7 as wrapper of the ecs6. For example, creating a OLDECS_UI_TEXT_SAPE component, no exposed to creators, only an internal component.

The ideal approach is the complete one, next the semi-complete and the hybrid one would be a temporal solution.

## Hybrid adaptation
This approach is being tested here: : https://github.com/decentraland-scenes/first-ecs7-scene/pull/1
Now, its functionality is: each update cycle, to collect the information that later will be processed. At the end of the cycle, the messages of the ECS6 are processed again, but now with the information to decide if the message continue with the old-ecs path or to be used to generate a ECS7 message.

**Comment by nearnshaw** [comment]
@gonpombo8   I think this can already be closed, right?
