### ISSUE TITLE
[Preview Mode] Feature Flags system is not working on Preview Mode

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/sdk#212]
Currently, if we have a feature running under a Feature Flag configuration, it will not appear in Preview Mode... although the flag is ON, the feature will never be activated there. The only way for the feature to be activated in Preview Mode is to register the feature without flag in our `PluginSystemFactory` (`Register` instead of `RegisterWithFlag`).

We have to think about how we want to manage the Feature Flags in the Preview Mode.

**Comment by menduz** [comment]
This is actually not an issue, it is by design. Feature flags only work on deployed environments, the preview uses the default values, always.

**Comment by menduz** [comment]
It works now, depending on the hostname
