### ISSUE TITLE
Remove Now script

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#217]
In package.json we still have a deprecated script to deploy to now 

We should remove it
`"deploy:now": "dcl export && now export",`

**Comment by ef3n9r98** [comment]
Hi @nearnshaw, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/
).


Thanks!
