### ISSUE TITLE
Define serialization protocol for CRDT messages

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#236]
As defined in https://diagrams.menduz.com/#/notebook/2l3t8FEx6Yc4GyDvkdDe4EQKf2L2/-MiSDLMvharXiZu6Vfjl an envelope message must be defined to send CRDT operations for entities and components. 

The proposed messages may look like this:

```protobuf
message WireMessage {
    repeated ComponentOperation operations = 1;
    repeated Query query = 2;
    repeated Responses query_response = 3;
}
 
message ComponentOperation {
    int32 message_type = 1;     // PUT_COMPONENT | DELETE_COMPONENT

    // the serialization/deserialization of the data depends is defined by this field 
    int32 component_class_id = 2; // ClassIdentifier number for the component kind

    int64 entity_id = 3;        // Entity number
 
    // We use lamport timestamps to identify components and to track in which order
    // a client created them. The key for the lamport number is key=(entity_id,component_number)
    int64 timestamp = 4;
 
    // @optional
    // missing data means the component was deleted
    bytes data = 5;
}
 
/*
# Open questions
 
  - What would happen if two scenes create a component for the first time, and both use the lamport number 1?
  - Should we generate random IDs for new dynamic entities?
    * we could claim buckets of random numbers every time we start a session to prevent collisions
*/
 
 
//// deprecate
message Query {
    int32 message_type = 1; // QUERY
    int64 query_type = 2; // RAYCAST | ...?
    reserved 3;
 
    // Serialized query
    bytes data = 5;
}
```

The serialization must consider optimized code for C# (speed & memory allocations) and Typescript. Also it would be a nice to have to have extensibility (possibility to add/remove fields) and multiple messages e.g `ComponentOperation` and `Query`. Another thing to consider is the serialization format of the `data` field itself, it can be flat buffers or protocol buffers (TBD)

Considerations for the analysis:
- Messages should be easy to concatenate in a file. Sequences of `ComponentOperation` can be used to serialize the state of a scene in a static file. The goal is to not use a different binary representation in this file.
- Multiple message types should be allowed over the wire.
- Memory allocations and execution speed must be prioritized, speed is a constraint

**Comment by leanmendoza** [comment]
This is an illustration of using protobuf to encode the wire message (the top-level message) through the transport.

Protobuf file:
```protobuf
syntax = "proto3";

message WireMessage {
  repeated ComponentOperation operations = 1;
}

message ComponentOperation {
  fixed32 message_type = 1;     // PUT_COMPONENT | DELETE_COMPONENT

  // the serialization/deserialization of the data depends is defined by this field 
  fixed32 component_class_id = 2; // ClassIdentifier number for the component kind

  fixed64 entity_id = 3;        // Entity number

  // We use lamport timestamps to identify components and to track in which order
  // a client created them. The key for the lamport number is key=(entity_id,component_number)
  fixed64 timestamp = 4;

  // @optional
  // missing data means the component was deleted
  bytes data = 5;
}
```
Example data
```ts
  {
    messageType: 0xfafafafa,
    entityId: 0xbebebebebebe,
    componentClassId: 0xcececece,
    timestamp: 0xdbdbdbdbdbdb ,
    data: new Uint8Array(Array.from({length: dataLength}, () => 255))
  }
```

Resulting:
![Screenshot_20220331_155359](https://user-images.githubusercontent.com/8042536/161128928-8976db8e-a233-4a13-bc3a-b60fce469e71.png)
There are three messages:
1. rawData = 0 bytes, message data 30 bytes
```
0a 1c 0d fa fa fa fa 15 ce ce ce ce 19 be be be be be be 00 00 21 db db db db db db 00 00 (+0 bytes)
```

2. rawData = 110 bytes, message data (without raw) 33 bytes
```
0a 8c 01 0d fa fa fa fa 15 ce ce ce ce 19 be be be be be be 00 00 21 db db db db db db 00 00 2a 6e (+110 bytes)
```

3. rawData = 220 bytes, message data (without raw) 34 bytes
```
0a fb 01 0d fa fa fa fa 15 ce ce ce ce 19 be be be be be be 00 00 21 db db db db db db 00 00 2a dc 01 (+220 bytes)
```

As you see, the difference between 2nd and 3rd is the length of raw data in the 3rd is greater than 127 so the 8th bit is used to indicate that there is one more byte to represent the lenght.


So, there are two points:
- It's not possible to do a flat copy to a struct
- It's not as fast as it could be, even having the fixed types this needs to be processed

**Comment by leanmendoza** [comment]
With flatbuffer happens a similar thing. 
Serializing is simpler in terms of primitive types having a fixed size, and you can use fixed type structs (e.g. a Vector3). This is an advantage of gaining time in the serialization.
Also, the flexibility of backward&forward compatibility is given by the `table` schema, it allows iterating in the versioning of the protocol as Protobuf does too.
But, flatbuffer has a referenced serialization. It puts all data at the end saving the offset and pushing in a stack. When a message is finished, this stack is processed and puts all the references at the beginning of bytes (more or less). This complicates the copying in a flat struct on the renderer side (e.g.: C# in case of Unity, C++ Godot) in a direct form. It'd be absolutely necessary to implement the FlatBuffer.

Following the previous protobuf example, here is an illustration of the same list of messages. It can be a little tricky.
In the flatbuffer schema there is no easy support for 8bytes integers, so avoiding wasting time in the implementation, only for illustration purposes, they were replaced by two 4bytes integers.
```
namespace Decentraland;

enum ComponentOperationType: uint32 {
  PUT_COMPONENT = 0,
  DELETE_COMPONENT = 1
}

table ComponentOperation {  
  message_type: ComponentOperationType;     // PUT_COMPONENT | DELETE_COMPONENT

  // the serialization/deserialization of the data depends is defined by this field 
  component_class_id: uint32; // ClassIdentifier number for the component kind

  entity_id_0: uint32;        // Entity number
  entity_id_1: uint32;        // Entity number

  // We use lamport timestamps to identify components and to track in which order
  // a client created them. The key for the lamport number is key=(entity_id,component_number)
  timestamp_0: uint32;
  timestamp_1: uint32;

  data: [ubyte];
}

table WireMessage {
  operations: [ComponentOperation];
}

root_type WireMessage;
```

![Screenshot_20220406_095644](https://user-images.githubusercontent.com/8042536/161979692-3f6900fd-5380-49bc-ba2c-c8a53cef8e04.png)

**Comment by leanmendoza** [comment]
A more plain approach is writing a header with a protocol version and a handler:
There is no list of messages as is, but there might be a sequence of messages.

```cpp
// This can not change ever
struct MessageHeader {
  // the length of message without counting this header 
  uint32_t length;

  // this can be a simple number or a compound number
  union {
    // can be an approach, major and minor from 0 to 255, patch from 0 to 65535
    struct {
      uint8_t major, minor;
      uint16_t patch;
    } v1;

    uint32_t number; 
  } versioning;
};
```

The backward compatibility would be managed by a set of handlers that ideally can recycle the older ones.

Version 0, following the previous example, can be:
```cpp 
struct WireMessage {
  ComponentOperationType messageType;     // PUT_COMPONENT | DELETE_COMPONENT

  // the serialization/deserialization of the data depends is defined by this field 
  uint32_t componentClassId; // ClassIdentifier number for the component kind

  uint64_t entityId;

  // We use lamport timestamps to identify components and to track in which order
  // a client created them. The key for the lamport number is key=(entity_id,component_number)
  uint64_t = timestamp;

  // the data is contiguous to this struct and the size is dataLength
  uint32_t dataLength;
};

enum class ComponentOperationType: uint32_t {
  PUT_COMPONENT = 0,
  DELETE_COMPONENT = 1
};

```

WIP

**Comment by leanmendoza** [comment]
Update:

Following the previous comment, a more clear approach was tested and implemented in https://github.com/decentraland/ecs. It's to add a type to the MessageHeader, and the maintenance would only be for the specific message. 

```cpp
struct MessageHeader {
    uint32_t length;
    MessageType type;
};

enum class MessageType: uint32_t {
    RESERVED = 0,
    CRDT_PUT_COMPONENT_OPERATION = 1,
    CRDT_DELETE_COMPONENT_OPERATION = 2
};
```

So, in this case, if we want to change the message, we'd add a type for example `V2_PROTOCOL_BUFFER_MESSAGE`. And then,
```ts
handler[MessageType.V2_PROTOCOL_BUFFER_MESSAGE] = ProtocolBufferHandler
// where
function ProtocolBufferHandler(buf: Uint8Array, length: number) {

}
```

As regards the current CRDT message, the body message is shared between PUT and DELETE component.
