### ISSUE TITLE
Define memory model for C# interop (ByteArray memory access, no C++ malloc) 

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#245]
renderer: https://github.com/decentraland/unity-renderer/pull/2286
kernel: https://github.com/decentraland/kernel/pull/285

**Comment by menduz** [comment]
@pbosio please include PRs

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/2286
kernel: https://github.com/decentraland/kernel/pull/285

**Comment by pbosio** [comment]
TODO: use byte array for websocket and remove the usage of base64 for those messages

**Comment by leanmendoza** [comment]
> TODO: use byte array for websocket and remove the usage of base64 for those messages

This will be ready to do when @dcl/rpc is ready to use.
