### ISSUE TITLE
Base parcel should be optional

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#28]
The base parcel field in scene.json should be optional, and not provided in the default scene.

It should be inferred as the bottom-left parcel, unless provided explicitly.

The base parcel should always be one of the parcels in the scene, so if the scene is L shaped and the bottom-left corner is missing then it should be picked by first taking the left-most column, then the lowest parcel in that column.

Choosing an arbitrary base parcel doesn't really bring any benefits, and it always brings problems when trying to reposition and deploy someone else's scene.

To maintain backwards compatibility with old scenes, we should still support base parcels being picked arbitrarily.

The default scene generated by the CLI with `dcl init` shouldn't include this field.

PD: I can't count how many times we discussed doing this in the last 3 years. And it's still not done.

**Comment by menduz** [comment]
This is like so by design, adding parcels should not change the center of coordinates.

**Comment by nearnshaw** [comment]
Let's discuss this when I'm back
This has always been extremely impractical
