### ISSUE TITLE
Implement Scene Boundaries Checker for SDK7 scenes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#285]
Current Scene Boundaries Checker system info: https://github.com/decentraland/unity-renderer/blob/dev/docs/scene-boundaries-checking.md

Currently, a scene can render an AvatarShape anywhere, even on their neighbor's land.
This can be used for evil, we want to control the positions of an AvatarShape just like we control any other entity so that it stays within scene bounds.

More context here:
https://www.notion.so/decentraland/RFC-Fake-Avatars-a85f9847267e47878f5113dcb1150712

------------------------------------
Implement SBC for SDK7 entities to evaluate them in the following cases:
 - [x] `GltfContainer`
 - [x] `MeshRenderer`
 - [x] `MeshCollider`
 - [x] `Transform` creation and update
 - [x] Entity creation
 - [x] Entity parenting operation (player/camera/other entity)
 - [x] NFT Shape
 - [x] Irregular-shaped meshes
 - [x] `AvatarShape`
 - [x] `TextShape`
 - [x] `AudioSource`

**Comment by pravusjif** [comment]
tackled at https://github.com/decentraland/unity-renderer/pull/3857

**Comment by pravusjif** [comment]
I'm unchecking the current 5 achieved objectives since we are changing the approach and starting from scratch.

**Comment by pravusjif** [comment]
New approach will be tackled at https://github.com/decentraland/unity-renderer/pull/3965
