### ISSUE TITLE
Preview Mode: Doesn't show any error screen on a fatal errors

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/sdk#289]
When we have a fatal error in PREVIEW, we don't show anything to the user.

![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/5b2b0868-74ef-4232-9fae-40966668e380)

How to reproduce:
- create empty scene `dcl init` -> `dcl start`
- open tab with this URL: `http://127.0.0.1:8000/?ws=asdasd` (`ws=asdasd` will produce a fatal error)

we should see this screen:
![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/0c446dfe-045a-4884-9307-5216b3f5c079)

**Comment by leanmendoza** [comment]
The screen cited is the `explorer-website` crash-screen. Preview has its own screen and it's working well from version 6.6.6 of `decentraland-ecs`.

![Screenshot_20220503_090304](https://user-images.githubusercontent.com/8042536/166449552-1fddceb6-f176-46ec-85c7-6e1755993de8.png)

This is an out-of-date issue.
