### ISSUE TITLE
AvatarShape setting hair & eye color

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#318]
Looks like the recent changes of setting of hair and eye color had an effect when setting these properties in AvatarShape

It's not clear how to pass values to these properties, and the TypeScript type checking seems not to be updated to whatever types are now required

See this example:
https://github.com/decentraland-scenes/avatar-mirror

It includes the following lines. these don't show any error, but they don't actually change the color, the color is always black

```ts
this.avatarShape.skinColor = Color4.FromHexString(avatar.skinColor);
this.avatarShape.hairColor = Color4.FromHexString(avatar.hairColor);
this.avatarShape.eyeColor = Color4.FromHexString(avatar.eyeColor);
```

Someone in the community proposed the following workaround that does work:

```ts
this.avatarShape.skinColor = (avatar as any).skin.color;
this.avatarShape.hairColor = (avatar as any).hair.color;
this.avatarShape.eyeColor = (avatar as any).eyes.color; 
```

I suppose the solution is to make the type of these properties match whatever type is being used by the values passed there

**Comment by menduz** [comment]
Fixed on SDK7 component. Won't fix for SDK6
