### ISSUE TITLE
Get metrics about current usage

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#32]
- WAU
- WoW retention
- Activated users per week
- Returning users

**Comment by nearnshaw** [comment]
Some other ideas:

- Deploys per SDK version
- Deploys per CLI version
- % of failed builds on preview
- average preview executions per active developer
- average preview open time per active developer
- hot reload success rate: % of times that a hot reload is manually refreshed after less than 3 seconds (or some other interval)

- ability to track the usage of any new feature
