### ISSUE TITLE
Hot-reload in portable experiences

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#320]
Workaround (PR Merged):
- https://github.com/decentraland/kernel/pull/306

Without the workaround:
- When you stop a portable experience and immediately try to spawn it, the spawn often fails.

The problem:
- Kernel deletes the scene and creates another one immediately with the same id. When it sends the UnloadScene to unity, unity adds it to a pending delete list. Before the unload does, kernel sends the creation of a scene id that Unity doesn't remove yet.

In the unity-side:
1. When unity receives the unload scene: https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs#L730
2. Unity checks if the scene is loaded: https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs#L664
3. Unity finally remove the scene in the dictionary: https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs#L752

**Comment by nearnshaw** [comment]
no longer relevant (we need to implement all PX in E@)
