### ISSUE TITLE
Fix default texture flipping

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#322]
Pending task list for the texture resource.
- [x] Eliminate default vertical flip in textures, video texture and normal textures should have the same orientation in a plane
- [x] Ensure that default UVs for planes are flipped to show videos and textures with the vertical flip
- [ ] https://github.com/decentraland/sdk/issues/64

**Comment by pbosio** [comment]
standardize textures orientation: https://github.com/decentraland/unity-renderer/pull/4187
**pending "domains allow list" for base64 deprecation issue

**Comment by nearnshaw** [comment]
@pbosio   can we consider this issue closed and track the base64 deprecation on this other ticket? 
https://github.com/decentraland/sdk/issues/64

I added this other ticket to the 7.1 board too

**Comment by pbosio** [comment]
> @pbosio can we consider this issue closed and track the base64 deprecation on this other ticket? #64
> 
> I added this other ticket to the 7.1 board too

yeap
