### ISSUE TITLE
Protobuff code generation introduced performance regression

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#323]
Recently this performance regression was introduced in production. After some commit hunting I detected the regression commit.

**regression commit**: https://github.com/decentraland/unity-renderer/commit/e5b5942ce445c0412b2f4aaec4c44b4ba8e2368a
**regression build**: https://play.decentraland.org/?renderer-version=1.0.36560-20220519091939.commit-e5b5942&NETWORK=ropsten&position=60,-71

https://user-images.githubusercontent.com/1031741/170351179-2435eb05-b63a-4e58-b737-02db035fb75d.mp4

**pre-regression commit**: https://github.com/decentraland/unity-renderer/commit/1887d5232902b18eba6d63a70b88959cb1fc20b1
**pre-regression build**: https://play.decentraland.org/?renderer-version=1.0.36507-20220518190325.commit-1887d52&NETWORK=ropsten&position=60,-71

https://user-images.githubusercontent.com/1031741/170351286-47481458-dabd-44cb-bcb9-05dc36be3df5.mp4

**Comment by Suduck** [comment]
Fixed in https://github.com/decentraland/unity-renderer/pull/2360
