### ISSUE TITLE
Define the deault parameters of the ECS components

### ISSUE THREAD

**Issue by Suduck** [decentraland/sdk#334]
- [ ] Check the default value that each parameter in the component should have in the case that is not defined by the user.

- [ ] Figure out how to create a component (while developing the scene) without specify all the parameters

**Comment by leanmendoza** [comment]
> Check the default value that each parameter in the component should have in the case that is not defined by the user.

As we're using ProtocolBuffer to serialize the components, we can adopt their default values. They're the natural default values, as an int = 0, string empty, array an empty array. 
If we don't adopt these default values as defaults, we need to reach a consensus in all the parts what happens with a particular field of a specific component when the parameter didn't go through the wire. 

Align with that, I think the most healthy approach is to create the component with this principle, so when we need to add a field, the "natural value" has to be equal to the default value. For example, creating the component BoxShape, the natural value is to be visible, but the property `visible` is a boolean with a `false` default value. In this case, the property should be `hidden` and the default value would be `false`, the BoxShape by default would be visible.

> Figure out how to create a component (while developing the scene) without specifying all the parameters

With the first approach, the proto-generation code on the Typescript side should have the `optional` option enabled, so we could create a BoxShape with `sdk.BoxShape.create(entity)` without parameters.

**Comment by Suduck** [comment]
The problem is that we are changing too much the way that things works today and It will be a pain in the ass for the content creators to migrate to the new ECS and change their mindsets

**Comment by gonpombo8** [comment]
closed via https://github.com/decentraland/protocol/pull/20
