### ISSUE TITLE
Bug on ubuntu 20.04

### ISSUE THREAD

**Issue by RaidelRoss** [decentraland/sdk#337]
Error running a project on ubuntu

step 1:
`npm install -g decentraland`

Step 2: _create a simple project_
`dcl init`

Step 3: _installing project dependencies and running_
`dcl start`

![173111901-69952902-ee99-426b-9512-1071f103263f](https://user-images.githubusercontent.com/36287019/173115617-1c4c635c-fd1a-4830-bd0b-f6866a4edd6c.png)
![173112070-b2331791-a439-4387-802c-45c3b5f05dbb](https://user-images.githubusercontent.com/36287019/173115640-494f65c2-354d-4522-8130-caf1eac0f17a.png)

_when trying to access it gives an error_

![173112150-da2fbdcb-395d-4361-9909-3cb3ebc6b245](https://user-images.githubusercontent.com/36287019/173115666-742c95cd-bbec-451c-a753-df1827962838.png)

Thank. regards

**Comment by leanmendoza** [comment]
@RaidelRoss Thanks for reporting! Could you report what version of node/npm are you using? 
I couldn't reproduce it in Kubuntu 20.04, I'm using node 16, npm 8

**Comment by leanmendoza** [comment]
Anyway, try running `npm i @dcl/schemas@4.8.0` and see if the error gets away.

**Comment by bariguana** [comment]
thanks for your reply

his proposal was effective

> Anyway, try running `npm i @dcl/schemas@4.8.0` and see if the error gets away.

everything works fine again

------------------------------------
I use these versions:
  node:v14.19.3
  npm: 6.14.17
 
------------------------------------
I will install node 16 and npm 8

Thank you

**Comment by RaidelRoss** [comment]
thanks for your reply

his proposal was effective

> Anyway, try running `npm i @dcl/schemas@4.8.0` and see if the error gets away.

everything works fine again

------------------------------------
I use these versions:
  node:v14.19.3
  npm: 6.14.17
 
------------------------------------
I will install node 16 and npm 8

Thank you
