### ISSUE TITLE
CameraEntity and PlayerEntity in ECS and Renderer

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#339]
Those will be new reserved entities (static number below 512). Documented at https://github.com/decentraland/sdk/blob/main/docs/static-entities.md

Those entities will receive CRDT messages from the renderer with Transform components to replace the `positionChanged` and `rotationChanged` events.

The CRDT messages for transforms of both entities will be ignored by the renderer. We can leverage this to later setup a permission system for whom can update which components of each entity.

Entities children of PlayerEntity and CameraEntity will be used achieve the feature parity of the attach to camera and avatar functions of the SDK6

**Comment by pbosio** [comment]
https://github.com/decentraland/unity-renderer/pull/2663
renderer is sending the Transform for Camera and Player entities
