### ISSUE TITLE
PointerEvents component (Replaces PointerDown & PointerUp)

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#352]
As per CRDT formal definition of Observed-Remove Set (OR-Set), the pointer up and pointer down events should have two independent result components to extract the click information out of the full list of CRDT messages.

The current (7.0.0 alpha) implementation has a shared component `PointerResult` for both PointerUp and PointerDown components. Rendering the following scenario impossible:

```scala
// first configure components in the scene
Scene->Renderer: PUT(Entity(0), PointerDown(id=1))
Scene->Renderer: PUT(Entity(0), PointerUp(id=2))
// (flush messages)
// the renderer now receives two events
  event MouseDown():
    Renderer->Scene: PUT(Entity(0), PointerResult(id=1,down=true))
  event MouseUp():
    Renderer->Scene: PUT(Entity(0), PointerResult(id=1,down=false))

// (frame, flush messages)
❌ the only message sent is the last PointerResult
```

Which is in practice a LWW-Element-Set CRDT.

The proposed solution unifies PointerDown and PointerUp components into one single PointerEvents component with a list of all the pointer commands executed during the time window. This approach is inspired in the [netcode presentation of Overwatch ECS](https://www.gdcvault.com/play/1024001/-Overwatch-Gameplay-Architecture-and). The list of last N commands enables extracting all the needed information to not loose any data and to enable extensibility. Every command have a global Lamport timestamp to preserve the global sequence order of pointer events.

In the first approach, only the RootEntity will receive the PointerEvents component from the engine. The scene code will fetch the information from this entity to use the helper functions to detect input events for every entity.

```protobuf
// this component will enable pointer events in this entity and its meshes
message PointerEvents {
  map <InputEnum, string> hover_messages = 2; // hover messages
}

// reused from RaycastComponent https://github.com/decentraland/sdk/issues/359
message RaycastHit {
    Vector3 world_position = 1;
    Vector3 origin = 2;
    optional string mesh_name = 3;

    // NOTE: optional added
    optional int32 entity_id = 4;

    Vector3 world_normal_hit = 5;
    float length = 6;
}

// the renderer will set this component to the entity after every pointer event
message PointerEventsResult {
  // a list of the last N pointer commands (from the engine)
  repeated PointerCommand commands = 1;

  // this message represents a raycast, used both for UP and DOWN actions
  message PointerCommand {
    InputEnum input_id = 1; // identifier of the input
    optional RaycastHit hit = 2;
    StateEnum state = 4;
    int32 timestamp = 5; // could be a Lamport timestamp
    optional float analog = 6; // if the input is analog then we store it here

    // added ray origin information
    Vector3 origin = 7;
    Vector3 direction = 8;
  }

  enum StateEnum {
    StateEnum_UP = 0;
    StateEnum_DOWN = 1;
    StateEnum_ANALOG = 2;
    StateEnum_HOVER_ENTER = 3;
    StateEnum_HOVER_LEAVE = 4;
  }
}
```

```scala
// first configure components in the scene
Scene->Renderer: PUT(Entity(0), PointerEvents(command_counter=10))
// (flush messages)
// the renderer now receives two events
  event MouseDown():
    Renderer->Scene: PUT(Entity(0), PointerEventsResult(commands.append( PointerCommand(DOWN, now) ))
  event MouseUp():
    Renderer->Scene: PUT(Entity(0), PointerEventsResult(commands.append( PointerCommand(UP, now) ))
// (frame, flush messages)
✅ only one message is flushed, with the latest state of all PointerEvents for the frame
```

With the help of some logic, we can infer lots of information from those commands in the messages:

```typescript
function wasEntityClicked(entity: Entity, inputNumber: number): boolean {
  const commands = PointerEventsResult.get(entity).commands
  const down = commands.findLastDownAction(inputNumber)
  const up = commands.findLastUpAction(inputNumber)
  if (down.timestamp < up.timestamp) return true // clicked
  return false
}

function isActivePointerDown(entity: Entity): boolean {
  const commands = PointerEventsResult.get(entity).commands
  const down = commands.findLastDownAction(inputNumber)
  const up = commands.findLastUpAction(inputNumber)

  if (!down) return false
  if (!up) return true // currently pressed
  if (down.timestamp > up.timestamp) return true // up component is from an old click
  else return false
}
```

# Root entity behavior

The RootEntity can intercept all pointer events regardless of a raycast hit or not. It is used to get the input information and the direction of every input event (including analog events). The RootEntity is used by the helpers

# Update 2022/09/13
`PointerEventsResult` would work independent from `PointerEvents` meaning that every input against a collider on the "pointer" layer will be added to the `PointerEventsResult` commands regardless of the entity containing or not a `PointerEvent` component

**Comment by Suduck** [comment]
Protocol PR: https://github.com/decentraland/protocol/pull/35
js-sdk-toolchain PR: https://github.com/decentraland/js-sdk-toolchain/pull/241
unity PR:  https://github.com/decentraland/unity-renderer/pull/2930

**Comment by Suduck** [comment]
For now, we have added some helpers that can help with this new implementation.  Those helpers functions are wasEntityClicked and isPointerEventActive.

Take into account that, right now, this functions will only return true 1 time. This means that if an entity has been clicked in this update tick, and you call it from two differents systems (for the same entity, action button, and pointer event type) it will only return true for the first call. (This will change but for now, I think that this can cover most of the uses-cases while we prepare a more mature way)

Examples:
```
if(isPointerEventActive(entity, ActionButton.PRIMARY, PointerEventType.DOWN)){
  const material =  Material.getMutable(cube)
  material.albedoColor =  {
    r: Math.random(),
    g: Math.random(),
    b: Math.random()
  }
}

if(wasEntityClicked(entity, ActionButton.PRIMARY)){
  const material =  Material.getMutable(cube)
  material.albedoColor =  {
    r: Math.random(),
    g: Math.random(),
    b: Math.random()
  }
}
```

**Comment by leanmendoza** [comment]
> Take into account that, right now, this functions will only return true 1 time. This means that if an entity has been clicked in this update tick, and you call it from two differents systems (for the same entity, action button, and pointer event type) it will only return true for the first call. (This will change but for now, I think that this can cover most of the uses-cases while we prepare a more mature way)

I changed the approach to a simpler one, making a global state linked to the root entity. This behavior is modified to:
- Each active event lasts through the tick-update. You can query the `wasEntityClicked` in several systems but in the next updates is cleared.

**Comment by pbosio** [comment]
Added following update to the issue:

> `PointerEventsResult` would work independent from `PointerEvents` meaning that every input against a collider on the "pointer" layer will be added to the `PointerEventsResult` commands regardless of the entity containing or not a `PointerEvent` component
