### ISSUE TITLE
Visibilitycomponent

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#353]
As of ECS6, the visibility of a shape is a property of the GLTFShape or BoxShape components (to name a few).

In the ECS7, the visibility will be a separated component. There are two possibilities, use a [tag component](https://gametorrahod.com/tag-component/), a tag is a no-data component that only describes some aspects of the entity that it belongs to, for example a `HiddenComponent()` or `DeadComponent()`. Or a fully featured component `VisibilityComponent(visible=true)`.

For the sake of simplicity and correctnes (to prevent default values and also to save bandwidth, my recommendation is to use a tag `HiddenComponent()` to make an entity and its children invisible.

The renderer should make invisible and non-interactable the entity with the component and all its descendants. It should also make the colliders not work.

**Comment by kuruk-mm** [comment]
Following work for this: https://github.com/decentraland/sdk/issues/427
