### ISSUE TITLE
VideoTextureState

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#360]
Open conversation:

VideoTextures are resources, but their state is also part of the resource, because two videos at two different seek points, are indeed two different textures.

And as two textures those should count as two resources. But loading videos is very expensive in terms of CPU and bandwidth.

A _very common and widespread_ use case for video textures is to have only one texture shared across many different shapes to create show stages with multiple UV mapped screens.
The chosen approach should contemplate:

- the resource-sharing approach described above
- the ease of use of setting and getting the current video state from the renderer

**Comment by leanmendoza** [comment]
Today the textures are referenced in the Material component as `TextureUnion` 
https://github.com/decentraland/protocol/blob/main/proto/decentraland/common/texture.proto

It could have an approach that sastifies the requirement above:
- The state that **defines** or **determines** the texture itself would be in another entity.
- The `TextureUnion` **oneof** would have the reference, this way we'd be creation a piece of indirection

This behavior would be useful for other many cases, such as CameraViewport, or a WearablePreviewViewport.

For the VideoTexture the protocol suggested would be:
- To add a new component with the `VideoState`:
```ts
type VideoTextureState = {
    src: string
    playing: boolean
    position: number
}
```
- To add the indirection in TextureUnion
```pb
message VideoTexture {
  entity: int32
}

message TextureUnion {
 oneof texture {
    ...
    VideoTexture video_texture = x;
  }
}

```

**Comment by nearnshaw** [comment]
@kuruk-mm   why was this issue reopened?  can't we consider it solved?
My understanding is that we're already handling the video texture as a separate reusable asset that can be shared on various materials
