### ISSUE TITLE
Send `sceneNumber` to renderer along with `sceneId`

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#362]
Come up with a monotonic ID generator for scene runtime IDs to replace the `sceneId: string`. It will gratefully impact the performance of the renderer.

- [ ] https://github.com/decentraland/unity-renderer/pull/2852
- [ ] https://github.com/decentraland/unity-renderer/issues/2582
- [x] https://github.com/decentraland/protocol/pull/26
- [x] https://github.com/decentraland/protocol/pull/25

**Comment by pravusjif** [comment]
Completed at https://github.com/decentraland/unity-renderer/pull/2977

**Comment by pravusjif** [comment]
merged https://github.com/decentraland/unity-renderer/pull/2977
