### ISSUE TITLE
Unequivocal entity ids

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#364]
# Approaches
1. Do not use entities that have been used in the past
2. Add entity version to distinguish between two entities with the same id

# Corner cases to handle
Today, when you call `engine.addEntity()` the engine looks for an unused id that it's already been used. So, this can introduce the next scenario:
**`Scene> Create Entity > entity=#1 , add box-shape and transform components`
`Scene> ... create other entities and update entity=#1`**

The state of the entity#1
- components = { BoxShape {timestamp = 101, data={visible, ...}}, Transform {timestamp = 2, data={position, .....}} }

**`Scene> Remove entity#1, so now the state is`**
- deleted = true
- components = { BoxShape {timestamp = 102, data=null}, Transform {timestamp = 3, data=null} }

**`Scene> Call engine.addEntity() and this returns the entity #1`**

If we repeat this with more components, the CRDT state of this Entity would be mostly trash.
If this entity is synchronizable, because of its ID history, there will be a lot of useless data moving.

**Comment by nearnshaw** [comment]
@leanmendoza  
Can this issue be considered resolved?  As far as I know we found a solution for this, right?

**Comment by leanmendoza** [comment]
Yes, it's solved
