### ISSUE TITLE
Definition: optional in components

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#365]
To deal with extensible protocols requires an essential feature: Optional data.

Based on the principle of [Tolerant Readers](https://martinfowler.com/bliki/TolerantReader.html), it is easy and fairly safe to add extra information to the serialization of a schema.

In the following example, both sentences are safe, and we are adding new data to the same type. It illustrates how data can be added without breaking compatibility:

```ts
type TypeAt2020 = { a: number, b: string }
const dataAt2020: TypeAt2020 = { a: 1, b: "hello" }
const dataAt2022: TypeAt2020 = { a: 1, b: "hello", c: "something new" }
```

The following on the other hand, doesn't work because the `b: string` is required:

```ts
type TypeAt2020 = { a: number, b: string }
const dataAt2020: TypeAt2020 = { a: 1, b: "hello" }
const dataAt2022: TypeAt2020 = { a: 1 } ❌
```

The tolerant readers principle states that you must _be conservative on what you read and strict on what you produce_, so serialized the data type must contain always ALL the required fields.

The same applies to types, adding new fields is only viable when the deployed software is compatible with the datatype, and adding a required field will definitely break the synchronization of the system

```ts
type TypeAt2020 = { a: number, b: string }
const dataAt2020: TypeAt2020 = { a: 1, b: "hello" }
type TypeAt2022 = { a: number, b: string, c: boolean }

// ❌  c is missing in type TypeAt2020 and required in TypeAt2022
conct dataAt2022: TypeAt2022 = dataAt2020 ❌ 
```

A walkaround for this limitation is to introduce optional types, making this scenario compliant and conflict free, both for internal systems and serialization

```ts
type TypeAt2020 = { a: number, b: string }
const dataAt2020: TypeAt2020 = { a: 1, b: "hello" }
type TypeAt2022 = { a: number, b: string, c?: boolean }

const dataAt2022: TypeAt2022 = dataAt2020 ✅
```

---

This mental model is applied in the [proto-compatibility-tool ](https://github.com/well-known-components/proto-compatibility-tool) and we are reusing the logic for our components. Newer versions of protobuf3 support the `optional` keyword, we are using the `optional` to extend new types.

An important part of this definition is that the systems USING the component will decide the default values, and those MUST NOT be serialized and broadcasted over the network.

A practical example is the addition of a `optional boolean visibility` field to a component. The rendering system will decide the default value for `visibility` based on its absence. It must NOT set the "default" value back to the component, keeping it "null/undefined".

**Comment by Suduck** [comment]
Another thing to consider is how the final user creates a component.

If we don't use optional in all the fields that are not strictly necessary, the users need to specify each value, each time it is creating a component. This can be confusing since the user may not know what the default value is.

As an example, take the `TextShape ` component creation. If we don't use optional, the user needs to specify all these values:

```    
TextShape.create(entity, {
      text: 'Hello world',
      visible: false,
      font: 'false',
      opacity: 0,
      fontSize: 15,
      fontAutoSize: false,
      hTextAlign: 'vertical',
      vTextAlign: 'horizontal',
      width: 200,
      height: 200,
      paddingTop: 211,
      paddingRight: 212,
      paddingBottom: 213,
      paddingLeft: 214,
      lineSpacing: 215,
      lineCount: 216,
      textWrapping: false,
      shadowBlur: 218,
      shadowOffsetX: 219,
      shadowOffsetY: 220,
      outlineWidth: 221,
      shadowColor: { r: 1, g: 1, b: 1 },
      outlineColor: { r: 1, g: 1, b: 1 },
      textColor: { r: 1, g: 1, b: 1 }
    })
 ```

The user may not know what `shadowBlur ` is and it should try every value until it finds something that works. This will be almost impossible to code since you need to understand perfectly a component to make use of it.


However, if we use optional for all properties you could do something like this:

```    
TextShape.create(entity, {
      text: 'Hello world',
    })
 ```

And the renderer has the responsibility to assign the default values even if the user doesn't specify it

**Comment by Suduck** [comment]
Also, another thing to have into consideration is the amount of data that is passed through the wire. 

For example, take into consideration the following component:

```
 UiTransform.create(entity, {
      parent: 0,
      alignContent: YGAlign.YGAlignCenter,
      alignItems: YGAlign.YGAlignFlexEnd,
      alignSelf: YGAlign.YGAlignFlexStart,
      borderBottom: 1,
      borderLeft: 1,
      borderRight: 1,
      borderTop: 1,
      direction: YGDirection.YGDirectionLTR,
      display: YGDisplay.YGDisplayNone,
      flex: 1,
      flexBasis: 3,
      flexBasisUnit: YGUnit.YGUnitPoint,
      flexDirection: YGFlexDirection.YGFlexDirectionColumnReverse,
      flexWrap: 1,
      flexGrow: 4,
      flexShrink: 1,
      height: 1,
      heightUnit: YGUnit.YGUnitPoint,
      justifyContent: YGJustify.YGJustifyFlexEnd,
      marginBottom: 1,
      marginBottomUnit: YGUnit.YGUnitPoint,
      marginLeft: 1,
      marginLeftUnit: YGUnit.YGUnitPoint,
      marginRight: 1,
      marginRightUnit: YGUnit.YGUnitPoint,
      marginTop: 1,
      marginTopUnit: YGUnit.YGUnitPoint,
      maxHeight: 1,
      maxHeightUnit: YGUnit.YGUnitPoint,
      maxWidth: 1,
      maxWidthUnit: YGUnit.YGUnitPoint,
      minHeight: 1,
      minHeightUnit: YGUnit.YGUnitPoint,
      minWidth: 1,
      minWidthUnit: YGUnit.YGUnitPoint,
      overflow: YGOverflow.YGOverflowVisible,
      paddingBottom: 1,
      paddingBottomUnit: YGUnit.YGUnitPercent,
      paddingLeft: 1,
      paddingLeftUnit: YGUnit.YGUnitUndefined,
      paddingTopUnit: YGUnit.YGUnitPoint,
      paddingRight: 1,
      paddingRightUnit: YGUnit.YGUnitPoint,
      paddingTop: 1,
      positionBottom: 1,
      positionBottomUnit: YGUnit.YGUnitPoint,
      positionLeft: 1,
      positionLeftUnit: YGUnit.YGUnitPoint,
      positionRight: 1,
      positionRightUnit: YGUnit.YGUnitPoint,
      positionTop: 1,
      positionTopUnit: YGUnit.YGUnitPoint,
      positionType: YGPositionType.YGPositionTypeRelative,
      width: 1,
      widthUnit: YGUnit.YGUnitPoint
    })
```

Even if we only want to set the width for this component, and we don't see them as optional, we will send all the data of each field. 

However, if we put optional in the proto, we will only send the width and the renderer will set the default value for the rest of the fields, This will reduce the amount of data send in the wire

**Comment by kuruk-mm** [comment]
Closed by https://github.com/decentraland/js-sdk-toolchain/pull/218
