### ISSUE TITLE
SDK7 feature parity with SDK6

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#369]
# Full Feature parity checklist

These are all the features currently available in SDK 6, that we should support on SDK7

## Definitions
- [x] https://github.com/decentraland/sdk/issues/397
- [x] https://github.com/decentraland/sdk/issues/394
- [x] https://github.com/decentraland/sdk/issues/388
- [x] https://github.com/decentraland/sdk/issues/356
- [x] https://github.com/decentraland/sdk/issues/340
- [x] https://github.com/decentraland/sdk/issues/304
- [x] https://github.com/decentraland/sdk/issues/305

## Base components

- [x] https://github.com/decentraland/sdk/issues/405
- [x] https://github.com/decentraland/sdk/issues/406
- [x] https://github.com/decentraland/sdk/issues/415
- [x] https://github.com/decentraland/sdk/issues/414
- [x] https://github.com/decentraland/sdk/issues/411 
- [x] https://github.com/decentraland/sdk/issues/410
- [x] https://github.com/decentraland/sdk/issues/412
- [x] https://github.com/decentraland/sdk/issues/413
- [x] https://github.com/decentraland/sdk/issues/416
- [x] https://github.com/decentraland/sdk/issues/404
- [x] https://github.com/decentraland/sdk/issues/407
- [x] https://github.com/decentraland/sdk/issues/408
- [x] https://github.com/decentraland/sdk/issues/418
- [x] https://github.com/decentraland/sdk/issues/420
- [x] https://github.com/decentraland/sdk/issues/409
- [x] https://github.com/decentraland/sdk/issues/399
- [x] https://github.com/decentraland/sdk/issues/395
- [x] https://github.com/decentraland/sdk/issues/361
- [x] https://github.com/decentraland/sdk/issues/403
- [x] https://github.com/decentraland/sdk/issues/366
  - [x]  https://github.com/decentraland/sdk/issues/426
  - [x] https://github.com/decentraland/sdk/issues/435
- [x] https://github.com/decentraland/sdk/issues/417 and https://github.com/decentraland/sdk/issues/367
- [x] https://github.com/decentraland/sdk/issues/353
- [x] https://github.com/decentraland/sdk/issues/352
- [x] https://github.com/decentraland/sdk/issues/421
- [x] https://github.com/decentraland/sdk/issues/419
- [ ] https://github.com/decentraland/sdk/issues/360
- [ ] https://github.com/decentraland/sdk/issues/357
- [x] https://github.com/decentraland/sdk/issues/359 
- [x] Textures

## Special components
- CameraEntity
  - [x] `PointerLocked` component
    - [x] https://github.com/decentraland/sdk/issues/395
  - [x] `CameraMode` component (first, third, distance to player)
    - [x] https://github.com/decentraland/sdk/issues/395

## Entities

- [x] https://github.com/decentraland/sdk/issues/339
- [x] Root entity

### player connected observable (other players) player disconnected observable (other players)
  - [x] **Feature parity**: Temporary keep `onPlayerDisconnectedObservable` and `onPlayerConnectedObservable` (ECS6)

### player entered scene observable (any player) ### player left scene observable (any player)
  - [x]  **Feature parity**: Temporary keep `onEnterSceneObservable` and `onLeaveSceneObservable` (ECS6)

### player changes camera mode observable (current player)
  - **Feature parity**: 
    - [x] Component of the CameraEntity	

### player plays animation observable (current player)
  - [x] **Feature parity**: `onPlayerExpressionObservable` (ECS6)

### Current player clicks on another player observable (includes userId, & ray data)
  - [x] **Feature parity**: `onPlayerClickedObservable` (ECS6)

### player locks/unlocks	 cursor observable (current player)
  - **Feature parity**: 
    - [x] RootEntity.PointerLocked component present

### player goes idle/returns from idle observable  (current player)
  - **Feature parity**:
    - [x] Component of the CameraEntity

### player changes profile observable (any player) (includes name, wearables list, etc)
  - [x] **Feature parity**: `onProfileChanged` (ECS6)

### scene finished loading observable
  - [x] **Feature parity**: `onSceneReadyObservable` (ECS6)

### videoTexture changed state observable (playing/paused/etc)
  - [x] **Feature parity**: `onVideoEvent` (ECS6)

### player changes realm or island observable
  - [x] **Feature parity**: `onRealmChangedObservable` (ECS6)

### use message bus
- [x]  **Feature parity**:  `MessageBus` https://github.com/decentraland/sdk/issues/454

### get a full list of connected players
  - [x] **Feature parity**: `import getConnectedPlayers() from '~system/Players'` from `kernel-api-rpc`
  
### get a full list of players currently in the scene
  - [x] **Feature parity**: `import getPlayersInScene() from '~system/Players'` from `kernel-api-rpc`

### player position / feetPosition / worldPosition  & rotation in eurler & quaternion
  - [x] **Feature parity**: PlayerEntity.Transform

### player data: name, id, publicKey, hasConnectedWeb3, avatar (wearables, bodyshape, skin color, snapshots, etc), version
  - [x] **Feature parity**: `import { getPlayerData } from '~system/Players'` from `kernel-api-rpc`

### same data for any nearby player by ID (from renderer)
  - [x] **Feature parity**: `import { getPlayerData } from '~system/Players' // with { userId } as param` from `kernel-api-rpc`

### same data for any player by ID (from catalysts) (use fetch)
  - [x] Ok

### get decentraland time
  - [x] **Feature parity**: `import { getDecentralandTime } from '~system/EnvironmentAPI'` from `kernel-api-rpc`
  
### get player realm, server URL, server name
  - [x] **Feature parity**: `import { getCurrentRealm } from '~system/EnvironmentAPI'` from `kernel-api-rpc`
  
### get player platform (desktop / browser)
  - [x] **Feature parity**: `import { getPlatform } from '~system/EnvironmentAPI'` from `kernel-api-rpc`
  
### get active portable experience
  - [x] **Feature parity**: `import { getPortableExperiencesLoaded } from '~system/PortableExperiences'` from `kernel-api-rpc`
  
### get player's current camera mode
  - [x] **Feature parity** CameraEntity.CameraMode component

## Scene data:

- [x] Fetch full metadata, including parcels, spawnpoints, title, tags, etc
	- [x] **Feature parity**: `import { getParcel } from '~system/ParcelIdentity'` from `kernel-api-rpc`

## Events

All these events were found in the repositories `js-sdk-toolchain@6.x.x`, `unity-renderer`, `kernel` and `posix`.
The ones used by the ECS6 are the actually that need to have a fallback for the feature parity.

### Used by ECS6 (js-sdk-toolchain branch 6.x.x) 
Ticked means it's tracked.
- [x] **positionChanged**: 
	- [x] PlayerEntity.Transform.position
- [x] rotationChanged : 
	- [x] PlayerEntity.Transform.position
- [x] cameraModeChanged
	- [x] CameraEntity.CameraMode
- [x] onEnterScene: See point **Observables 3)**
- [x] onLeaveScene: See point **Observables 4)**
- [x] idleStateChanged: See point **Observables 10)**
- [x] sceneStart: See point **Observables 11)**
- [x] playerExpression: See point **Observables 6)**
- [x] videoEvent: See point **Observables 12)**
- [x] onPointerLock: See point **Observables 8)**
- [x] playerConnected: See point **Observables 1)**
- [x] playerDisconnected: See point **Observables 2)**
- [x] profileChanged: See point **Observables 10)**
- [x] onRealmChanged: See point **Observables 13)**
- [x] playerClicked: See point **Observables 7)**
- [x] comms 
- [x] uuidEvent
- [x] raycastResponse
- [x] actionButtonEvent
- [x] pointerUp
- [x] pointerDown

## Other functionalities:

- [x] movePlayerTo() - inside scene 
	https://github.com/decentraland/sdk/issues/356 
- [x] teleportTo() - to other scenes (keep it as it is✅)
- [x] openExternalLink() (keep it as it is✅)
- [x] fetch() (keep it as it is✅)
- [x] signedFetch() (keep it as it is✅)
- [x] websockets events, socket.onmessage (keep it as it is✅)
- [x] EventConstructor() events.fireEvent()  / events.addListener() 
	remove events entirely?
- [x] Global button events

## Helpers:

- [x] Set rotation w Euler
- [x] Vector3 & its functions
- [x] Quaternion  & its functions
- [x] System explicit execution order https://github.com/decentraland/sdk/issues/361 

## UI Support https://github.com/decentraland/sdk/issues/424

- [x] UiText
- [x] UiImages

## Docs
- [x] https://github.com/decentraland/sdk/issues/327

**Comment by gonpombo8** [comment]
pending features are tracked here https://github.com/decentraland/sdk/issues/442
