### ISSUE TITLE
add `minCommandLineVersion` to `package.json`

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#37]
- [ ] In the `decentraland-ecs/package.json` add a `minCommandLineVersion` field, to ensure compatibility _from_ the [decentraland/cli](https://github.com/decentraland/cli) with that version of the ECS.
- [ ] In [decentraland/cli](https://github.com/decentraland/cli), when the `minCommandLineVersion` is present, validate against current version and prevent `start|deploy|export` interactions if the min version is lesser than the current version. Use `npm i semver` to compare versions

**Comment by leamendoza97** [comment]
@menduz 
duplicated in #39?

**Comment by menduz** [comment]
Yes, closing this one.
