### ISSUE TITLE
CRDT repo: Handle the buffer support or remove it

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#372]
This workaround https://github.com/decentraland/crdt/pull/54 was necessary to be able to receive messages in the browser.
OQ: Does Buffer have to be removed or handle its support?

**Comment by menduz** [comment]
In Node.js Buffer exists and it is the default structure to handle byte arrays. But it is at the end of the day, a class extension of Uint8Array.

As a rule of thumb for all the projects, I'd support Uint8Array OOTB and Buffer should work OOTB as well
