### ISSUE TITLE
sdk issues of loading blocking

### ISSUE THREAD

**Issue by billygogo** [decentraland/sdk#376]
hello. 

After the sdk update, the loading screen appears and stops even though the basic cube span project was created and executed.

I updated  decentraland sdk yesterday.
using this:       
npm install -g decentraland
npm i decentraland-ecs@latest

following  the SDK getting started guide.
and make new folder
      dcl init  
       - Scene select 
       - Cube spawner  select
and download example totally.
![image](https://user-images.githubusercontent.com/95423215/177967657-ec987f9d-6e31-48b3-a92e-8520bf31cec0.png)

     dcl start 
The loading screen is no longer progressing.
![image](https://user-images.githubusercontent.com/95423215/177967838-017c6c13-4e9f-471b-b9be-b0d4d070d8ee.png)

this is browser error message
![image](https://user-images.githubusercontent.com/95423215/177968015-34f0241b-25b5-4b0c-851b-63bf71e9a8cb.png)

all browser(chrome, edge, brave) meet same problem. 
all source(awsome - repository examples) meet same thing.

I talk about this issues in discord sdk channel

The Cube Spawn project is the most basic project. no user code. This must be done.
I guess there is a problem between unity framewok and SDK.

I hope it will be resolved soon.
Thank you in advance, with respect and encouragement to the developers of Decentraland who always do their best.
 
dcl version           
![image](https://user-images.githubusercontent.com/95423215/177970979-c406f696-17cd-4b31-ac06-3b2e68cd77da.png)

decentraland-ecs version
![image](https://user-images.githubusercontent.com/95423215/177971598-ec55a2ad-f52f-40d0-b66c-c5c2e7e8ee11.png)

**Comment by billygogo** [comment]
this issues fixed

**Comment by leanmendoza** [comment]
thanks for reporting and the update!
