### ISSUE TITLE
Discussion: center of coordinates for UITransform

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#388]
**Alternative A: (Discarded solution)**

Should the center of coordinates be the first clickable pixel of the user area? That is the 25% of the X coordinate. Placing elements behind the chat/minimap would require negative X position.

**Alternative B: (Accepted solution ✅)**

Should the UI canvas be the whole screen, letting the scene decide where to put every element and then expose the information about whether or no the DCL UI Overlay (Map, chat) is visible.

---

Personally, I believe that the alternative B is better for simplicity. Some helpers could be created to expose a "ResizedUiEntity" which respects the "interactable" area of the screen depending on the visibility of the DCL UI

**Comment by Suduck** [comment]
Since we need to specify the width and the height of the root layout, we can have something like 

`width={Screen.width} ` that will take the 75% of the screen and use it in every example, and if the content creator wants to use fullscreen he can do something like 
`width={Screen.fullScreenWidth}`

**Comment by menduz** [comment]
Let's assume the following cases:
1. I want to create a 34px x 34px square at position (13,99)
2. I want to create a 50% x 50% square at the center of the screen

I think that both can be done IF the root canvas has the full width and height of the screen

But, instead, if we need to specify the initial width and height, the second case requires more code, specifically to query the size of the screen.

> Since we need to specify the width and the height of the root layout

Should we instead use the full width and height of the screen for the root layout?

**Comment by menduz** [comment]
After a call with @Suduck and @pbosio, the option of configuring the root canvas to 100% of the screen (UI buffer) by default will be implemented.
