### ISSUE TITLE
add min required versions to cli and ecs

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#39]
In order to ensure maximum compatibility and to not drag compatibility code from three years ago, some checks can be set in place to ensure compatibility versions both from the ECS and from the CLI

### Why is this important?
Changes like `setupProxy.js`, comms, `setupExport.js` and others require specific code from both projects. And without knowledge about it, there may be invisible errors that don't lead to specific call to actions (like updating a version) and that only generates frustration to users of the tools. This change generates a human readable message and fails preventing more errors, with a very clear lead about the compatibility issue and a call to action to fix the issue.

- [ ] add a option to the CLI to skip version checks
  ```ts
  const skipVersionCheck = /* process arg --skip-version-checks */
  ```
- [ ] In `dcl start|build|deploy|export` add a check to throw if (CLI checks minimum ECS version)
  ```ts
  if (!skipVersionCheck && semver.lt(scene.installedEcsVersion, cliPackageJson.minEcsVersion))
    throw new Error([
      'This version of decentraland-cli (dcl) requires an ECS version higher than',
      cliPackageJson.minEcsVersion,
      'the installed version is',
      scene.installedEcsVersion,
      'please go to <link> to know more about the versions and upgrade guides'
    ].join(' '))
  ```
- [ ] In `dcl start|build|deploy|export` add a check to throw if (ECS checks minimum CLI version)
  ```ts
  if (
      !skipVersionCheck 
    && ecsPackageJson.requiredCliVersion 
    && semver.lt(ecsPackageJson.minCliVersion, cliPackageJson.version)
  )
    throw new Error([
      'This version of decentraland-ecs requires a version of the ECS decentraland-cli (dcl) higher than',
      cliPackageJson.minEcsVersion,
      'the installed version is',
      scene.installedEcsVersion,
      'please go to <link> to know more about the versions and upgrade guides'
    ].join(' '))
  ```

**Comment by nearnshaw** [comment]
<3
This should be a big help
