### ISSUE TITLE
Scene at -149, -145 never finishes loading

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#393]
This is happening in production (web and desktop client).

By dumping the scenes load info running `clientDebug.DumpScenesLoadInfo()` in the browser console we can see its ID and state as "WAITING_FOR_INIT_MESSAGES"
```
Dumping state for scene: QmSVnp6BTzVPrBF9PaRwuFYppgpPog1uLqmSAeBbKpKzrU
This scene is not waiting for any components. Its current state is WAITING_FOR_INIT_MESSAGES
```

If you spawn next to it for example [at -149, -144](https://play.decentraland.org/?position=-149%2C-144) you can see that the scene at -149, -145 never finishes loading.

If you spawn directly [at -149, -145](https://play.decentraland.org/?position=-149%2C-145) the rendering is never enabled.

**Comment by menduz** [comment]
![Screen Shot 2022-08-03 at 11 36 40](https://user-images.githubusercontent.com/260114/182635762-eede1ba0-f613-4171-bdda-60d401b81f1c.png)

It seems like the code of the scene is broken.

**Comment by menduz** [comment]
In any case, a timeout of two minutes is enough to finish loading the scene

**Comment by Suduck** [comment]
For me, the renderer is enabled after a while. The scene stays with the green loader. I think that this is the expected behavior. 

Should we close this issue?

**Comment by pravusjif** [comment]
Cool, thanks for debugging guys. In the future we'll probably want to have some kind of "broken scene" state that can be seen in-world to identify cases like this of having a scene that doesn't compile.

I'm closing it.
