### ISSUE TITLE
Discussion: Ordering entities for UI Hierarchy (Flexbox)

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#397]
react-dom relies on DOM tree to render the entities in the order provided by the users.

Unity and Flexbox have a similar approach to layouting as the DOM does. The elements can be ordered using the [VisualElement.Hierarchy](https://docs.unity3d.com/ScriptReference/UIElements.VisualElement.Hierarchy.html).

Whether the new UI uses React or not to declare the final shape, a field to specify the order of the entities (UIElements) needs to be defined in the protocol itself.

Otherwise, the reconciliation algorithm _MAY_ re-use some entities that are already added to a parent breaking the layouting. It is not the same to be the first, n-th or last entity in a flexbox layout.

Alternatives:
* To reduce complexity, a "order" field may be added to the UITransform, then a [sorting method](https://docs.unity3d.com/ScriptReference/UIElements.VisualElement.Hierarchy.Sort.html) can be used in the renderer to always re-order the children of an entity
* Another simple solution is to send two mutually exclusive extra fields: `ChildOf` and `RightOf` to mimic the react fiber internals which uses linked lists to represent the DOM

**Comment by gonpombo8** [comment]
Closed by https://github.com/decentraland/sdk/issues/369
