### ISSUE TITLE
Create publishing pipelines in new repository for decentraland-ecs

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#4]
- [x] Enable Github action to publish decentraland-ecs in https://github.com/decentraland/js-sdk-toolchain (use a different package name to prevent conflicts until we reach stability)
- [x] Add `oddish-action` to publish artifacts in pull requests and merges https://github.com/decentraland/explorer/blob/feat/decouple-kernel-website/.github/workflows/ci.yml#L50-L65  
  In the pull request, it will generate a .tar file that can be istalled directly in node after download

**Comment by leamendoza97** [comment]
This will be finished when the temporary package rename (decentraland-ecs-wip) is removed. Before, it's necessary to test that works properly
