### ISSUE TITLE
Update the CLI globally sometimes its failing in linux 

### ISSUE THREAD

**Issue by Suduck** [decentraland/sdk#423]
Sometimes when you try to install decentraland CLI globally it fails in Linux with the following error: 

```
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/d4rwins/.nvm/versions/node/v16.15.0/lib/node_modules/decentraland
npm ERR! dest /home/d4rwins/.nvm/versions/node/v16.15.0/lib/node_modules/.decentraland-5RljuNhn
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/d4rwins/.nvm/versions/node/v16.15.0/lib/node_modules/decentraland' -> '/home/d4rwins/.nvm/versions/node/v16.15.0/lib/node_modules/.decentraland-5RljuNhn'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/d4rwins/.npm/_logs/2022-08-22T14_44_42_179Z-debug-0.log
```

You need to remove the directory of node modules in order to install the next version of CLI. 

Also, when you try to start the scene with `dcl start` it fails because it doesn't have permission

`-bash: /home/d4rwins/.nvm/versions/node/v16.15.0/bin/dcl: Permission denied`

and you need to give the permissions manually in order to make it work.

Once this happens, it happens always that you want to install a new version of CLI.

I don't know exactly what triggers the issue but it has happened to me @Suduck  with Windows SO with a WSL installed and also to @leanmendoza with a Linux  SO

**Comment by menduz** [comment]
This happens when somebody installs the CLI using `sudo npm install -g decentraland` which is illegal.
