### ISSUE TITLE
Disscusion: UI components to add 

### ISSUE THREAD

**Issue by Suduck** [decentraland/sdk#424]
We are defining the first iteration of UI components that we need to implement for the feature parity with the ECS6. Those components can change until we release the first beta version of ECS7. When we reach the beta version, we can't break the compatibility with old scenes so we need to decide carefully which one implement for the first version.

A good approach will be to implement only the strictly necessary components since we can always add more in the future, but we can't remove components for the future. So this is something to take into account while deciding which one to implement and how to do it.

Feature parity:

- [x] Text or Label
      text
      textColor
      textAlignment ( left, center, right,  for te first version I wouldn't do the justify option)
      font
      fontSize
      lineCount?
      lineSpacing? ( if easy to integrate, it will be in the feature parity, if not it will be delayed)
      autoSize? - Future ( This is a tricky one, we should evaluate this, since it is a powerful tool but also has high performance cost, it should be associated with a minFontSize and maxFontSize in case that we want to implement it)

- [ ] Image
     source
     uvs  -  from 0 to 1 but for the final user, it will choose the pixels 
     filterMode? 

```ts
 const` uiAtlas = Atlas("atlas.png", 512, 512, {
  button1: {x: 0, y: 0, w: 32, h: 32},
  background2: {x: 0, y: 0, w: 32, h: 32}
})



function Atlas<K extends string, V>(tex: string, w: number, h: number, description: Record<K, V>): Record<K, V> {
  return {} as any
}


function ui() {
  return <DivUi transform={..} image={uiAtlas.background2}>
    
  </DivUi> 
} 
```
     
- [ ] InputField or InputText
     same as text or label plus
     InputType? ( To ensure that you can only set numbers or strings...etc)
     Placeholder text
     Placeholder textColor
     Placeholder fontsize?
     InputFieldOnChangeComponent
      value: string 
      submit: bool?
      
     OnFocus(): The player clicked on the UI component and has a cursor on it.
    OnBlur(): The player clicked away and the cursor is gone.
    OnChanged(): The player typed or deleted something to change the string on the component.
    OnTextSubmit(): The player hit the Enter key to submit this string.

     
- [ ]  Resuse OnPointerEvents to receive messages of interaction 

Future:
- [ ] Background color
- [ ] OnHover?
- [ ] AtlasImage? ( This will represent the ability that we have now to use 1 image for several items, should we separate them or implement in the current image)
- [ ] Transparency? ( I will evade this at all cost. transparency has a high cost in rendering, but maybe is still necessary)
- [ ]  Image - preserveAspectRatio?

**Comment by menduz** [comment]
https://github.com/decentraland/adr/issues/125
