### ISSUE TITLE
Remove `Visible`, `IsPointerBlocker` and `WithCollision` from the ECS Components protocol

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/sdk#427]
Currently, the parameters are deprecated like:

```
message PBSphereShape {  
  // @deprecated use MeshCollider instead https://github.com/decentraland/sdk/issues/366
  optional bool with_collisions = 1; // default=true
  // @deprecated use MeshCollider instead https://github.com/decentraland/sdk/issues/366
  optional bool is_pointer_blocker = 2; // default=true
  // @deprecated use HiddenComponent instead https://github.com/decentraland/sdk/issues/353
  optional bool visible = 3; // default=true
}
```
https://github.com/decentraland/protocol/blob/main/ecs/components/SphereShape.proto

So it's necessary to clean those in `js-sdk-toolchain` and `unity-renderer`, breaking the backward compatibility before the beta release of the SDK 7.x.x

**Comment by leanmendoza** [comment]
Sync this Issue with #435 that has some points in common

**Comment by kuruk-mm** [comment]
Fixed on: https://github.com/decentraland/protocol/pull/47
