### ISSUE TITLE
Type issue compiling 6.11.3

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#432]
There are multiple similar type issues when running `dcl build` on any scene built with SDK 6.11.3

Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1537,53): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1544,53): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1550,59): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1555,61): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1832,53): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1833,53): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1839,59): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1840,59): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1841,61): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1855,53): Type 'T' does not satisfy the constraint 'ComponentLike'.
  Error /node_modules/decentraland-ecs/types/dcl/index.d.ts (1857,53): Type 'T' does not satisfy the constraint 'ComponentLike'.

Steps to reproduce:

1) run `dcl init` > create Scene
2) run `dcl build`

This was reported by at least two people in Discord, and I was able to reproduce it myself too
It can be avoided by running `dcl build --skip-build`, but not when deploying to Heroku for example

![Screen Shot 2022-08-29 at 17 20 47](https://user-images.githubusercontent.com/3507907/187291371-72c3510d-507d-48e8-81a8-9dd25903dfc5.png)

**Comment by MineaChhem** [comment]
I got it too and my mate

**Comment by stom66** [comment]
I am also experiencing this issue with version 6.11.4.

To fix it locally, run the following in the file `node_modules\decentraland-ecs\types\dcl\index.d.ts`:

Search for: `<T>(component: ComponentConstructor<T>`
Replace with: `<T extends ComponentLike>(component: ComponentConstructor<T>`.

11 instances will be replaced and this should fix the issue.

**Comment by nearnshaw** [comment]
Issue fixed with this commit:
https://github.com/decentraland/js-sdk-toolchain/pull/233

@MineaChhem @stom66 
Should be working now with `decentraland-ecs@next` 
a new stable version will be released soon
