### ISSUE TITLE
Feature Parity: Component `MESH_COLLIDER`

### ISSUE THREAD

**Issue by pbosio** [decentraland/sdk#435]
related to: https://github.com/decentraland/sdk/issues/366

- [x] Add MeshCollider component
 protocol: https://github.com/decentraland/protocol/pull/34
 js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/238
 renderer: https://github.com/decentraland/unity-renderer/pull/2931
- [x] Enable pointer input for MeshCollider
 renderer: https://github.com/decentraland/unity-renderer/pull/2952
 refactored: https://github.com/decentraland/unity-renderer/pull/2930
- [x] Enable pointer hover visual feedback for MeshCollider
 renderer: https://github.com/decentraland/unity-renderer/pull/3060
- [x] Enable colliders for NFTShape
 protocol: https://github.com/decentraland/protocol/pull/48
 js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/261
 renderer: https://github.com/decentraland/unity-renderer/pull/3066
- [x] Enable colliders for GLTF
protocol: https://github.com/decentraland/protocol/pull/41
renderer: https://github.com/decentraland/unity-renderer/pull/3091
js-sdk: https://github.com/decentraland/js-sdk-toolchain/pull/269
~~- [ ] Enable visibility component for colliders~~
- [x] Remove old primitive mesh components from renderer
- [x] Remove old primitive mesh components from protocol
- [x] Remove old primitive mesh components from js-sdk
- [x] Remove old pointer events components
- [x] MeshCollider wrapper as MeshRenderer ( @leanmendoza  )

**Comment by leanmendoza** [comment]
I assign myself to do the wrapper as MeshRenderer has.
