### ISSUE TITLE
Avatar Modifier Area enum UNRECOGNIZE crashes the Renderer

### ISSUE THREAD

**Issue by Suduck** [decentraland/sdk#436]
If you use the UNRECOGNIZE enum of the AvatarModifierArea and send it to the renderer, it explodes.

I didn't investigate the issue, but I think that when the renderer tries to deserialize the enum it explodes because that enum only exists in the typescript part.

We need to find a way to solve the problem either removing the UNRECOGNIZE part or creating a wrap in case that the UNRECOGNIZE enum is necessary for retrocompatibility

**Comment by leanmendoza** [comment]
UNRECOGNIZE is no longer added to the enums.
