### ISSUE TITLE
Pointer Event UP is not working. The hover text is not appearing and we are not detecting it in the renderer

### ISSUE THREAD

**Issue by Suduck** [decentraland/sdk#439]
If you try to use the following code 

```
    OnPointerUp.create(entity, {
      button: ActionButton.POINTER,
      hoverText: 'Press E to spawn'
    }) 
```

It doesn't work since the hover text doesn't appear. However, if you click on it and maintain it, you will see the hover text.

The problem is that renderer is not detecting the click and it is not sending the PointerUp action

**Comment by nearnshaw** [comment]
This seems fixed. The same scenario behaves properly in the example scene "Basic Interactions"
