### ISSUE TITLE
Analyze if 'SceneId' can be removed from Portable Experience Wearables

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#467]
Ideally we should stop having any kind of **scene id** in the renderer and its kernel-renderer communication, but right now in the renderer, Portable Experience Wearable Scenes need to have a scene id to map them to their corresponding wearable id.

Example of cases in which the PX scene id is used to be mapped to its wearable id [Here](https://github.com/decentraland/unity-renderer/blob/d73b9ba97aca772740e8fd437c914a7101d15770/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Scripts/ExperiencesViewerComponentController.cs#L112) and [Here](https://github.com/decentraland/unity-renderer/blob/d73b9ba97aca772740e8fd437c914a7101d15770/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Scripts/ExperiencesViewerComponentController.cs#L181).

If the renderer could map the portable experience scenes to their wearables in some other way, the last of the scene ids used in there could be replaces by scene numbers like regular scenes.

**Comment by menduz** [comment]
I've reviewed the data flows and sending the sceneId will always be required. And it is mapped 1-1 to the wearable URN, so I think it makes sense to keep it for now.
