### ISSUE TITLE
Pixels are not being honored. Instead the size of the global canvas is being used (small box should be bigger)

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#492]
Pixels are not being honored. Instead the size of the global canvas is being used and it affects the ratio of the UI

![Screen Shot 2022-11-29 at 20 26 24](https://user-images.githubusercontent.com/260114/204670691-c5adc002-46c4-4111-873a-f1becd8c4ef7.png)
![Screen Shot 2022-11-29 at 20 26 40](https://user-images.githubusercontent.com/260114/204670710-43a78d08-9d01-4ca9-9108-9022eb812278.png)

**Comment by pravusjif** [comment]
tackled at https://github.com/decentraland/unity-renderer/pull/3770

**Comment by pravusjif** [comment]
@menduz right now I'm unable to reproduce the issue using the sdk's latest version or even the playground version. I tried resizing the viewport with these 2 cases (the 2nd one is very similar to the one you used for this issue), can you test these 2 cases as well? if there is another condition to reproduce the problem can you share the scene code please?

* [simple case](https://playground.decentraland.org/?code=ZXhwb3J0IGNvbnN0IHVpID0gKCkgPT4gKAogIDxVaUVudGl0eQogICAgdWlUcmFuc2Zvcm09e3sKICAgICAgd2lkdGg6ICIzMDBweCIsCiAgICAgIGhlaWdodDogIjIwMHB4IgogICAgfX0KICAgIHVpQmFja2dyb3VuZD17eyBiYWNrZ3JvdW5kQ29sb3I6IENvbG9yNC5XaGl0ZSgpIH19CiAgLz4KKQoKUmVhY3RFY3NSZW5kZXJlci5zZXRVaVJlbmRlcmVyKHVpKQ%3D%3D&renderer-branch=main)
* [case with child panels](https://playground.decentraland.org/?code=ZXhwb3J0IGNvbnN0IHVpID0gKCkgPT4gKAogIDxVaUVudGl0eQogICAgdWlUcmFuc2Zvcm09e3sKICAgICAgd2lkdGg6IDUwMCwKICAgICAgaGVpZ2h0OiA1MDAsCiAgICAgIHBhZGRpbmc6IHsgdG9wOiAyMCwgcmlnaHQ6IDIwLCBib3R0b206IDIwLCBsZWZ0OiAyMCB9LAogICAgICBmbGV4RGlyZWN0aW9uOiBZR0ZsZXhEaXJlY3Rpb24uWUdGRF9ST1cKICAgIH19CiAgICB1aUJhY2tncm91bmQ9e3sgYmFja2dyb3VuZENvbG9yOiB7cjogMSwgZzogMSwgYjogMSwgYTogMC44fSB9fQogID4KICAgIDxVaUVudGl0eQogICAgICB1aVRyYW5zZm9ybT17ewogICAgICAgIHdpZHRoOiAxMDAsCiAgICAgICAgaGVpZ2h0OiAxMDAKICAgICAgfX0KICAgICAgdWlCYWNrZ3JvdW5kPXt7IGJhY2tncm91bmRDb2xvcjoge3I6IDEsIGc6IDAsIGI6IDEsIGE6IDAuOH0gfX0KICAgIC8%2BCiAgICA8VWlFbnRpdHkKICAgICAgdWlUcmFuc2Zvcm09e3sKICAgICAgICB3aWR0aDogMjYwLAogICAgICAgIGhlaWdodDogMTAwCiAgICAgIH19CiAgICAgIHVpQmFja2dyb3VuZD17eyBiYWNrZ3JvdW5kQ29sb3I6IHtyOiAwLCBnOiAxLCBiOiAxLCBhOiAwLjh9IH19CiAgICAvPgogICAgPFVpRW50aXR5CiAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgd2lkdGg6IDEwMCwKICAgICAgICBoZWlnaHQ6IDEwMAogICAgICB9fQogICAgICB1aUJhY2tncm91bmQ9e3sgYmFja2dyb3VuZENvbG9yOiB7cjogMCwgZzogMCwgYjogMSwgYTogMC44fSB9fQogICAgLz4KICA8L1VpRW50aXR5PgopCgpSZWFjdEVjc1JlbmRlcmVyLnNldFVpUmVuZGVyZXIodWkp&renderer-branch=main)

**Comment by pravusjif** [comment]
In [the current UI fixes PR](https://github.com/decentraland/unity-renderer/pull/3770) I changed the scenes ui settings scale mode from Constant Physical Size to Constant Pixel Size, it makes more sense I think, if we want the ui elements to keep their pixel size regardless of viewport size: https://docs.unity.cn/Manual/UIE-Runtime-Panel-Settings.html

**Comment by menduz** [comment]
I think both playground links are accurate, thanks @pravusjif . Would you add a test over that property to ensure it doesn't change accidentally?
