### ISSUE TITLE
CLI running dcl start affects performance

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#496]
When I leave `dcl start` running in the background in the command line, even once I closed the browser tab, it severely impacts my machine's performance for running other scenes.

This happens both when I use two CLI windows, or when I use the editor + a CLI window. It also happens if I run both scenes with `dcl start --skip-build -w`

Steps to reproduce:

With only CLI:

1) In one command line window run the Hummingbirds scene (SDK7) from Goerli Plaza.  (It runs at 59 FPS)
2) Close it, stop the `dcl start` command.
3) In another command line window run the Beer Dispenser scene (SDK7) from Goerli Plaza (It also runs at 59 FPS)
4) Close the browser tab, but DONT end the `dcl start` command, leave it running
5) Run the Hummingbirds scene again, on your other command line tab. (It now runs between 10 and 20 FPS)
6) End the `dcl start` command for both scenes, then run the Hummingbirds scene again (59 FPS again)

With CLI + Editor:

1) In one command line window run the Hummingbirds scene (SDK7) from Goerli Plaza.  (It runs at 59 FPS)
2) Close it, stop the `dcl start` command.
3) Open the editor on the Beer Dispenser scene (SDK7) from Goerli Plaza. Run it with run preview (It also runs at 59 FPS)
4) Close the tab in VS Code
5) Run the Hummingbirds scene again, on your other command line tab. (It now runs between 10 and 20 FPS)
6) Close the VS Studio window, also end the `dcl start` for the Hummingbirds scene, then run the Hummingbirds scene again (59 FPS again)

For the case of the editor, this is especially a problem because there is no way to stop the running of the server there, other than closing the entire VS Studio window.

If I leave dcl start running in a command line tab, I also notice that my machine drains its battery a lot faster, so I assume it's performing intense work, even if there's no scene running on any browser window. This has been the case since I can remember, it's not a new problem.

**Comment by AN-DCL** [comment]
Nico is building a new implementation of `dcl start`, he will check that it is not affected by this issue.

**Comment by nearnshaw** [comment]
Won't fix, SDK6
