### ISSUE TITLE
OpenNFTDialog is missing

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#511]
The openNFTDialog() function is missing in SDK7. This used to display a UI with an image of an NFT, and additional data like the owner, its price if on sale, and a link to it on OpenSea.

https://docs.decentraland.org/creator/development-guide/display-a-certified-nft/#open-an-nft-ui

**Comment by nearnshaw** [comment]
The openNFTDialog() function is missing in SDK7. This used to display a UI with an image of an NFT, and additional data like the owner, its price if on sale, and a link to it on OpenSea.

https://docs.decentraland.org/creator/development-guide/display-a-certified-nft/#open-an-nft-ui

**Comment by pravusjif** [comment]
This will be solved when tacklling: https://github.com/decentraland/sdk/issues/527
