### ISSUE TITLE
Take player to a DCL world

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#514]
We need to expose a function to take the player to another world, so that a scene can work as a hub to take players from Genesis City to a world. This should be a function that the content creator can chose to trigger in whatever situation makes sense.

Implementing this will also require work from the explorer team, to prompt the player with a confirmation screen with information about where they're being sent. Like with teleporting, the player will have the option to decline.

This feature could perhaps reuse the existing TeleportTo() function (passing a world name instead of coordinates), or could be a separate new function.

**Comment by menduz** [comment]
Will be resolved at #527
