### ISSUE TITLE
Wrapmode mirror_once is redundant

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#516]
When configuring a texture, the wrapMode has options TWM_MIRROR and TWM_MIRROR_ONCE, both look like they produce identical results.

We might want to remove Mirror_once, or make it only has one axis of symmetry

See this example, where two planes have these different modes set, but look identical:

[example](https://playground.decentraland.org/?code=CmNvbnN0IG1lc2hFbnRpdHkgPSBlbmdpbmUuYWRkRW50aXR5KCkKVHJhbnNmb3JtLmNyZWF0ZShtZXNoRW50aXR5LCB7IAogIHBvc2l0aW9uOiBWZWN0b3IzLmNyZWF0ZSg0LCAzLjUsIDQpLApzY2FsZTogVmVjdG9yMy5jcmVhdGUoNCwgNCwgNCkgfSkKCgovLyBtYXRlcmlhbCBzaG91bGQgYmUgcmVwZWF0ZWQgdGlsZWQsIDN4MyBvbiBlYWNoIGZhY2UKTWVzaFJlbmRlcmVyLnNldFBsYW5lKG1lc2hFbnRpdHksIHNldFVWcyg0LCA0KSkKCgoKZnVuY3Rpb24gc2V0VVZzKHJvd3M6IG51bWJlciwgY29sczogbnVtYmVyKSB7CiAgcmV0dXJuIFsKICAgIC8vIE5vcnRoIHNpZGUgb2YgdW5yb3J0YXRlZCBwbGFuZQogICAgMCwgLy9sb3dlci1sZWZ0IGNvcm5lcgogICAgMCwKCiAgICBjb2xzLCAvL2xvd2VyLXJpZ2h0IGNvcm5lcgogICAgMCwKCiAgICBjb2xzLCAvL3VwcGVyLXJpZ2h0IGNvcm5lcgogICAgcm93cywKCiAgICAwLCAvL3VwcGVyIGxlZnQtY29ybmVyCiAgICByb3dzLAoKICAgIC8vIFNvdXRoIHNpZGUgb2YgdW5yb3J0YXRlZCBwbGFuZQogICAgY29scywgLy8gbG93ZXItcmlnaHQgY29ybmVyCiAgICAwLAoKICAgIDAsIC8vIGxvd2VyLWxlZnQgY29ybmVyCiAgICAwLAoKICAgIDAsIC8vIHVwcGVyLWxlZnQgY29ybmVyCiAgICByb3dzLAoKICAgIGNvbHMsIC8vIHVwcGVyLXJpZ2h0IGNvcm5lcgogICAgcm93cywKICBdCn0KCgpNZXNoQ29sbGlkZXIuc2V0UGxhbmUobWVzaEVudGl0eSkKY29uc3QgdGV4dHVyZVNvdXJjZTogR2VuZXNpc1BsYXphQ29udGVudCA9ICdpbWFnZXMvcG9ydHJhaXRzL2JhcnRlbmRlci5wbmcnCk1hdGVyaWFsLnNldFBick1hdGVyaWFsKG1lc2hFbnRpdHksIHsKICB0ZXh0dXJlOiBNYXRlcmlhbC5UZXh0dXJlLkNvbW1vbih7CiAgICBzcmM6IHRleHR1cmVTb3VyY2UsCiAgICB3cmFwTW9kZTogVGV4dHVyZVdyYXBNb2RlLlRXTV9NSVJST1IsCiAgICAvLyBmaWx0ZXJNb2RlOiBGaWx0ZXJNb2RlLkJpbGluZWFyCgogIH0pLAogIGNhc3RTaGFkb3dzOiB0cnVlLCAKICAgcm91Z2huZXNzOiAxLAoKfSkKCgpjb25zdCBtZXNoRW50aXR5MyA9IGVuZ2luZS5hZGRFbnRpdHkoKQpUcmFuc2Zvcm0uY3JlYXRlKG1lc2hFbnRpdHkzLCB7IAogIHBvc2l0aW9uOiBWZWN0b3IzLmNyZWF0ZSg5LCAzLjUsIDQpLApzY2FsZTogVmVjdG9yMy5jcmVhdGUoNCwgNCwgNCkgfSkKCi8vIG1hdGVyaWFsIHNob3VsZCBiZSByZXBlYXRlZCB0aWxlZCwgM3gzIG9uIGVhY2ggZmFjZQpNZXNoUmVuZGVyZXIuc2V0UGxhbmUobWVzaEVudGl0eTMsc2V0VVZzKDQsIDQpKQoKTWF0ZXJpYWwuc2V0UGJyTWF0ZXJpYWwobWVzaEVudGl0eTMsIHsKICB0ZXh0dXJlOiBNYXRlcmlhbC5UZXh0dXJlLkNvbW1vbih7CiAgICBzcmM6IHRleHR1cmVTb3VyY2UsCiAgICB3cmFwTW9kZTogVGV4dHVyZVdyYXBNb2RlLlRXTV9NSVJST1JfT05DRSwKICAgIC8vIGZpbHRlck1vZGU6IEZpbHRlck1vZGUuQmlsaW5lYXIKCiAgfSksCiAgY2FzdFNoYWRvd3M6IHRydWUsCiAgIHJvdWdobmVzczogMSwKfSkKCi8vIGNvbnN0IGdsdGZTb3VyY2U6IEdlbmVzaXNQbGF6YUNvbnRlbnQgPSAnbW9kZWxzL211c2V1bS9vbGRfbG9nby5nbGInCi8vIGNvbnN0IGdsdGZFbnRpdHkgPSBlbmdpbmUuYWRkRW50aXR5KCkKLy8gR2x0ZkNvbnRhaW5lci5jcmVhdGUoZ2x0ZkVudGl0eSwgewovLyAgIHNyYzogZ2x0ZlNvdXJjZQovLyB9KQovLyBUcmFuc2Zvcm0uY3JlYXRlKGdsdGZFbnRpdHksIHsgcG9zaXRpb246IFZlY3RvcjMuY3JlYXRlKDgsIDEsIDgpLAoKLy8gICBzY2FsZTogVmVjdG9yMy5jcmVhdGUoMSwgMSwgMSkgCi8vIH0pCgoKCgo%3D)

See this doc for reference about what each should do:
https://learnopengl.com/Getting-started/Textures

**Comment by pravusjif** [comment]
I confirm that his looks like a problem with WebGL, since using the following test code I get the expected results in Unity Editor but not in the web build.

<img width="1309" alt="Screen Shot 2023-05-19 at 14 10 32" src="https://github.com/decentraland/sdk/assets/1031741/91f313a7-b5d6-41c2-96b2-b6bed14eaa64">

<img width="873" alt="Screen Shot 2023-05-19 at 14 13 23" src="https://github.com/decentraland/sdk/assets/1031741/367047a9-81c5-4305-8c35-5ca420dde511">

I'll be removing the `TWM_MIRROR_ONCE` option since is the one that doesn't work in WebGL.
