### ISSUE TITLE
UiText are treated as elements in UI

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#519]
The labels are being accounted for the layouting affecting the rest of the elements. The expected behavior is that labels (UiText component) inherit the full size of their container, without affecting any other entity size.

- [x] Fix UiText to inherit the same sizing as its parent
- [x] Fix `UiText.textAlign` that seems not to be working

The screenshots show up the expected behavior first and the rendered behavior last. We can clearly observe that the "root" text is affecting the layouting of the other elements. Condensing them into the left.

Expected:
![Screen Shot 2022-12-14 at 16 20 13](https://user-images.githubusercontent.com/260114/207693307-59b29ad4-1f9b-4473-950f-91f8d493be23.png)

Given:
![Screen Shot 2022-12-14 at 16 18 07](https://user-images.githubusercontent.com/260114/207693328-a7b7e3f7-2e05-4521-9b3c-3d6385e98be4.png)

Snippet used for the test:

```tsx

export const uiComponent = () => (
  <UiEntity
    uiTransform={{
      width: 1024,
      height: 768,
    }}
  >
    <UiEntity
      uiTransform={{
        width: '100%',
        height: '100%',
        alignItems: YGAlign.YGA_FLEX_START,
        padding: {bottom: 20, left: 20,right: 20,top: 20}
      }}
      uiText={{value: 'root', fontSize: 20,color: Color4.White(), textAlign: TextAlignMode.TAM_MIDDLE_CENTER}}
      uiBackground={{backgroundColor: Color4.Black()}}
    >
    <UiEntity
      uiTransform={{
        width: 100,
        height: '100%',
      }}
      uiBackground={{backgroundColor: Color4.Red()}}
      uiText={{ value: '1', fontSize: 20, textAlign: TextAlignMode.TAM_MIDDLE_CENTER }}
    />
    <UiEntity
      uiTransform={{
        width: 100,
        height: 100,
        margin: {right: 20, left: 20},
        flexGrow: 1
      }}
      uiBackground={{backgroundColor: Color4.Magenta()}}
      uiText={{ value: '2', fontSize: 20, textAlign: TextAlignMode.TAM_MIDDLE_CENTER }}
    />
    <UiEntity
      uiTransform={{
        width: 100,
        height: '100%',
      }}
      uiBackground={{backgroundColor: Color4.Blue()}}
      uiText={{ value: '3', fontSize: 20, textAlign: TextAlignMode.TAM_MIDDLE_CENTER }}
    />
    </UiEntity>
  </UiEntity>
)

ReactEcsRenderer.setUiRenderer(uiComponent)
```

[YogaLayout link for testing](https://yogalayout.com/playground/?eyJ3aWR0aCI6IjEwMjQiLCJoZWlnaHQiOiI3NjgiLCJtaW5XaWR0aCI6bnVsbCwibWluSGVpZ2h0IjpudWxsLCJtYXhXaWR0aCI6bnVsbCwibWF4SGVpZ2h0IjpudWxsLCJhbGlnbkl0ZW1zIjoxLCJwYWRkaW5nIjp7InRvcCI6IjIwIiwicmlnaHQiOiIyMCIsImJvdHRvbSI6IjIwIiwibGVmdCI6IjIwIn0sInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH0sImNoaWxkcmVuIjpbeyJ3aWR0aCI6MTAwLCJoZWlnaHQiOiIxMDAlIiwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfX0seyJ3aWR0aCI6MTAwLCJoZWlnaHQiOjEwMCwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwibWFyZ2luIjp7InJpZ2h0IjoiMjAiLCJsZWZ0IjoiMjAifSwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfSwiZmxleEdyb3ciOiIxIn0seyJ3aWR0aCI6MTAwLCJoZWlnaHQiOiIxMDAlIiwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwibWFyZ2luIjp7ImJvdHRvbSI6IjAifSwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfX1dfQ==)

**Comment by menduz** [comment]
Related to https://github.com/decentraland/sdk/issues/536

**Comment by pravusjif** [comment]
In the end it was decided to remove the fix for this issue from https://github.com/decentraland/unity-renderer/pull/3770 and will be solved when we Implement the multi-ui-components approach without a visual element parent.

**Comment by pbosio** [comment]
fxed here: https://github.com/decentraland/unity-renderer/pull/3869
