### ISSUE TITLE
`System.NullReferenceException` when removing an AvatarAttach

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#520]
When you attach something through a parent entity, and then remove the entity (an the parent in the previous entity), the scene stopped working, and even the hot-reload breaks with this error:
![image](https://user-images.githubusercontent.com/8042536/207863739-89b0a620-ee68-42a6-83a8-bd4a25c24ef4.png)

Step to reproduce:
1. Go to the [Playground snippet](https://playground.decentraland.org/?code=CgovLyBDdWJlIGZhY3RvcnkKZnVuY3Rpb24gY3JlYXRlQ3ViZSh4OiBudW1iZXIsIHk6IG51bWJlciwgejogbnVtYmVyKTogRW50aXR5IHsKICBjb25zdCBtZXNoRW50aXR5ID0gZW5naW5lLmFkZEVudGl0eSgpCiAgVHJhbnNmb3JtLmNyZWF0ZShtZXNoRW50aXR5LCB7IHBvc2l0aW9uOiB7IHgsIHksIHogfSB9KQogIE1lc2hSZW5kZXJlci5jcmVhdGUobWVzaEVudGl0eSwgeyBtZXNoOiB7ICRjYXNlOiAnYm94JywgYm94OiB7IHV2czogW10gfSB9IH0pCiAgTWVzaENvbGxpZGVyLmNyZWF0ZShtZXNoRW50aXR5LCB7IG1lc2g6IHsgJGNhc2U6ICdib3gnLCBib3g6IHt9IH0gfSkKCiAgcmV0dXJuIG1lc2hFbnRpdHkKfQoKLy8gU3lzdGVtcwpmdW5jdGlvbiBjaXJjdWxhclN5c3RlbShkdDogbnVtYmVyKSB7CiAgY29uc3QgZW50aXRpZXNXaXRoTWVzaFJlbmRlcmVyID0gZW5naW5lLmdldEVudGl0aWVzV2l0aCgKICAgIE1lc2hSZW5kZXJlciwKICAgIFRyYW5zZm9ybQogICkKICBmb3IgKGNvbnN0IFtlbnRpdHksIF9tZXNoUmVuZGVyZXIsIF90cmFuc2Zvcm1dIG9mIGVudGl0aWVzV2l0aE1lc2hSZW5kZXJlcikgewogICAgY29uc3QgbXV0YWJsZVRyYW5zZm9ybSA9IFRyYW5zZm9ybS5nZXRNdXRhYmxlKGVudGl0eSkKCiAgICBtdXRhYmxlVHJhbnNmb3JtLnJvdGF0aW9uID0gUXVhdGVybmlvbi5tdWx0aXBseSgKICAgICAgbXV0YWJsZVRyYW5zZm9ybS5yb3RhdGlvbiwKICAgICAgUXVhdGVybmlvbi5mcm9tQW5nbGVBeGlzKGR0ICogMTAsIFZlY3RvcjMuVXAoKSkKICAgICkKICB9Cn0KCi8vIEluaXQKY29uc3QgaW5pdEVudGl0eSA9IGNyZWF0ZUN1YmUoOCwgMSwgOCkKcG9pbnRlckV2ZW50c1N5c3RlbS5vblBvaW50ZXJEb3duKAogIGluaXRFbnRpdHksCiAgKCkgPT4gewogICAgY3JlYXRlQ3ViZSgxICsgTWF0aC5yYW5kb20oKSAqIDgsIE1hdGgucmFuZG9tKCkgKiA4LCAxICsgTWF0aC5yYW5kb20oKSAqIDgpCiAgfSwKICB7IGJ1dHRvbjogSW5wdXRBY3Rpb24uSUFfUFJJTUFSWSwgaG92ZXJUZXh0OiAnUHJlc3MgRSB0byBzcGF3bicgfQopCgplbmdpbmUuYWRkU3lzdGVtKGNpcmN1bGFyU3lzdGVtKQoKaW1wb3J0IHsgZ2V0VXNlckRhdGEgfSBmcm9tICd%2Bc3lzdGVtL1VzZXJJZGVudGl0eScKbGV0IHVzZXJJZDogdW5kZWZpbmVkIHwgc3RyaW5nID0gdW5kZWZpbmVkCmdldFVzZXJEYXRhKHt9KQogIC50aGVuKChkYXRhKSA9PiAodXNlcklkID0gZGF0YS5kYXRhPy51c2VySWQpKQogIC5jYXRjaChjb25zb2xlLmVycm9yKQoKCmxldCBmbGFnID0gZmFsc2UKZW5naW5lLmFkZFN5c3RlbSgoKSA9PiB7CiAgY29uc3QgY29tbWFuZCA9IGlucHV0U3lzdGVtLmdldElucHV0Q29tbWFuZChJbnB1dEFjdGlvbi5JQV9QUklNQVJZLCBQb2ludGVyRXZlbnRUeXBlLlBFVF9ET1dOKQogIGlmIChjb21tYW5kKSB7CiAgICBpZiAoIWZsYWcgJiYgY29tbWFuZC5oaXQ%2FLmVudGl0eUlkID09PSBpbml0RW50aXR5KSB7CiAgICAgIGNvbnN0IHRyYW5zZm9ybSA9IFRyYW5zZm9ybS5nZXRNdXRhYmxlKGluaXRFbnRpdHkpCiAgICAgIGZsYWcgPSB0cnVlCgogICAgICAvLyBDYWxjdWxhdGVzIHRoZSBjcmF0ZSdzIHBvc2l0aW9uIHJlbGF0aXZlIHRvIHRoZSBjYW1lcmEKICAgICAgdHJhbnNmb3JtLnBvc2l0aW9uID0gVmVjdG9yMy5aZXJvKCkKICAgICAgdHJhbnNmb3JtLnJvdGF0aW9uID0gUXVhdGVybmlvbi5JZGVudGl0eSgpCiAgICAgIHRyYW5zZm9ybS5wb3NpdGlvbi56ICs9IDEuNQoKICAgICAgdHJhbnNmb3JtLnBhcmVudCA9IGVuZ2luZS5hZGRFbnRpdHkoKQogICAgICBBdmF0YXJBdHRhY2guY3JlYXRlT3JSZXBsYWNlKHRyYW5zZm9ybS5wYXJlbnQsIHsKICAgICAgICBhdmF0YXJJZDogdXNlcklkLAogICAgICAgIGFuY2hvclBvaW50SWQ6IEF2YXRhckFuY2hvclBvaW50VHlwZS5BQVBUX0xFRlRfSEFORAogICAgICB9KQogICAgfSBlbHNlIHsKICAgICAgY29uc3QgdHJhbnNmb3JtID0gVHJhbnNmb3JtLmdldE11dGFibGUoaW5pdEVudGl0eSkKICAgICAgZmxhZyA9IGZhbHNlCgogICAgICBjb25zdCBjYW1lcmFUcmFuc2Zvcm0gPSBUcmFuc2Zvcm0uZ2V0KGVuZ2luZS5DYW1lcmFFbnRpdHkpCiAgICAgIGNvbnN0IGZvcndhcmRWZWN0b3IgPSBWZWN0b3IzLnJvdGF0ZShWZWN0b3IzLnNjYWxlKFZlY3RvcjMuRm9yd2FyZCgpLCAxLjUpLCBjYW1lcmFUcmFuc2Zvcm0ucm90YXRpb24pCgogICAgICB0cmFuc2Zvcm0ucG9zaXRpb24gPSBWZWN0b3IzLmFkZChjYW1lcmFUcmFuc2Zvcm0ucG9zaXRpb24sIGZvcndhcmRWZWN0b3IpCiAgICAgIHRyYW5zZm9ybS5wb3NpdGlvbi55ID0gMC41CgogICAgICB0cmFuc2Zvcm0ucm90YXRpb24gPSBRdWF0ZXJuaW9uLmZyb21Mb29rQXQodHJhbnNmb3JtLnBvc2l0aW9uLCBjYW1lcmFUcmFuc2Zvcm0ucG9zaXRpb24pCiAgICAgIHRyYW5zZm9ybS5yb3RhdGlvbi54ID0gMAogICAgICB0cmFuc2Zvcm0ucm90YXRpb24ueiA9IDAKCiAgICAgIGVuZ2luZS5yZW1vdmVFbnRpdHkodHJhbnNmb3JtLnBhcmVudCkKICAgICAgdHJhbnNmb3JtLnBhcmVudCA9IHVuZGVmaW5lZAogICAgfQogIH0KfSk%3D)
2. Press `E` hitting the cube.
3. Press `E` hitting the ground
4. You should see the error in the console.

**Comment by pbosio** [comment]
fix: https://github.com/decentraland/unity-renderer/pull/4037
