### ISSUE TITLE
Entity as unknown type can be tricky and can introduce some typos.

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#521]
The typos can involve all SDK internal functions and external ones.

```ts
function hasEntityTransform(entity: Entity) {
  return Transform.getOrNull(entity) === null
}

console.log(hasEntityTransform(1))
console.log(hasEntityTransform(321))
console.log(hasEntityTransform('21'))
console.log(hasEntityTransform(undefined))
console.log(hasEntityTransform('321'))
console.log(hasEntityTransform(0))
console.log(hasEntityTransform('invalidEntity'))
```

[Here the example in the Playground](https://playground.decentraland.org/?code=CmZ1bmN0aW9uIGhhc0VudGl0eVRyYW5zZm9ybShlbnRpdHk6IEVudGl0eSkgewogIHJldHVybiBUcmFuc2Zvcm0uZ2V0T3JOdWxsKGVudGl0eSkgPT09IG51bGwKfQoKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKDEpKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0oMzIxKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKCcyMScpKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0odW5kZWZpbmVkKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKCczMjEnKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKDApKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0oJ2ludmFsaWRFbnRpdHknKSk%3D)

**Comment by menduz** [comment]
I think this one is closed?

**Comment by leanmendoza** [comment]
Fixed in the @next version

[Playground Example with main branch](https://playground.decentraland.org/?sdk-branch=main&code=CmZ1bmN0aW9uIGhhc0VudGl0eVRyYW5zZm9ybShlbnRpdHk6IEVudGl0eSkgewogIHJldHVybiBUcmFuc2Zvcm0uZ2V0T3JOdWxsKGVudGl0eSkgPT09IG51bGwKfQoKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKDEpKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0oMzIxKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKCcyMScpKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0odW5kZWZpbmVkKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKCczMjEnKSkKY29uc29sZS5sb2coaGFzRW50aXR5VHJhbnNmb3JtKDApKQpjb25zb2xlLmxvZyhoYXNFbnRpdHlUcmFuc2Zvcm0oJ2ludmFsaWRFbnRpdHknKSk%3D)
