### ISSUE TITLE
Realm data fetching update

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#53]
When fetching the player realm data, it follows the old structure of realms + layers

Layers no longer exist, so we should remove that property
Perhaps it makes sense to start including the island now

https://docs.decentraland.org/development-guide/user-data/#get-player-realm-data

**Comment by menduz** [comment]
Sadly we can't remove the "layer" field to not break old scenes. An empty string is passed on to it. We make it `@deprecated and @internal` to prevent it from showing up on newer versions

**Comment by nearnshaw** [comment]
Ok with not removing the "layer" field for backwards compatibility, but let's including the "island" as a new optional field
That info can sometimes be of use

**Comment by pbosio** [comment]
kernel: https://github.com/decentraland/kernel/pull/110
sdk (declaration only): https://github.com/decentraland/js-sdk-toolchain/pull/49
