### ISSUE TITLE
Implement UiCanvasInformation component for the scene root entity

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#534]
Based on [ADR-124](https://github.com/decentraland/adr/pull/157) a new `UiCanvasInformation` should be implemented to be attached from the renderer to the scene's root entity providing certain Ui canvas information to be read by the scene code.

This will allow the scene to react accordingly to specifics of the device pixel ratio.

At the time of writing the information needed is:
```
message UiCanvasInformation {
  // informs the scene about the resolution used for the UI rendering
  float device_pixel_ratio = 1;
  // informs about the width of the canvas
  int32 width = 2;
  // informs about the height of the canvas
  int32 height = 3;
  // informs the sdk about the interactable area. Some implementations may change this area depending on the HUD that is being shown. This value may change at any time by the Renderer to create reactive UIs.
  Rect interactable_area = 4;
}
```

**Comment by menduz** [comment]
duplicated from https://github.com/decentraland/sdk/issues/531
