### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#535]
# Versioning policy

This document describes versioning policy applied to both scripting framework and editor. They could be versioned separately or as a bundle, the decision hasn't been made yet.

The goal of versioning policy is to forge a contract between the SDK team and content creators: which versions of software are supported and how long the support lasts.

## Definitions

* *Version number* -- a unique identifier of publicly available version of software which consists of *major version* number and *minor version* number separated by a dot (for example, 7.11).

* *Version family* -- all versions that have identical major version form a family. We call version A a *successor* of version B if A and B belong to same family and A minor number is higher than B's (for example, 7.11 is a successor of 7.10).

* *Breaking change* -- a change that forces a user to change their code or assets to keep them in functioning state. TODO: compile a list of common breaking changes.

* *Non-breaking change* -- a change that does not require any action by a user, the behavior and properties of user's code and assets are unchanged.

* *Stable version* -- a version that forbids breaking changes in all its successors (which all considered as stable too). Any breaking change must be introduced only through creation of new version family by incrementing major version number. Non-breaking changes are reflected through incrementing minor version number.

* *Unstable version* -- a version that allows breaking changes in its successors. Breaking changes may be introduced by incrementing minor version number.

## How many versions should we offer and support?

We are a small team pursuing big goals and can't afford a burden of supporting many versions for a long time. Our software will evolve quickly, its value proposition will grow steadily, thus hopefully convincing users to follow development closely and to not stick to a certain major version for long.

In every stable version family we should support only the latest minor version. We should avoid proliferation of major versions, sticking to two supported families at worst. 

## How long do we support a stable version family?

Let's assume we start with a stable version 7.1 released publicly. We continue the development of 7.x version family for as long as possible, adding new features and bugfixes while avoiding breaking changes.

```
7.1-stable -> 7.2 -> ... -> 7.15
```

Once further development becomes unbearably hindered or impossible by stability requirement, we create a new version family (in our example, 8.x) that initially could be declared unstable. Starting from this moment, previous family (7.x) should not receive any new features and receive only major bugfixes.

```
7.1-stable -> 7.2 -> ... -> 7.15
                             |
                             |-> 8.0-unstable
```

Once a new version family becomes stable (8.x), a team commits to support (major bugfixes) previous version (7.x) for N (6? case-by-case basis?) months, thus giving creators plenty of time to migrate.

```
7.1-stable -> 7.2 -> ... -> 7.15 -> ... -> 7.21 (major bugfixes)
                             |
                             |-> 8.0-unstable -> ... -> 8.7-stable
```

**Comment by menduz** [comment]
Decentraland tends to a consistent `@next` tag for main branch and `@latest` for tagged versions. It is also the most adopted JS versioning schema. We use the `@next` for unstable as of today, do you think we can adjust this proposal to not change it?

Unstable also may include of course non-breaking changes, extending to half-cooked new features (alpha/beta).

The versioning schema we use for non-stable versions goes like this: `0.0.0-<build_number/date>-commit.<7_hex_commit>` you can preview it running `npm info @dcl/sdk` `@dcl/ecs-math: 2.0.1-20221129185242.commit-40495c1`

**Comment by leanmendoza** [comment]
> Decentraland tends to a consistent `@next` tag for main branch and `@latest` for tagged versions. It is also the most adopted JS versioning schema. We use the `@next` for unstable as of today, do you think we can adjust this proposal to not change it?
> 
> Unstable also may include of course non-breaking changes, extending to half-cooked new features (alpha/beta).
> 
> The versioning schema we use for non-stable versions goes like this: `0.0.0-<build_number/date>-commit.<7_hex_commit>` you can preview it running `npm info @dcl/sdk` `@dcl/ecs-math: 2.0.1-20221129185242.commit-40495c1`

All versions are well-defined by that schema, even the stable and unstable ones.
The version tags as `major.minor.patch` would be a stable release that points to some specific version (with the previous schema)

My understanding of this proposal would change the next:
- With a new **major** version, we can say that it's unstable until the first `major.minor.patch-stable` is tagged. At this moment, the lifetime of the previous major should be determined.
- At the development level: @next always pretends to be unstable, and @latest pretends to be a stable release.

**Comment by AN-DCL** [comment]
> Decentraland tends to a consistent @next tag for main branch and @latest for tagged versions. It is also the most adopted JS versioning schema. We use the @next for unstable as of today, do you think we can adjust this proposal to not change it?

A clarification: this proposal is user-centric, it describes versions visible to users and ignores any internal details. That's why, for example, patch numbers are omitted -- it's likely that content creators simply won't care about a difference between minor version and a patch number. Not sure how non-coding folks (who will hopefully be a majority one day) would benefit from being exposed to JS conventions.

> At the development level: @next always pretends to be unstable.

If @next points to the main branch, then it should be stable (i.e. no breaking changes allowed) most of the time. If we release new stable major version, then development of this version will proceed on the main branch, while previous major version will be "moved" to its own branch.

**Comment by menduz** [comment]
The current workflow is IMO very compatible with that. Versions are tagged manually via git tags in the shape major.minor.patch and that is what people receive as `latest`, are you proposing a `7-stable` [dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag/) also to point to the latest 7.x.y version?


You can watch the released versions here, https://github.com/decentraland/js-sdk-toolchain/releases and that is what the broader audience gets. Not a single of the "in-between" versions that are [tagged here ](https://www.npmjs.com/package/@dcl/sdk?activeTab=versions) ![Screen Shot 2022-12-22 at 13 48 02](https://user-images.githubusercontent.com/260114/209185185-cbd8f495-7820-478a-a47f-c52af02fa209.png)
