### ISSUE TITLE
Preview connected to Metamask

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#537]
Today with the CLI, you can run a scene with `dcl start --web3` to connect to Metamask and try it out with a specific wallet. For certain interactions it's a very useful debug tool.

In the Editor currently you can't do that, the only option is to open the preview in a browser windw, and manually add `&ENABLE_WEB3` to the URL. There should be a friendlier way.

One option could be to include a second button to "Open in browser" that opens in browser + that URL param already added.

**Comment by cazala** [comment]
This has been closed by this PR: https://github.com/decentraland/editor/pull/62
