### ISSUE TITLE
UiInput and UiDropdown visual bugs

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#549]
# `<Input />` visual bugs

- There is a padding cutting the contents of the input field
- The 100x32 size is not being honored, rendering an input (including border) of 90x28
- There is a border, the Input should be positioned at 0x0, it starts on (x,y)=(7,3)

![Screen Shot 2022-12-29 at 11 21 25](https://user-images.githubusercontent.com/260114/209968188-cb845716-b0a5-4a14-9fdb-566d0b85c6c2.png)

```tsx

export const ui = () => (
  <UiEntity
    uiTransform={{
      width: "3000px",
      height: "3000px"
    }}
    uiBackground={{ color: Color4.Black() }}
  >
    <Input uiTransform={{ width: "100px", height: "32px" }} />
  </UiEntity>
)

ReactEcsRenderer.setUiRenderer(ui)
```

# `<Drowdown />` visual bugs

- There is a huge padding in the contents, trying to render "@Empty@" cuts off many letters
- The 100x32 size is not being honored, rendering an input (including border) of 100x34
- There is a border, the Input should be positioned at 0x0, it starts on (x,y)=(9,3)
![Screen Shot 2022-12-29 at 11 32 02](https://user-images.githubusercontent.com/260114/209968533-7c8e3e57-00b1-4a35-9503-0a7faa5dce93.png)

```tsx
export const ui = () => (
  <UiEntity
    uiTransform={{
      width: "3000px",
      height: "3000px"
    }}
    uiBackground={{ color: Color4.Black() }}
  >
    <Dropdown uiTransform={{ width: "100px", height: "32px" }} emptyLabel="@Empty@" />
  </UiEntity> 
)


ReactEcsRenderer.setUiRenderer(ui)
```

**Comment by mikhail-dcl** [comment]
This is the problem with styling that I mentioned in the PR: Unity has its own style sheets and currently I left our of scope what to do with them.
I propose to think of our approach to styles (including substate such as #hovering) in general and in application each component before addressing it straightaway.

**Comment by pravusjif** [comment]
I believe the problem has been solved by the changes of [this PR](https://github.com/decentraland/unity-renderer/pull/4642).

* UiInput
```
export const ui = () => (
    <UiEntity
        uiTransform={{
            width: "3000px",
            height: "3000px",
            position: "49%"
        }}
        uiBackground={{ color: Color4.Black() }}
    >
        <Input 
            uiTransform={{ width: "100px", height: "32px" }}
            uiBackground={{ color: Color4.White() }}
            color={Color4.Black()}
        />
    </UiEntity>
)

ReactEcsRenderer.setUiRenderer(ui)
```

https://user-images.githubusercontent.com/1031741/225994473-4d22d831-bb87-47ed-aa21-ee61fac710b5.mp4

* UiDropdown
```
export const ui = () => (
    <UiEntity
        uiTransform={{
            width: "3000px",
            height: "3000px",
            position: "49%"
        }}
        uiBackground={{ color: Color4.Black() }}
    >
        <Dropdown 
            uiTransform={{ width: "100px", height: "32px" }}
            color={Color4.Yellow()}
            emptyLabel="@Empty@"
        />
    </UiEntity>
)

ReactEcsRenderer.setUiRenderer(ui)
```

https://user-images.githubusercontent.com/1031741/225994506-81816da7-6989-4c2e-a8d7-75d67b4891ff.mp4
