### ISSUE TITLE
Bug: Action keys not being ignored if UiInput is focused

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#552]
When you press the letter `u` insithe a UiInput, then the entire UI is toggled, and the `u` is not added to the input.

Expected behavior: All action keys (WASD, C, U, B) are not triggered while the focus is in an input area.

**Comment by mikhail-dcl** [comment]
It's fixed already

**Comment by menduz** [comment]
@mikhail-dcl thanks!
