### ISSUE TITLE
Hide Component IDs

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#562]
Currently, when creating a custom component you need to assign a unique ID to it. 

Making sure the IDs you assign are unique can be quite a problem, especially if you're importing libraries that create their own custom components. You might not know what IDs those libraries use, and you could even end up combining libraries with incompatible sets of components.

Ideally, creators should be able to create a custom component by just specifying the schema, and the ID number gets assigned behind the scenes, they never even need to find out that there is an ID number at all.

Part of the challenge here is to ensure that component IDs are assigned consistently for any player running the same scene, to ensure that they can send multiplayer sync messages between each other that get correctly interpreted. If the loading of the scene happens with race conditions, there could be scenarios where certain components get compiled in different orders, and therefore with different ids.

**Comment by gonpombo8** [comment]
closed via https://github.com/decentraland/js-sdk-toolchain/pull/384
