### ISSUE TITLE
Friendlier Raycast helper layer

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#571]
Currently, the only way to use raycasts is to create a raycast component and then use a system to listen for RaycastResult components. This is not very friendly, especially as raycast results remain there, and you need to handle manually marking them as done once you've dealt with them.

Here's an example scene that builds upon the current implementation:
https://github.com/decentraland-scenes/sdk7-goerli-plaza/tree/main/bird-field

The proposed implementation would be very similar with how we handle pointer down events with a register callback. With pointer down events we also have a pointerDownResult component, but must users will never need to deal with this. Instead, most users register a callback function that gets executed each time the event occurs. Se [this doc](https://docs.decentraland.org/creator/development-guide/sdk7/register-callback/) for reference.

The proposed solution would then build upon the existing Raycast and RaycastResponse components, but offer a friendlier layer. It could look something like this:

```
rayEventsSystem.onRay(
  entity,
  function (hits) {
    console.log("hit entity at ", hits[0].position)
  },
  {
    origin: Vector3.create(8, 1, 0),
    direction: Vector3.create(0, 0, 1),
    maxDistance: 16,
    queryType: RaycastQueryType.RQT_HIT_FIRST
  }
)
```

The callback function would only be executed once per each `onRay`, independently if the ray hit something or not

**Comment by AN-DCL** [comment]
What is the purpose of `entity` argument?

**Comment by nearnshaw** [comment]
> What is the purpose of `entity` argument?

In the current implementation, the Raycast component needs to be added to an entity. Although it's true that in most cases (or maybe all?) the user won't care what entity it's added to though. Unlike the OnPointerDown event callbacks, here the entity that owns the ray is quite irrelevant. We could study the option of having this function add a new entity behind the scenes.

**Comment by AN-DCL** [comment]
"here the entity that owns the ray is quite irrelevant."

Then a user-friendly wrapper must not expose it to a user.

**Comment by menduz** [comment]
The entities are relevant for raycasts, since the origin point of the ray should be affected by the global position of the entity.

In the following example, we are attaching the raycast origin to the hand of a player, which is affected by a moving platform (elevator).

This behavior is better explained at https://adr.decentraland.org/adr/ADR-148


```ts

const gun = engine.addEntity()
attachEntityToPlayer(playerEntity, gun, AttachPoint.HAND)


rayEventsSystem.onRay(
  gun,
  function (hits) {
    console.log("hit entity at ", hits[0].position)
  },
  {
    origin: Vector3.create(0, 0, 0),
    direction: Vector3.create(0, 0, 1),
    maxDistance: 16,
    queryType: RaycastQueryType.RQT_HIT_FIRST
  }
)
```


The sequence of messages goes like this:


```mermaid
sequenceDiagram
  loop GameLoop
    Scene->>Scene: Run game loop
    Scene->>Renderer: Send updates (entities and raycast)
    Renderer->>Renderer: Process messages
    Renderer->>Renderer: Calculate physics (including elevators & global positions)
    Renderer->>Renderer: Raycasts & Put results in outgoing queue
    Renderer->>Scene: Process raycast result
  end
```

**Comment by nearnshaw** [comment]
So in that example above, the `origin` is not an absolute position in the scene, but rather a relative position to the entity that owns the raycast? And I assume the  same applies to the direction, it's relative to the direction of the entity.  That scenario makes sense and actually in many cases could be easier than dealing with absolute positions and directions in the scene.

If so, then that's a pretty compelling case for the entity to be relevant.

**Comment by menduz** [comment]
I'm not sure it was implemented that way, we may want to add a caveat on the current implementation if we decide to change it. I'd remove the origin point entirely and use the Transform approach, which will inherit the "relative to the scene" position of the root entity.

Enabling a helper like this one: 

```ts
const entityRaycastPool = engine.entityPool()

function simpleRaycast(origin: Vector3, direction: Vector3, maxDistance: number, queryType, callback) {
  const entity = entityRaycastPool.getEntity()

  Transform.set(entity, { position: origin, parent: engine.RootEntity })
  
  rayEventsSystem.onRay(
    entity,
    function (hits) {
      entityRaycastPool.collect(entity)
      callback(hits)
    },
    {
      // DELETED: origin: Vector3.create(0, 0, 0),
      direction: direction,
      maxDistance,
      queryType
    }
  )
}
```

**Comment by AN-DCL** [comment]
Capability to specify ray in local coordinates of another entity is neat. Optional `parentEntity` argument should allow single API method to service both "global" and "local" rays:

```javascript
function raycast(origin: Vector3, direction: Vector3, maxDistance: number, queryType, callback, parentEntity?: Entity = null)
```

That said, there could be an issue with scaling. We should check that the renderer doesn't transform `maxDistance` to local coordinates, otherwise it may inadvertently stretch/contract ray length if any ancestor entity has scaling.

**Comment by pravusjif** [comment]
The raycast protocol has been updated to use the "transform-related" aproach:
* Protocol update: https://github.com/decentraland/protocol/pull/122
* SDK update: https://github.com/decentraland/js-sdk-toolchain/pull/472
* Reference client update: https://github.com/decentraland/unity-renderer/pull/4761


I'm starting to work on a helper similar to the pointer down events system aproach.
