### ISSUE TITLE
Flip Billboard orientation for TextShape

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#576]
When adding a billboard to an entity with TextShape, the default behavior is for the text to appear flipped around.

We would expect to be able to read the text always, but instead it keeps turning to face the opposite direction that it should.

![Image](https://user-images.githubusercontent.com/3507907/214313682-7482e743-9728-454e-9ff4-314589f7eb56.png)

Although one can work around this by applying the billboard to a parent entity and having the text rotated 180 degrees, this is not a friendly solution to content creators.

The default orientation of any entity that has a Billboard component + a TextShape component should be to always keep the text readable.

**Comment by pbosio** [comment]
Note: TextShape is facing direction 0,0,-1 and that should not be changed, so we need no invert the billboard rotation
plus we need to remove initial component rotation: https://github.com/decentraland/unity-renderer/blob/50129111f39ea1d42c33e75af6dbc744a4e178f6/unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/ECSTextShapeComponentHandler.cs#L43

**Comment by pbosio** [comment]
Also take the opportunity to fix this https://github.com/decentraland/sdk/issues/608
