### ISSUE TITLE
CLI can create a new SDK7 project

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#577]
Currently, whenever you create a new project with the CLI or with the Editor UI, you are only offered SDK6 options. To create a new project with SDK7, the only existing alternative is to clone the template repo manually.

This was maybe acceptable for the Alpha, but for the Beta we need something better.

We need the version of the Editor that we release with SDK7 beta to create a new project with SDK7. For this we will need to change the CLI too to link the `dcl init` to this template.

**Comment by menduz** [comment]
![Screenshot 2023-01-24 at 12 04 29](https://user-images.githubusercontent.com/260114/214329993-c32c2f42-9c4f-44d5-a260-70716ad811b8.png)

@nicoecheza
