### ISSUE TITLE
getParcel in SDK7

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#585]
the getParcel function was deprecated in SDK7, together with all of the ParcelIdentity import path it belonged to

We need to expose this function somehow

This function is the only way for the scene to fetch metadata from scene.json. This can be especially useful to libraries, that for example can know the dimensions of the scene or the locations of spawn points.

More details:
https://docs.decentraland.org/creator/development-guide/scene-metadata/#fetch-metadata-from-scene-code

**Comment by gonpombo8** [comment]
closed via https://github.com/decentraland/js-sdk-toolchain/pull/404
