### ISSUE TITLE
Inspector React views 

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#589]
- Entity Tree
- Component inspector
- Asset Catalog
- https://github.com/decentraland/sdk/issues/590

**Comment by cazala** [comment]
I'm closing this issue, the entity tree and asset catalog have already been introduced by https://github.com/decentraland/js-sdk-toolchain/pull/437, the component inspector has it's own issue https://github.com/orgs/decentraland/projects/20/views/21?pane=issue&itemId=22810571 and next features to be added to the entity tree and asset catalog will come as separate issues.
