### ISSUE TITLE
Create manual QA guide

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#596]
Enumerating all steps to ensure creating a project works. Top of my head:

- `npx @dcl/sdk init --dir my-scene` to init a project in the folder `my-scene`
- `cd my-scene` to enter the folder, assert files exist
- `npm start` to initialize the preview
  - assert it installs the dependencies
  - assert it compiles successfully
  - assert it opens the browser

**Comment by nearnshaw** [comment]
To be handled by the QA team
