### ISSUE TITLE
`build-ecs --watch` isn't working

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#598]
By menduz
> Dcl is no-longer compatible with sdk7, it now uses sdk-commands. Will post how to migrate shortly

# Original Issue: `build-ecs` --watch isn't working
Steps to reproduce:
1. Clone https://github.com/decentraland/sdk7-scene-template and `git checkout fix/use-next-sdk`
3. Install dependencies with `npm install` and run `npm run watch`
4. Modify any file and see how the `build-ecs` process is closed

The same happens with `dcl start` which runs a `build-ecs --watch` internally

**Comment by menduz** [comment]
Dcl is no-longer compatible with sdk7, it now uses sdk-commands. Will post how to migrate shortly

**Comment by leanmendoza** [comment]
Ohh, great :D

**Comment by leanmendoza** [comment]
> Dcl is no-longer compatible with sdk7, it now uses sdk-commands. Will post how to migrate shortly

But the `npm run watch` only runs `build-ecs --watch`, there is no DCL involved there

**Comment by menduz** [comment]
```jsonc
// package.json
{
  "scripts": {
    "start": "sdk-commands start",
    "build": "sdk-commands build"
  }
}
```

`dcl start` is now `npm start`
`dcl build` is now `npm run build`
