### ISSUE TITLE
Add full UI to preview

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#6]

**Comment by nearnshaw** [comment]
Not seeing the real UI in preview makes it very hard to know where to add your own scene-level UI, as it might be overwritten by the chat, map, etc.

We need to see all the elements. The chat doesn't need to be functional, I don't need to be able to connect and chat with others, but it should expand to show the full space it occupies.

Also, having access to the UI will make it easy to try the scene out in night mode or with different quality settings, which is a MAJOR missing feature.

It also enables changing player wearables, which in some scenes is a key mechanic.
