### ISSUE TITLE
Scene code runs before having data from engine

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#600]
The scene should wait for the engine to send an initial state before starting to run the scene's code. Without this, a system that queries for the root entity, the player entity or the camera entity will not find these in the first frames of the scene. 

It's possible for creators to work around this by adding a check like in the example below. But without this check, the scene fails. The console reads that component 1 from entity 1 can't be found. Removing this complication would help make code a lot simpler for content creators in some cases.

```ts
const cube = engine.addEntity()

Transform.create(cube, {
  position: Vector3.create(3, 1, 3),
})

MeshRenderer.setBox(cube)

function CubeRotateSystem() {
  // comment out the next line & the scene breaks
  if (!Transform.has(engine.PlayerEntity)) return
  const transform = Transform.getMutable(cube)
  transform.rotation = Transform.get(engine.PlayerEntity).rotation
}

engine.addSystem(CubeRotateSystem)
```

[playground link](https://playground.decentraland.org/?explorer-branch=dev&sdk-branch=main&code=Y29uc3QgY3ViZSA9IGVuZ2luZS5hZGRFbnRpdHkoKQoKVHJhbnNmb3JtLmNyZWF0ZShjdWJlLCB7CiAgcG9zaXRpb246IFZlY3RvcjMuY3JlYXRlKDMsIDEsIDMpLAp9KQoKTWVzaFJlbmRlcmVyLnNldEJveChjdWJlKQoKZnVuY3Rpb24gQ3ViZVJvdGF0ZVN5c3RlbSgpIHsKICAvLyBjb21tZW50IG91dCB0aGUgbmV4dCAmIHRoZSBzY2VuZSBicmVha3MKICBpZiAoIVRyYW5zZm9ybS5oYXMoZW5naW5lLlBsYXllckVudGl0eSkpIHJldHVybgogIGNvbnN0IHRyYW5zZm9ybSA9IFRyYW5zZm9ybS5nZXRNdXRhYmxlKGN1YmUpCiAgdHJhbnNmb3JtLnJvdGF0aW9uID0gVHJhbnNmb3JtLmdldChlbmdpbmUuUGxheWVyRW50aXR5KS5yb3RhdGlvbgp9CgplbmdpbmUuYWRkU3lzdGVtKEN1YmVSb3RhdGVTeXN0ZW0p)

**Comment by menduz** [comment]
The update should come as part of the initial `crdtGetState` call by the `onStart` function
![Screenshot 2023-02-07 at 16 22 22](https://user-images.githubusercontent.com/260114/217344500-127e18e4-aecc-41de-962e-85598a4b0d18.png)

@pbosio

**Comment by pbosio** [comment]
> The update should come as part of the initial `crdtGetState` call by the `onStart` function ![Screenshot 2023-02-07 at 16 22 22](https://user-images.githubusercontent.com/260114/217344500-127e18e4-aecc-41de-962e-85598a4b0d18.png)
> 
> @pbosio

@menduz that is correctly called and components are updated, but scene-runtime does an eval of the scene code before calling `sceneModule.runStart()` https://github.com/decentraland/scene-runtime/blob/main/src/worker-sdk7/index.ts#L91-L105
can we move the `runStart` to be called before the eval? 🤔

**Comment by menduz** [comment]
the eval is what actually enables this function to exist. it _must_ happen before calling it

**Comment by pbosio** [comment]
> the eval is what actually enables this function to exist. it _must_ happen before calling it

yeah I imagine that was the case, but, what is the suggested implementation for this?
making sure that `onStart` is called before anything else of the scene code?

**Comment by menduz** [comment]
This is the code of the engine.update, it processes the update messages received on the onStart and sent to the rendererTransport.onmessage

Can we validate the camera transform is coming through as package in the result of `crdtGetState`? and all the way to [this function](https://github.com/decentraland/unity-renderer/blob/84a20193936c18be81fccfe697d848d1ccf1e7c6/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs#L212)? 

I think we may find where the issue is by only writing tests this time

![Screenshot 2023-02-07 at 16 41 12](https://user-images.githubusercontent.com/260114/217348440-24eebd01-91b6-4f6a-b43a-a8e0fcf403d6.png)

**Comment by menduz** [comment]
> yeah I imagine that was the case, but, what is the suggested implementation for this?
making sure that onStart is called before anything else of the scene code?

It is the first thing that gets called, for sure. Unless you have top level declarations with side effects. But it is not the case of this example.

**Comment by pbosio** [comment]
> > yeah I imagine that was the case, but, what is the suggested implementation for this?
> > making sure that onStart is called before anything else of the scene code?
> 
> It is the first thing that gets called, for sure. Unless you have top level declarations with side effects. But it is not the case of this example.

I will check, but I vaguely recall adding logs to the `onStart` function and to the `index.ts` of my scene and the `index.ts` was called sooner than `onStart`
but I will check again and let you know what I find

**Comment by menduz** [comment]
If you compile this code

```ts
export async function onStart() {
  console.log('XXXX')
}

console.log('OOOO')
```

it will print 

```
OOOO
XXXX
```

And that is expected (and the only viable thing to do).

But then if you run this:

```ts
import * as sdk from '@dcl/sdk'

export async function onUpdate(deltaTime: number) {
  console.log('OnUpdate', deltaTime)
  return await sdk.onUpdate(deltaTime)
}

export async function onStart() {
  console.log('OnStart')
  return await sdk.onStart()
}

sdk.engine.addSystem(function() {
  console.log('SystemRun')
})

console.log('TopLevelDeclaration')
```

You will/should see the logs

```
TopLevelDeclaration
OnStart
OnUpdate 0.0
SystemRun
OnUpdate x.x
SystemRun
OnUpdate x.x
SystemRun
OnUpdate x.x
SystemRun
```

**Comment by pbosio** [comment]
Ok, my bad, I misunderstood the issue.
so we are expecting to work for systems but not expecting to work for top level declaration.
I thought it was already working in systems, but I'll check again.
Are we planning to add a callback for the scene so devs can setup stuff when we know that initial data is set?
I've assumed that that was Nico's major concern

**Comment by nearnshaw** [comment]
oh, very interesting
so in the example above, if I add the following, it would get logged after the onStart & the top level declaration

```ts
executeTask(async () => {
  console.log('ExecuteTask')
})
```

TopLevelDeclaration
OnStart
ExecuteTask
OnUpdate 0.0
SystemRun
...etc

**Comment by menduz** [comment]
It should! Do you confirm?

**Comment by nearnshaw** [comment]
Yep, confirmed, that's working as intended
<img width="633" alt="Screenshot 2023-02-07 at 19 16 38" src="https://user-images.githubusercontent.com/3507907/217379301-e166b893-54be-4bb0-bb99-ebd219deb3ec.png">

**Comment by pbosio** [comment]
Issue was happening on playground but working well on preview
fixed here: https://github.com/decentraland/sdk-playground/pull/25
