### ISSUE TITLE
Elements in UI out of order

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#601]
Issue reported by @wacaine

https://files.slack.com/files-pri/T9EJMTT7Z-F04NLKH576H/screen_shot_2023-02-08_at_12.29.38_pm.png

Looking for help on 2d UI.   I am listing element second but shows 3rd?

![Image](https://user-images.githubusercontent.com/3507907/217613791-81dc686b-4fb8-4290-b803-a34934d0131f.png)

I added a another item.  Order seems arbitrary.
Order is:

Player!
Rocks
SDK
Bob

But output is:

![Image](https://user-images.githubusercontent.com/3507907/217614030-28e66fbb-a573-452a-ba46-2097569a8476.png)

flexDirection:'column',  vs flexDirection:'column-reverse', will flip the order but the order I put in is not being used.  The order I send in is not be used

![Image](https://user-images.githubusercontent.com/3507907/217615360-6dc875f4-4fca-4bf1-b83b-ad2b2722a487.png)

Original conversation:

https://files.slack.com/files-pri/T9EJMTT7Z-F04NS3EL204/screen_shot_2023-02-08_at_12.35.40_pm.png

[playground link](https://playground.decentraland.org/?explorer-branch=dev&sdk-branch=main&code=Ci8vIFZhcmlhYmxlIHRvIHJlZmxlY3QgY3VycmVudCBzdGF0ZSBvZiBtZW51IHZpc2liaWxpdHkKbGV0IF9pc01lbnVWaXNpYmxlOiBib29sZWFuID0gdHJ1ZQoKCmV4cG9ydCBmdW5jdGlvbiBpc01lbnVWaXNpYmxlKCl7CiAgLy9jb25zb2xlLmxvZygiaXNNZW51VmlzaWJsZSgpIiwiRU5UUlkiLF9pc01lbnVWaXNpYmxlKQogIHJldHVybiBfaXNNZW51VmlzaWJsZTsKfQovLyBGdW5jdGlvbiB0byB0b2dnbGUgdGhlIHN0YXRlIG9mIHRoZSBtZW51CmV4cG9ydCBmdW5jdGlvbiB0b2dnbGVNZW51VmlzaWJpbGl0eSgpewogIGNvbnNvbGUubG9nKCJ0b2dnbGVNZW51VmlzaWJpbGl0eSIsIkVOVFJZIixfaXNNZW51VmlzaWJsZSkKICBfaXNNZW51VmlzaWJsZSA9ICFfaXNNZW51VmlzaWJsZQp9CgogCmNvbnN0IHVpQ29tcG9uZW50ID0gKCkgPT4gKAogIDxVaUVudGl0eT4KICAgIDxVaUVudGl0eQogICAgICB1aVRyYW5zZm9ybT17ewogICAgICAgICAgd2lkdGg6IDQwMCwKICAgICAgICAgIGhlaWdodDogMjAwLAogICAgICAgICAgLy9mbGV4RGlyZWN0aW9uOidyb3cnLAogICAgICAgICAgLy9qdXN0aWZ5Q29udGVudDogJ2ZsZXgtc3RhcnQnLAogICAgICAgICAgLy9hbGlnbkl0ZW1zOiAnZmxleC1zdGFydCcsCiAgICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICBtYXJnaW46IHsgdG9wOiAnMjAwcHgnLCBsZWZ0OiAnMjAwcHgnIH0KICAgICAgICB9fQogICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LkJsdWUoKSB9fQogICAgPiAvL3RhYmxlCiAgICAgIDxVaUVudGl0eT4vL3N0YXJ0IHJvdwogICAgICAgIDxVaUVudGl0eQogICAgICAgICAgICB1aVRyYW5zZm9ybT17ewogICAgICAgICAgICAgIHdpZHRoOiAyMDAsCiAgICAgICAgICAgICAgaGVpZ2h0OiA0MCwKCiAgICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgIC8vbWFyZ2luOiB7IHRvcDogJzIwMHB4JywgbGVmdDogJzIwMHB4JyB9CiAgICAgICAgICAgIH19CiAgICAgICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LlJlZCgpIH19CiAgICAgICAgICA%2BCiAgICAgICAgICAgIDxMYWJlbAogICAgICAgICAgICAgIHZhbHVlPSdQbGF5ZXIhJwogICAgICAgICAgICAgIGZvbnRTaXplPXsyNH0KICAgICAgICAgICAgICB1aVRyYW5zZm9ybT17ewogICAgICAgICAgICAgICAgbWFyZ2luOiB7IHRvcDogJzEwcHgnLGxlZnQ6ICc1MCUnIH0KICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LlJlZCgpIH19CiAgICAgICAgICAgIC8%2BCiAgICAgICAgICA8L1VpRW50aXR5PgogICAgICAgICAgPFVpRW50aXR5CiAgICAgICAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgICAgICAgd2lkdGg6IDIwMCwKICAgICAgICAgICAgICBoZWlnaHQ6IDQwLAogICAgICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgICAgICAvL21hcmdpbjogeyB0b3A6ICcyMDBweCcsIGxlZnQ6ICcyMDBweCcgfQogICAgICAgICAgICB9fQogICAgICAgICAgICB1aUJhY2tncm91bmQ9e3sgY29sb3I6IENvbG9yNC5QdXJwbGUoKSB9fQogICAgICAgICAgPgogICAgICAgICAgICA8TGFiZWwKICAgICAgICAgICAgICB2YWx1ZT0nU2NvcmUnCiAgICAgICAgICAgICAgZm9udFNpemU9ezI0fQogICAgICAgICAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgICAgICAgICBtYXJnaW46IHsgdG9wOiAnMTBweCcsbGVmdDogJzUwJScgfQogICAgICAgICAgICAgIH19CiAgICAgICAgICAgICAgLy9jb2xvcjogQ29sb3I0LkJsYWNrKCkgCiAgICAgICAgICAgICAgLy91aUJhY2tncm91bmQ9e3sgY29sb3I6IENvbG9yNC5CbGFjaygpIH19CiAgICAgICAgICAgIC8%2BCiAgICAgICAgICAKICAgICAgICA8L1VpRW50aXR5PgogICAgICA8L1VpRW50aXR5Pi8vZW5kIGxhYmVsIHJvdwoKICAgICAgLy9TVEFSVCBORVhUIFJPVwogICAgICAvL1NUQVJUIE5FWFQgUk9XIC8vU1RBUlQgTkVYVCBST1cgLy9TVEFSVCBORVhUIFJPVwogICAgICAvL1NUQVJUIE5FWFQgUk9XCgogICAgICA8VWlFbnRpdHk%2BLy9zdGFydCAgcm93MQogICAgICAgIDxVaUVudGl0eQogICAgICAgICAgICB1aVRyYW5zZm9ybT17ewogICAgICAgICAgICAgIHdpZHRoOiAyMDAsCiAgICAgICAgICAgICAgaGVpZ2h0OiA0MCwKCiAgICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgIC8vbWFyZ2luOiB7IHRvcDogJzIwMHB4JywgbGVmdDogJzIwMHB4JyB9CiAgICAgICAgICAgIH19CiAgICAgICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LlRlYWwoKSB9fQogICAgICAgICAgPgogICAgICAgICAgICA8TGFiZWwKICAgICAgICAgICAgICB2YWx1ZT0nUm9ja3MnCiAgICAgICAgICAgICAgZm9udFNpemU9ezI0fQogICAgICAgICAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgICAgICAgICBtYXJnaW46IHsgdG9wOiAnMTBweCcsbGVmdDogJzUwJScgfQogICAgICAgICAgICAgIH19CiAgICAgICAgICAgICAgdWlCYWNrZ3JvdW5kPXt7IGNvbG9yOiBDb2xvcjQuUmVkKCkgfX0KICAgICAgICAgICAgLz4KICAgICAgICAgIDwvVWlFbnRpdHk%2BCiAgICAgICAgICA8VWlFbnRpdHkKICAgICAgICAgICAgdWlUcmFuc2Zvcm09e3sKICAgICAgICAgICAgICB3aWR0aDogMjAwLAogICAgICAgICAgICAgIGhlaWdodDogNDAsCiAgICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgIC8vbWFyZ2luOiB7IHRvcDogJzIwMHB4JywgbGVmdDogJzIwMHB4JyB9CiAgICAgICAgICAgIH19CiAgICAgICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LkdyYXkoKSB9fQogICAgICAgICAgPgogICAgICAgICAgICA8TGFiZWwKICAgICAgICAgICAgICB2YWx1ZT0nMicKICAgICAgICAgICAgICBmb250U2l6ZT17MjR9CiAgICAgICAgICAgICAgdWlUcmFuc2Zvcm09e3sKICAgICAgICAgICAgICAgIG1hcmdpbjogeyB0b3A6ICcxMHB4JyxsZWZ0OiAnNTAlJyB9CiAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICAvL2NvbG9yOiBDb2xvcjQuQmxhY2soKSAKICAgICAgICAgICAgICAvL3VpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LkJsYWNrKCkgfX0KICAgICAgICAgICAgLz4KICAgICAgICAgIAogICAgICAgIDwvVWlFbnRpdHk%2BCiAgICAgIDwvVWlFbnRpdHk%2BLy9lbmQgICByb3cxCgogICAgICAvL1NUQVJUIE5FWFQgUk9XCiAgICAgIC8vU1RBUlQgTkVYVCBST1cgLy9TVEFSVCBORVhUIFJPVyAvL1NUQVJUIE5FWFQgUk9XCiAgICAgIC8vU1RBUlQgTkVYVCBST1cKCiAgICAgIDxVaUVudGl0eT4vL3N0YXJ0ICByb3cyCiAgICAgICAgPFVpRW50aXR5CiAgICAgICAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgICAgICAgd2lkdGg6IDIwMCwKICAgICAgICAgICAgICBoZWlnaHQ6IDQwLAoKICAgICAgICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICAgICAgLy9tYXJnaW46IHsgdG9wOiAnMjAwcHgnLCBsZWZ0OiAnMjAwcHgnIH0KICAgICAgICAgICAgfX0KICAgICAgICAgICAgdWlCYWNrZ3JvdW5kPXt7IGNvbG9yOiBDb2xvcjQuVGVhbCgpIH19CiAgICAgICAgICA%2BCiAgICAgICAgICAgIDxMYWJlbAogICAgICAgICAgICAgIHZhbHVlPSdTREsnCiAgICAgICAgICAgICAgZm9udFNpemU9ezI0fQogICAgICAgICAgICAgIHVpVHJhbnNmb3JtPXt7CiAgICAgICAgICAgICAgICBtYXJnaW46IHsgdG9wOiAnMTBweCcsbGVmdDogJzUwJScgfQogICAgICAgICAgICAgIH19CiAgICAgICAgICAgICAgdWlCYWNrZ3JvdW5kPXt7IGNvbG9yOiBDb2xvcjQuUmVkKCkgfX0KICAgICAgICAgICAgLz4KICAgICAgICAgIDwvVWlFbnRpdHk%2BCiAgICAgICAgICA8VWlFbnRpdHkKICAgICAgICAgICAgdWlUcmFuc2Zvcm09e3sKICAgICAgICAgICAgICB3aWR0aDogMjAwLAogICAgICAgICAgICAgIGhlaWdodDogNDAsCiAgICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgIC8vbWFyZ2luOiB7IHRvcDogJzIwMHB4JywgbGVmdDogJzIwMHB4JyB9CiAgICAgICAgICAgIH19CiAgICAgICAgICAgIHVpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LkdyYXkoKSB9fQogICAgICAgICAgPgogICAgICAgICAgICA8TGFiZWwKICAgICAgICAgICAgICB2YWx1ZT0nMCcKICAgICAgICAgICAgICBmb250U2l6ZT17MjR9CiAgICAgICAgICAgICAgdWlUcmFuc2Zvcm09e3sKICAgICAgICAgICAgICAgIG1hcmdpbjogeyB0b3A6ICcxMHB4JyxsZWZ0OiAnNTAlJyB9CiAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICAvL2NvbG9yOiBDb2xvcjQuQmxhY2soKSAKICAgICAgICAgICAgICAvL3VpQmFja2dyb3VuZD17eyBjb2xvcjogQ29sb3I0LkJsYWNrKCkgfX0KICAgICAgICAgICAgLz4KICAgICAgICAgIAogICAgICAgIDwvVWlFbnRpdHk%2BCiAgICAgIDwvVWlFbnRpdHk%2BLy9lbmQgICByb3cyCiAgICAgIAogICAgPC9VaUVudGl0eT4vL2VuZCB0YWJsZQogIDwvVWlFbnRpdHk%2BLy93aG9sZSBjYW52YXMKKQoKZnVuY3Rpb24gZ2V0UGxheWVyUG9zaXRpb24oKSB7CiAgY29uc3QgcGxheWVyUG9zaXRpb24gPSBUcmFuc2Zvcm0uZ2V0T3JOdWxsKGVuZ2luZS5QbGF5ZXJFbnRpdHkpCiAgaWYgKCFwbGF5ZXJQb3NpdGlvbikgcmV0dXJuICcgbm8gZGF0YSB5ZXQnCiAgY29uc3QgeyB4LCB5LCB6IH0gPSBwbGF5ZXJQb3NpdGlvbi5wb3NpdGlvbgogIHJldHVybiBge1g6ICR7eC50b0ZpeGVkKDIpfSwgWTogJHt5LnRvRml4ZWQoMil9LCB6OiAke3oudG9GaXhlZCgyKX0gfWAKfQoKCgpleHBvcnQgZnVuY3Rpb24gc2V0dXBVaSgpIHsKIFJlYWN0RWNzUmVuZGVyZXIuc2V0VWlSZW5kZXJlcih1aUNvbXBvbmVudCkKIC8vUmVhY3RFY3NSZW5kZXJlci5zZXRVaVJlbmRlcmVyKHVpQ29tcDIpCn0KCnNldHVwVWkoKQoKLy8vLy8KCgoKLy8vLy8KCg%3D%3D)

**Comment by pbosio** [comment]
@wacaine @nearnshaw 
this issue is the result of some comments that are not actually comments.
for example:
`<UiEntity>//start row`
"start row" is not being treated as a comment here, you might even notice vscode not painting it the same color a comments
```
<UiEntity>
//start row
```
or
```
//start row
<UiEntity>
```
would be ok (in different lines)
once those "not-comments" are removed, UI is sorted as desired
