### ISSUE TITLE
enable importing json files

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#602]
Allow importing json files into a .ts file from a Decentraland projects

to enable `require('./package.json')` and `import { version } from './package.json`

This should allow creators to use a few 3rd party libraries that don't work today because of this barrier

For example, this error happens when attempting to import the gRPC library:

![Image](https://user-images.githubusercontent.com/3507907/217631632-69052a1b-ed87-46dc-a125-234567663786.png)

**Comment by menduz** [comment]
Should be fixed by esbuild
