### ISSUE TITLE
Support videos from folder

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#605]
The VideoTexture is only able to play videos from streamed URLs. In SDK7 it's not recognizing the path when pointing to a video file stored in the scene itself.

https://github.com/decentraland/unity-renderer/blob/dev/unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerHandler.cs#L50

Bence ran into this issue trying this:

![Image](https://user-images.githubusercontent.com/3507907/218536559-90aab863-47d3-4d0f-8c80-3c0325171c9f.png)

![Image](https://user-images.githubusercontent.com/3507907/218536608-a9ce8416-7644-46cf-8c03-47b2abb74ca9.png)

**Comment by pbosio** [comment]
should be fixed with this PR https://github.com/decentraland/unity-renderer/pull/4401

**Comment by pbosio** [comment]
fixed here: https://github.com/decentraland/unity-renderer/pull/4401
