### ISSUE TITLE
Pointer event collisions ignore GLTF

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#628]
It seems like in some models, the rays pointer events are now not able to recognize the colliders

The zombies in the zombie shooter scenes ( [link](https://github.com/decentraland-scenes/sdk7-goerli-plaza/tree/main/Zombie-shooter) ) are not clickable. As a workaround I had to explicitly add a MeshCollider to the entities, with that it works. But it shouldn't be necessary, because the zombie 3D model does have a collider, and stops we from walking through it.

Viewing the model in Babylon Sandbox:
![Screenshot 2023-03-06 at 15 44 39](https://user-images.githubusercontent.com/3507907/223202801-165e5179-5767-422d-8a0f-ff665a3c2324.png)

To try this issue, 
1) open the zombie-shooter scene
2) Try playing it, notice you can shoot zombies dead
3) open zombie.ts file and comment out line 31, that adds a MeshCollider to the zombies
4) Try playing it again, you'll see there's no action when clicking and no hover hint

**Comment by pbosio** [comment]
duplicate: https://github.com/decentraland/sdk/issues/652
