### ISSUE TITLE
Deprecate Base64 asset loading

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#64]
Migrated to https://github.com/decentraland/explorer-technical-backlog/issues/24

Create components in SDK and Unity:
- [x] `AvatarTexture(address: string)` which texture from profile is this component using. It will use the current content server from the active realm. That is needed because profiles are first deployed in the content server of the users and propagation of these deployments may take time leading to race conditions in which the images are not yet deployed/synchronized
- [x] Create an allow list of `textureBaseUrls: Array<BaseUrl>` that can be used inside the Renderer to enable https://github.com/decentraland/sdk/issues/165
  ```ts
  new Texture(url: string) requiring textureBaseUrls.some(_ => url.startsWith(_))
  ```

**Comment by menduz** [comment]
@nearnshaw reopening, 24 seems to be `Click events outside scene raise errors`

**Comment by menduz** [comment]
Oh, this other 24 https://github.com/decentraland/explorer-technical-backlog/issues/24

**Comment by bikevit2008** [comment]
Why do u want delete Base64? Now i use base64 png for send by websockets between server and client(decentraland)

**Comment by pbosio** [comment]
added allow list and permission: https://github.com/decentraland/unity-renderer/pull/4401
