### ISSUE TITLE
Prevent moving objects outside of scene boundaries

### ISSUE THREAD

**Issue by cazala** [decentraland/sdk#640]
Currently gizmos allow the user to move items anywhere without taking into account any scene boundaries

**Comment by nearnshaw** [comment]
Note: moving entities below the ground is not necessarily all bad, we shouldn't prevent it
EG: You might want to add a UFO and have it partially buried underground so that it looks like it crash-landed

**Comment by cazala** [comment]
@nearnshaw gotcha, removed the part about moving below the ground 👍
