### ISSUE TITLE
Add ability to add or remove components from the `EntityInspector`

### ISSUE THREAD

**Issue by cazala** [decentraland/sdk#641]
The `EntityInspector` should allow the user to remove components and to add new ones (only from the supported core components, no custom components yet).

**Comment by AN-DCL** [comment]
See proposed interactions here: https://www.notion.so/decentraland/Development-roadmap-d0d466934a194a8a92770be84759d559?pvs=4#d5d50582c75e4ea39d817d7c3ed84118
