### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#653]
When trying to run the [Video Streaming example scene](https://github.com/decentraland-scenes/sdk7-goerli-plaza/tree/main/video-streaming) from Goerli plaza, the video never starts playing

This happens in 7.1.1
(with 7.1.0 the video texture doesn't load at all and looks gray instead of black, because of another fixed issue)

On console I see this, every time I try to start the video player
`VIDEO PLAYER: fatal network error encountered, try to recover`

<img width="662" alt="Screenshot 2023-03-14 at 18 24 51" src="https://user-images.githubusercontent.com/3507907/225140308-b3228bd5-803b-425d-83e4-6c8484b3aeb6.png">

The video from Vimeo seems to work well. If I paste the URL directly in the browser, I'm able to download the video file:

https://player.vimeo.com/external/552481870.m3u8?s=c312c8533f97e808fccc92b0510b085c8122a875

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-renderer/pull/4691

**Comment by pravusjif** [comment]
So actually video streaming playback was working fine, the scene was just missing the needed `allowedMediaHostnames` property in the `scene.json`, I just corrected that [with this commit](https://github.com/decentraland-scenes/sdk7-goerli-plaza/commit/281dc4c5c1e33455e3d479670984cbc2ae37ae5d).

I'll try to tackle another problem I saw while testing: the video doesn't start until at least 1 hot reload has taken place
