### ISSUE TITLE
Smart wearable disabling on SDK7

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#676]
On SDK6 we have an example that blocks smart wearables:
https://github.com/decentraland-scenes/block-portable-experiences

It uses a trigger area  and the `getPortableExperiencesLoaded()` function, then it disables parts of the scene's mechanics if any are present.
<s>This is currently not working and needs fixing : https://github.com/decentraland/sdk/issues/570</s>

This kind of mechanic is needed in cases where a smart wearable might give players an unfair advantage in a game. We already have recurring complaints about this not working.
For SDK6, fixing this example is good enough.

For SDK7 we don't have an equivalent, there is no `getPortableExperiencesLoaded()` function.
There are two options, we should pick whichever is the easiest to implement:

1) We can replicate what we have on SDK6, providing a similar function
2) Add a property on the scene.json to turn off portable experiences in the whole scene

If we go with option 2, we can pursue option 1 in the future. But option 2 should be enough to remove friction between scene creators and portable experiences.

**Comment by nearnshaw** [comment]
yeah that's a great question
I think if we can narrow it down to smart wearables that would be the ideal. 

It would also be good to let creators include an allow-list of allowed portable experiences that shouldn't be blocked.
If we go with option 1 (just detect portable experiences) that can be handled by the code in the example scene. If we go with option 2, we would need an extra field on the scene.json for that list. 
In either case, it's not an ideal solution because for events like fashion week or indeed if quests get done w a portable experience, scene creators will likely not even know that it exists and that they should add these to the list.

So if we can easily narrow this down to only portable experiences from wearables, that would certainly be a lot more useful.

**Comment by pbosio** [comment]
> yeah that's a great question I think if we can narrow it down to smart wearables that would be the ideal.
> 
> It would also be good to let creators include an allow-list of allowed portable experiences that shouldn't be blocked. If we go with option 1 (just detect portable experiences) that can be handled by the code in the example scene. If we go with option 2, we would need an extra field on the scene.json for that list. In either case, it's not an ideal solution because for events like fashion week or indeed if quests get done w a portable experience, scene creators will likely not even know that it exists and that they should add these to the list of allowed PX.
> 
> So if we can easily narrow this down to only portable experiences from wearables, that would certainly cover all the scope we want and would have less collateral damage.

Yeah, agree there is no ideal solution
It's not hard to create a PX and load the explorer with it, without needing any smart wearable.
Maybe we could use scene.json `featureToggles` property to disable PX and we disable all PX (smart wearable or not) except for those set in the feature flag that we use for loading PX like the one for mvfw?

**Comment by nearnshaw** [comment]
Using the `featureToggles` sounds like the perfect solution, it was put there to be expanded with things like this :)

>except for those set in the feature flag that we use for loading PX like the one for mvfw
If we can access that, it sounds ideal

>maybe we can also add some kind of list of "allowed PX" in the scene.json for the scenario where creator wants to disable PX to be able to load one of their own
Yes, it's also a great use case in case the creator wants certain PX to work, but wants to control which ones
