### ISSUE TITLE
Rotation issues

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#692]
Rotate any axe from babylon and then the inspector would transform that quaternion into a euler, and back again with some axes changed.

https://user-images.githubusercontent.com/16782417/230160944-5ce5d74f-d7e1-4d4a-ac58-07eee9e11880.mov

Babylon>Datalayer: PUT_COMPONENT e=0x201 c=core::Transform t=2 data={"rotation":{"x":-0.521874189376831,"y":0,"z":0,"w":0.8530224561691284}}
DataLayer>Inspector: PUT_COMPONENT e=0x201 c=core::Transform t=2 data={"rotation":{"x":`-0.521874189376831`,"y":0,"z":0,"w":0.8530224561691284}}
// Here inspector updates the rotation values 
Inspector>Datalayer: PUT_COMPONENT e=0x201 c=core::Transform t=3 data={"rotation":{"x":`0.521874189376831`,"y":0,"z":0,"w":-0.8530224561691284}}

**Comment by AN-DCL** [comment]
> {"x":-0.521874189376831,"y":0,"z":0,"w":0.8530224561691284}}
> {"x":0.521874189376831,"y":0,"z":0,"w":-0.8530224561691284}}

These two describe same rotation in two different ways: rotation by `N` radians around axis `A` is equivalent to rotation by `2 * pi - N` radians around axis `-A`.
