### ISSUE TITLE
Preview & deploy a scene composite

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#699]
Define a mechanism for gluing together user code and scene composite's definition.

# Preview: 
- [x] Bundle all the composite at build-time. https://github.com/decentraland/js-sdk-toolchain/pull/549
- [x] Instance `main.composite` at `onStart` https://github.com/decentraland/js-sdk-toolchain/pull/549
- [x] Having hot-reload and sync composite between Inspector and Preview https://github.com/decentraland/js-sdk-toolchain/pull/554
- [ ] Make the composite to instance configurable

# Deploy:
- [x] Fix deploy in Editor https://github.com/decentraland/editor-sdk7/pull/28
- [x] Generate `main.crdt` on the fly while editing the scene https://github.com/decentraland/js-sdk-toolchain/pull/554
- [ ] Remove `main.crdt` on the fly and generate `main.crdt` at deploy-time: it consists of a snapshot after `onStart` when the api `EngineApi.crdtGetState` returns `hasEntities=false`
- [x] Write `scene.json` with parcels configured inside the composite https://github.com/decentraland/js-sdk-toolchain/pull/610

**Comment by nicoecheza** [comment]
I think we can close this one. The remaining points where extracted to their own issue already (#812 & #813)

@AN-DCL
