### ISSUE TITLE
sdk6: onPointerLockedStateChange not working correctly

### ISSUE THREAD

**Issue by pbosio** [decentraland/sdk#704]
when unlocking pointer (ESC) and locking it again quickly chrome throws an exception, pointer lock state is not reported to the scene but the renderer don't care about the exception, so there is a mismatch on what the scene received and the renderer's pointer lock state.
https://github.com/decentraland/unity-renderer/blob/e311812ec266f06e7d8bd76fefb1b44ad7496121/browser-interface/packages/unity-interface/dcl.ts#L211-L224
also, when working, event is triggered on every click.
probably the best approach to avoid having a mismatch on pointer lock state is that the renderer report the lock state instead of the browser

Do not fix the "event is triggered on every click." until you fix observer getting notified each time.   If you fix the "event is triggered on every click" but not the main issue the workaround wont work

https://decentralandteam.slack.com/files/U0368CBHSDS/F052MMD13C5/screen_recording_2023-04-11_at_12.31.39_pm.mov

**Comment by pravusjif** [comment]
for SDK7 there's also a problem with that, the pointer locked value is always undefined in that case

**Comment by nearnshaw** [comment]
won't fix (SDK6)
