### ISSUE TITLE
View all bounding boxes in preview

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#74]
In preview mode, it would be great to toggle all bounding boxes of all entities in the scene on and off, showing them as wireframes or something subtle.

In older versions of the SDK (with Babylon), we had this and it was a huge help.
It used to work with pressing B
We need to see if we don't add B to the list of buttons to interact with.

Nice to have:
It would be ideal to have some kind of UI element to click to toggle this on/off
A key on the keyboard is hard to find and easy to forget.

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1784
kernel: https://github.com/decentraland/kernel/pull/172
