### ISSUE TITLE
change `NFTShape` component to use urn

### ISSUE THREAD

**Issue by pbosio** [decentraland/sdk#745]
for sdk6 we used the following format for the nft `ethereum://contract_address/token_id`
that doesn't give as much room to scale, for example we might want to support wearables, emotes, etc urns
so the proposed change should be able to support both urn for wearables, etc and also support directly pointing to a nft token, for that last scenario we can use the following format:
`urn:decentraland:<CHAIN>:<CONTRACT_STANDARD>:<CONTRACT_ADDRESS>:<TOKEN_ID>` i.e: `urn:decentraland:ethereum:erc721:0x00...000:123`

- [x] change component property name from [protocol](https://github.com/decentraland/protocol/blob/main/proto/decentraland/sdk/components/nft_shape.proto#L18)
- [x] use [this urn parsing logic](https://github.com/decentraland/unity-renderer/blob/dev/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/RestrictedActionsServiceImpl.cs#L91) for the new implementation
- [x] implement logic on the renderer to add support for this
- [ ] ~add support for matic assets~ (Opensea API doesn't support fetching non-ethereum nfts info yet)

**Comment by pravusjif** [comment]
Handled at 
* https://github.com/decentraland/protocol/pull/146
* https://github.com/decentraland/js-sdk-toolchain/pull/575
* https://github.com/decentraland/unity-renderer/pull/5154

**Comment by pravusjif** [comment]
@nearnshaw the documentation will need to change after this issue related PRs are merged and published.

new way
```
const nftEntity = engine.addEntity()
Transform.create(nftEntity, {
  position: Vector3.create(4, 1, 8),
  scale: Vector3.create(3, 3, 3)
})
NftShape.create(nftEntity, {
  urn: 'urn:ethereum:erc721:0x06012c8cf97bead5deae237070f9587f8e7a266d:558536'
})
```

Also, I don't know if its worht mentioning it in the [related docs](https://docs.decentraland.org/creator/development-guide/sdk7/display-a-certified-nft/) but from what I see in the code and what I tested, only ethereum L1 NFTs are supported, even for SDK6.

**Comment by pravusjif** [comment]
* Supporting decentraland wearable/emote NFTs with raw urns will be tackled in another issue post-beta phase
* Tried to implement `matic` nfts fetching support but Opensea API doesn't support fetching nft info from non-ethereum chains yet
