### ISSUE TITLE
fix `crdtSendToRenderer` from `SceneControllerService`

### ISSUE THREAD

**Issue by pbosio** [decentraland/sdk#747]
The very first time `crdtSendToRenderer` is called, it must wait until all `GltfContainer` components for that scene are loaded, like (for reference) `if(scene.currentTick == 0) yield WaitFor(allGltfLoaded)`
dependency on https://github.com/decentraland/sdk/issues/736
dependency on https://github.com/decentraland/sdk/issues/746

Implementation can be tested with [bird-field scene](https://github.com/decentraland/sdk7-goerli-plaza/blob/main/bird-field/src/index.ts)

**Comment by pravusjif** [comment]
The `tick_number` property also has to be populated for
* `RaycastResult` (probably in `ECSRaycastSystem` when doing the component APPEND)
* `PointerEventsResult` (probably in `ECSInputSenderSystem` when doing the component APPEND)
* `VideoEvent` (probably in `ECSVideoPlayerSystem` whe ndoing the component APPEND)
