### ISSUE TITLE
Inspector project setup

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#749]
A user should be able to setup an inspector project.

1. After clicking on "Create project" button in the extension's tab, a user should be given an option to create either "classical" project, or "inspector" project.
2. User should be prompted to provide a name for the project.
3. A TypeScript file which contains an entry point of scene's TS program should be created.
4. An asset package with name set by user at step 2 should be created.

**Comment by menduz** [comment]
How project types differ?
