### ISSUE TITLE
Remove Decentraland Library step from Editor

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#759]
When adding a dependency via the Decentraland Editor SDK7, you're asked if "is this a Decentraland library"
the distinction made sense on SDK6 and is still needed there, but it's not needed on SDK7. We should not install libraries as bundle dependencies anymore

We should remove that step from the process, as it can cause confusion

**Comment by cazala** [comment]
Closed by https://github.com/decentraland/editor-sdk7/pull/72
