### ISSUE TITLE
Add "debug tools" button toggle in preview mode

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#76]
We can add the following debug options to the preview UI, without much effort

- the debug pannel (currently toggled with P)
- the stats data in the corner w FPS (currently always there in the corner, can't be turend off)

and these don't exist yet, but would be great to also control via UI

- view all colliders  (https://app.zenhub.com/workspaces/sdk-60febfe80dcd78000f01aca0/issues/decentraland/sdk/73)
- view all bounding boxes (https://app.zenhub.com/workspaces/sdk-60febfe80dcd78000f01aca0/issues/decentraland/sdk/74)

We could either include them on the three-dots menu on the bottom-right corner (with night-mode, etc)
Or we could add a tab to the settings

**Comment by RominaMarchetti** [comment]
https://www.figma.com/file/HvW1lICE214xtY3pex5R5P/DebugTools?node-id=0%

This design includes adding a new call to action near the social bar. After clicking it it shows the options to toggle on off.
The information inside the panels is distributed differently now and all the UI was moved to the left side of the screen which belongs to the safe zone for Decentraland UI.

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1845
kernel: https://github.com/decentraland/kernel/pull/183
