### ISSUE TITLE
Support externalAction observable

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#777]
create the externalAction observable and add it to our Observables list.
```ts
// packages/@dcl/sdk/src/observables.ts
const onExternalAction = new Observable<IEvents['externalAction']>(() => subscribe({ eventId: 'externalAction' }))

case 'externalAction': {
          onExternalAction.notifyObservers(data as IEvents['externalAction'])
          break
        }
```

**Comment by menduz** [comment]
what is an external action?

**Comment by pbosio** [comment]
isn't that the "hack" we used to use for builder and it isn't used for anything else?
I think that event is also emit when unity starts in tutorial mode, but wasn't that tutorial going to be replaced by a tutorial deployed in worlds?

**Comment by menduz** [comment]
it already was replaced. I think we are safe to not include this hack on SDK7
