### ISSUE TITLE
NFTShape: Add support for matic wearables/emotes

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#782]
Currently NFTShape fetches the corresponding NFT asset info (image, etc.) from the unity client by using a dcl lambda `https://opensea.decentraland.org/api/v1/assets` that behind the curtains it uses `https://opensea.io/assets/ethereum/{CONTRACT_ADDRESS}/{TOKEN_ID}`.

That OpenSea endpoint from its [v1 API](https://docs.opensea.io/v1.0/reference/getting-assets) only supports `ethereum` assets (the v2 will supposedly support non-ethereum assets fetching but its `/assets` endpoint hasn't been implemented by Opensea yet).

Decentraland old L1 wearables can be used without a problem by getting the contract address and token id of any of those from opensea marketplace and then using that with NFTShape as with any other ethereum NFT, but most wearable/emotes from Decentraland are in `matic`...

So, the solution to support most dcl assets in the NFTShape component would be one of the following:

**A.** Implement something using what the avatar editor HUD [uses in the renderer to display wearable/emote thumbnails](https://github.com/decentraland/unity-renderer/blob/aac45acd7f1923c878eeec08e6135eae3d552159/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs#L172~L185): would require to be able to get a `WearableItem` from just a `urn`, and get as much data as possible from the wearable item.
All wearables info is stored at `IWearablesCatalogService.WearablesCatalog`. If the wearable is not cached it should be retrieved with `await IWearablesCatalogService.RequestWearableAsync(wearableId, ct)`. The `WearableItem` only contains the thumbnail url (string), not the instance of the image/sprite.
Regarding to the thumbnails images, there is a call `ThumbnailsManager.GetThumbnail` which already checks if the thumbnail exists in the cache (by url). Internally we also use the `ILazyTextureObserver` which internally also handles a texture cache

**B.** Implement some custom request to TheGraph similar to what "store scenes" do ([example](https://github.com/decentraland-scenes/mvfw23_neo_iodf/blob/main/src/store/store/blockchain/fetch.ts#L40)) for displaying thumbnail of wearable/emote NTs.

**C.** Work with platform/dApps team to create an endpoint to retrieve the data that NFTShape needs by using a raw Decentraland URN or similar (behind the curtains that endpoint will probably fetch the images from the catalysts)
As an example, the endpoint could be something like `/nft-metadata/{urn}` and return `{ "title": "my nft", "owner": "0xasd123", "description": "text", "imageAbsoluteUrl": "https://..../nft.png" }`

**D.** Wait for OpenSea to implement their missing fetching endpoint for non-ethereum assets and then update the unity-renderer implementation to use that new endpoint (it may involve using some query param to specify the chain of each asset fetched)

**Comment by nearnshaw** [comment]
@pravusjif  now that we support any NFT from Polygon, isn't this covered?

**Comment by pravusjif** [comment]
> @pravusjif now that we support any NFT from Polygon, isn't this covered?

Uhmm yes this should be working already, I'm closing it
