### ISSUE TITLE
Assets folder's structure

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#783]
1. When an inspector project is initialized, create an `assets` folder.
2. Inside the `assets` folder create a folder with name identical to project's name. It is the default asset package.
3. `main.composite` should be placed in the default asset package's folder.
4. In asset inspector's folder tree, do not show "File System" and "assets", display only the folder of default asset package.
5. Imported builder's assets should be placed in `assets/builder` folder.

**Comment by leanmendoza** [comment]
Related to https://github.com/decentraland/sdk/issues/708
