### ISSUE TITLE
Change camera controls to FPS-like mode

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#796]
1. Moving mouse while holding right button changes pitch / yaw.
2. Pressing WASD while holding right button moves camera along its X and Z axes.
3. Mouse wheeling while holding right button changes speed of camera's movement.

**Comment by menduz** [comment]
This should be an option, not the _only_ option

**Comment by AN-DCL** [comment]
> This should be an option, not the _only_ option

It is a default camera control schema in Unity, Unreal and Godot. No reason to go against the grain.
