### ISSUE TITLE
Add child operation creates two children

### ISSUE THREAD

**Issue by AN-DCL** [decentraland/sdk#804]
1. Add a child to root entity.
2. Observe two children being added.

**Comment by cazala** [comment]
https://github.com/decentraland/sdk/assets/2781777/f5138718-ca31-4a19-a0b6-ebb66c0dd76c

I started undoing commits to find out where this was introduced and I believe it was done in this PR in case it helps on fixing it: https://github.com/decentraland/js-sdk-toolchain/pull/606

This is a link to the first preview where I found the issue: https://feat-search-folders.js-sdk-toolchain.pages.dev/inspector/
This is the previous preview where it does not happen: https://free-camera.js-sdk-toolchain.pages.dev/inspector/
