### ISSUE TITLE
Deleting a file that has the same name as other file in other folder does not work

### ISSUE THREAD

**Issue by cazala** [decentraland/sdk#810]
BLOCKED: We need to fix https://github.com/decentraland/sdk/issues/809 before fixing this one.

Sometimes it does nothing, sometimes it deletes another file. This can be tested deleting the file `models2/test2-glb.glb`

https://github.com/decentraland/sdk/assets/2781777/d929ec71-2f34-4ad3-8269-56a21711c652

**Comment by nicoecheza** [comment]
already fixed
