### ISSUE TITLE
Hot reload often breaks the preview

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#880]
When having the preview open and making changes to the inspector and/or the code, the rendering of the scene often breaks, showing the orange floor and no entities.

In my experience I see this very consistently happen with the first change since the preview starts, and tends to work well after that if there are any other changes. According to Nico Eche, he doesn't experience that entirely consistently, though. In my experience, if I make another change and save the scene comes back to working.

![Image](https://user-images.githubusercontent.com/3507907/247959293-1fbb3fdd-e8a2-40aa-9cf1-75514bce96db.png)

This happens both when using the browser in VS Code and with Chrome.

In console there are a few messages that are suspicious, though not clear that they are the cause.

This is especially problematic in scenes where the player falls through the floor if the scene changes, for example in the mansion template. Even if you fix the preview by making another change, the player is far away from the spawn point and can't get back up. Some creators also might not realize that it takes another change for the scene to get fixed, so they might get stuck in a loop of hard reloading for every change.

**Comment by nicoecheza** [comment]
stoyan reported an issue on for explorer team in slack that seems to be the same problem:

https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1687875996617269

since Genesis plaza runs on SDK6, this might be a problem with the explorer rather than the inspector
