### ISSUE TITLE
Preview tries to load asset bundles

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#89]
When running a preview, there are many error messages of asset bundles that were tried to be fetched

It seems that with more models in the scenes, we get more of these. These error messages can add up to a lot and be very ugly on console, and probably the requests to check for the asset bundles also make the loading of preview slower.

When in preview, shouldn't check for asset bundles at all.

![Screen Shot 2021-10-01 at 16.49.40.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/523a59f2-74d5-4ce1-8347-b74f85168d21)

**Comment by pbosio** [comment]
kernel PR: https://github.com/decentraland/kernel/pull/68
