### ISSUE TITLE
Error when dropping builder asset 

### ISSUE THREAD

**Issue by cazala** [decentraland/sdk#902]
The `@dcl/inspector` in `main` seems to be in a broken state.

When drag and dropping a builder asset in the inspector within VSCode, there is an error:

<img width="631" alt="Screenshot 2023-07-19 at 15 02 59" src="https://github.com/decentraland/sdk/assets/2781777/af495ac5-22f5-49d8-af46-232b598f5260">

The asset is downloaded and shows up in the File System tab, but the entity is not created in the Hierarchy and nothing shows up on the Renderer.

Steps to reproduce:

- Launch `@dcl/inspector` locally from `main` branch as always with `npm start`
- Launch the VSCode extension locally with the `.env` using this config:
```
LOCAL_DEV_SERVER=Inspector
LOCAL_DEV_PORT=8000
```
- Go to a new folder and Create Project > Standard project
- Once ready, drag and drop an asset from the Asset Packs tab into the Renderer

**Comment by nicoecheza** [comment]
updating to @dcl/inspector@next on the editor seems to fix the problem 👌
