### ISSUE TITLE
Remove boundary checker from PX (SDK7)

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#908]
> I was messing around with building a PX, and I found that it’s considering items attached to the player as out of bounds.

![image](https://github.com/decentraland/sdk/assets/16782417/77b9f4fa-17a6-439a-a159-cbdb4f22ac3c)

We need to tag the px scene as global or something like that so the renderer knows that it's a global scene/px and it doesn't need to run the boundary checker

**Comment by nearnshaw** [comment]
we still need to implement all of PX on E@
