### ISSUE TITLE
UiCanvasInformation not found

### ISSUE THREAD

**Issue by DrasticLp** [decentraland/sdk#915]
Hi,
I have some UIs that need to get the screen size in order to work but when I try to get it, it crashes...
![image](https://github.com/decentraland/sdk/assets/46007101/66d6ac1b-9fe7-4f98-af97-a18159418c89)

![image](https://github.com/decentraland/sdk/assets/46007101/4ef1e1f3-f11f-4466-803d-b12e566b9f94)

Any ideas ?

**Comment by nearnshaw** [comment]
At what point during the scene's lifecycle are you trying to fetch this data?

Are you doing it from inside the main() function, a function called indirectly by main(), a system or an async block of code?   If from any of the above, then this should work, and if not there's surely a bug.

However, if you're not, then it's likely that the corresponding entities are simply not loaded yet. The reason why we have a main function is that it's executed only once the engine has confirmed that everything is already loaded.

**Comment by DrasticLp** [comment]
I execute it inside a ui
![image](https://github.com/decentraland/sdk/assets/46007101/7d559884-b56b-4dde-8286-b164b208555e)
The ui is registered inside the main() function
I also tried only calling it after 15 seconds to test it and it still crashed

**Comment by DrasticLp** [comment]
It started to happend when I updated from 7.3.0 to 7.3.7

**Comment by nearnshaw** [comment]
Another snippet where it's not working:

´´´ts
export function Main() {
    try {
        canvas = UiCanvasInformation.getOrNull(engine.RootEntity)
        if(!canvas) {
            canvas = {'width': 1024, 'height': 768}
        }

        pxWidth = canvas.width
        pxHeight = canvas.height

        return (canvas)
    } catch (e: any) {
        utils.timers.setTimeout(() => {
            Main()
        }, 100)
    }
}
´´´ 
Decentraland Editor SDK7
v1.21.0
in ui.tsx

**Comment by pravusjif** [comment]
@DrasticLp can you confirm that with [this build](https://github.com/decentraland/unity-renderer/pull/5626) the problem is solved?

You can test it starting your local scene and adding `&explorer-branch=fix/sdk7-scenes-addition-to-datastore` to the URL

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-renderer/pull/5626

The fix will reach production (probably SDK 7.3.11) after the explorer's next release.
