### ISSUE TITLE
Billboard mode follows avatars, not camera

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#917]
The rotation of entities that have a billboard component follows the position of the avatar. This is fine in 1st person, but in 3rd person, since the avatar and camera angle might not match, this breaks the optical illusion we're supposed to be seeing.

Billboard mode should always follow the camera, regardless of what camera mode is being used.

![Image](https://user-images.githubusercontent.com/3507907/262754784-1cdc20b0-8b42-41ae-9850-692626dfcd2a.png)

**Comment by pbosio** [comment]
can't reproduce
