### ISSUE TITLE
SDK7 cannot call a local http test version of a REST service from a local preview of a scene

### ISSUE THREAD

**Issue by cfravel** [decentraland/sdk#925]
If you try to call a local http test version of a REST API service from a local preview of an SDK7 scene, you get the following error:

_Warning: Can't make an unsafe http request in deployed scenes, please consider upgrading to https. 
url=http://localhost/<serviceurl>_

testing with a local https service was allowed in SDK6

**Comment by gonpombo8** [comment]
> _Warning: Can't make an unsafe_ 
Hey, this is working as expected. You are seeing a Warning that this http request is not going to work once you deploy your scene.
But the request is being made.
