### ISSUE TITLE
AudioStream issues in SDK7

### ISSUE THREAD

**Issue by garyrutland** [decentraland/sdk#927]
Currently, the `AudioStream` component is only being triggered when pointer focus happens.

1. If I am outside of the scene and enter (with pointer focus, I'm not sure if there is a better name for this?) it does now connect
However, if I then leave the scene and re-enter the AudioStream doesn't reconnect.
On scene exit I am removing the AudioStream by using AudioStream.deleteFrom(this.entity) and re-creating on entry.

2. If I spawn within the scene I can see the API requests being made to retrieve the token but does not then connect to the stream until focus happens.
In this case, if a player doesn't focus within 5 seconds they would end up with the login dialog appearing and currently there isn't a way for us to hook into this.
This is also the case if I run into the scene without focus.

A simple way to replicate this is with the following code:

```ts
import { AudioStream, engine } from "@dcl/sdk/ecs"

export function main() {
  console.log('main')

  const entity = engine.addEntity()

  AudioStream.createOrReplace(entity, {
    url: 'https://icecast.ravepartyradio.org/ravepartyradio-192.mp3',
    volume: 0.1,
    playing: true
  })

  console.log(AudioStream.get(entity))
}
```

While this seems like a nuisance rather than anything critical, for us, this is very problematic as we require authentication to connect to our streams and the API call to get a token is triggered straight away but because the `AudioStream` does not connect when intended it results in the token being invalid and a login dialog appears.

**Comment by pbosio** [comment]
Hi @garyrutland 
1- the issue would be that leaving the scene while reproducing an `AudioStream` and after that re-entering the scene won't play the `AudioStream`?
if I understand correctly you are subscribed to the "scene exit" event and removing the `AudioStream` component, If you avoid doing that (removing the component), does the issue persist?

2- the browser restrict any media to be played until there is an user input or the pointer is locked by the canvas, that's the reason the scene awaits for any of those input to start playing the `AudioStream`
could explain a little bit more about how the flow for the scene is? just to understand the issue better 
I understood it like: as soon as the scene code is executed you send an auth request to your servers, a token is received and used to start an `AudioStream`
do I understand it correctly?

Maybe could you wait for the user to perform any input instead of running that flow when the scene is executed?
something like this might help
```ts
let isMediaAllowed = false

function detectFirstUserInput(){
  isMediaAllowed = inputSystem.isTriggered(InputAction.IA_ANY, PointerEventType.PET_DOWN) 
                  || PointerLock.get(engine.CameraEntity).isPointerLocked
  if (isMediaAllowed)
    engine.removeSystem(detectFirstUserInput)
}

engine.addSystem(detectFirstUserInput)
```

**Comment by garyrutland** [comment]
To clarify, we are upgrading fr SDK6 where all of this works fine.

**Comment by garyrutland** [comment]
Doing some more tests with updated versions (@dcl/js-runtime: 7.3.14, @dcl/sdk: 7.3.14) it seems scenario one is now ok.
If what you're saying is true for scenario two (which based on more testing does seem to be true) this has changed since SDK 6 and is also not documented.

However, while doing more tests it feels like there are some inconsistencies in behaviour.

```ts
import { getUserData } from "~system/UserIdentity"
import { AudioStream, engine } from "@dcl/sdk/ecs"
import { onEnterSceneObservable, onLeaveSceneObservable } from "@dcl/sdk/observables"

export async function main() {
  console.log("main")

  const myPlayer = await getUserData({})
  const entity = engine.addEntity()

  onEnterSceneObservable.add((player) => {
    console.log("player entered scene: ", player.userId)

    if (player.userId === myPlayer.data?.userId) {
      AudioStream.createOrReplace(entity, {
        url: "http://mediaserv30.live-streams.nl:8086/live",
        volume: 0.1,
        playing: true
      })

      // true
      console.log(AudioStream.has(entity))

      // {url: 'http://mediaserv30.live-streams.nl:8086/live', volume: 0.1, playing: true}
      console.log(AudioStream.get(entity))
    }
  })

  onLeaveSceneObservable.add((player) => {
    console.log("player left scene: ", player.userId)

    if (player.userId === myPlayer.data?.userId) {
      AudioStream.deleteFrom(entity)

      // false
      console.log(AudioStream.has(entity))
    }
  })
}
```

**Scenario one**
1. Spawn in scene (no music)
2. Left click and the music will start
3. Walk out of the scene and the music will stop
4. Walk back into the scene and the music will start again
 
**Scenario two**
1. Spawn in the scene (no music)
2. Right click and the music will start
3. Walk out of the scene and the music will stop
4. Walk back into the scene and the music will NOT start again until a click is done

It seems each time you leave/enter a scene the "active" flag gets reset, and if you're saying this is a browser restriction then this surely only needs to happen once for the entirety of DCL?

_On a side note, the example URL used in the [docs](https://docs.decentraland.org/creator/development-guide/sdk7/audio-streaming/) as of this post does not work and gets a connection refused response._

**Comment by garyrutland** [comment]
It is also worth noting, and this was also the case in SDK6 that no matter what the actual state of the player is that `playing` always returns `true`.

```ts
console.log(AudioStream.get(entity))
```

**Comment by pbosio** [comment]
@garyrutland issue should be fixed on next release.
please take into consideration that if a user enters your scene through the url or link and does not interact with the page canvas, the browse will most likely to block the audio playing until the user interacts with the canvas
