### ISSUE TITLE
SDK7: some of the builtin emotes are named differently than in the docs

### ISSUE THREAD

**Issue by cfravel** [decentraland/sdk#941]
The document at https://docs.decentraland.org/creator/development-guide/sdk7/trigger-emotes/ provides the names of the built-in emotes.  It has some discrepancies vs the code.

The names that currently actually work are:

- wave
- fistpump    // not fist_pump
- robot
- raiseHand   // not raise_hand.  Notice capital H is required
- clap
- money
- kiss
- tik
- hammer,
- tektonik
- dontsee     // not dont_see
- handsair    // not hands_air
- shrug
- disco
- dab
- headexplode // not head_explode

Either the docs, or the code, should be changed.
Note that there is also a typo of a comma after hammer in the documentation

**Comment by nearnshaw** [comment]
Thanks for reporting this Carl
I just fixed it in the docs
(we should avoid changing the names in the SDK, as it could break scenes that curenlty work)
