### ISSUE TITLE
OnHover component (in-world)

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#95]
An OnHover component could enable running a lambda whenever an entity is hovered-on.

```ts
myEntity.addComponent(
   new OnHover(
     () => {
      log(“player started hovering“)
      feedbackUI.visible = true
     },
     () => {
      log(“player stopped hovering“)
      feedbackUI.visible = false
     }
    )
 )
```

In this code snippet, I’m assigning the OnHover two required lambdas, the fist for when the hovering starts, and the second for when it ends. We could instead have a separate component for when hovering ends (like OnPointerUp) but it’s hard to imagine scenarios where you don’t want to handle both events, so better to have both together.

The engine already checks for hovering to display the hover text, it would make sense to expose that existing event to the scene, to avoid recalculating pointer trajectories.

**Comment by pbosio** [comment]
posix: https://github.com/decentraland/posix/pull/12
renderer: https://github.com/decentraland/unity-renderer/pull/1700
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/71
