### ISSUE TITLE
Warn when scene missing name/description/thumbnail

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#951]
When trying to deploy a scene that doesn't have a name, a description, or a thumbnail, we should show a warning.

Today only 8% of scenes have a description, less than 25% have a custom name.
The new discoverability features like search on the map or categorization depend on scenes having metadata in them.

We should push creators more to complete this data. We could make a visible warning whenever you try to deploy something that is missing this.

**Comment by gonpombo8** [comment]
We already have this logic on the old CLI (sdk6) 
https://github.com/decentraland/cli/blob/main/src/sceneJson/utils.ts#L19-L58
