### ISSUE TITLE
AvatarModifierArea position and excludeIds problem

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#963]
### PROBLEM 1

A creator reported that using the following code, the avatar area ends up only covering a 3x3x3 area from the origin of coordinates:
```
AvatarModifierArea.createOrReplace(entity, {
            area: Vector3.create(10, 14, 10),
            modifiers: [AvatarModifierType.AMT_HIDE_AVATARS],
            excludeIds: []
        })
```

### PROBLEM 2

Apparently the `excludeIds` collection is only working for one's own address and/or not for more than 1 excludeID...

**Comment by pravusjif** [comment]
* Can't reproduce **PROBLEM 1**

**Comment by esisl** [comment]
There is a problem.
The exception only works if excludeIds is a constant
However, I already see the message:
"...problem is fixed with &explorer-branch=fix/sdk7-avatar-modifier-area in your local test url"

**Comment by esisl** [comment]
Colleagues... this is a disaster.
Option 1
Collecting a list of players: let connectedPlayers = await getConnectedPlayers({})
I collect an array from userId
and specify it as excludeIds
Does not work. We see only the first user from the list.

Option 2
I output a list from option 1 to the console, make an array constant ['0x...', '0x...']
Works!

**Comment by esisl** [comment]
I think I have a hypothesis...

If you do AvatarModifierArea.createOrReplace several times in a row

And at the same time, first there will be only one userId in the excludeIds array, and then two, then this does not work.

But if you immediately execute AvatarModifierArea.createOrReplace with two userids in the excludeIds array, then it works...

Maybe something is not in time?

**Comment by esisl** [comment]
Yes. If you do AvatarModifierArea.createOrReplace several times in a row, then only one or two of the first ones are executed, and then executing this code HAS NO EFFECT!

**Comment by pravusjif** [comment]
Problem finally solved at https://github.com/decentraland/unity-renderer/pull/5791

**Comment by pravusjif** [comment]
PR with fix merged. Will reach production in next explorer release.
