### ISSUE TITLE
Use consistent dropdowns in the Play Sound and Play Animation actions

### ISSUE THREAD

**Issue by meyaradcl** [decentraland/sdk#970]
In the **Play Animation** and **Play Sound** actions I see we are using 2 different dropdowns:

![Image](https://github.com/decentraland/sdk/assets/126520407/8f3e57d9-2e5b-4508-878d-aaa52e3fdc87)

![Image](https://github.com/decentraland/sdk/assets/126520407/064579cb-fe1b-4b15-b8bf-558c1f226d76)

We should use the same one (the one with lighter background), especially inside the same container. 

Note: this is not critical, and we could review during the UI toolkit initiative of cycle 3.

**Comment by cyaiox** [comment]
Fixed on https://github.com/decentraland/js-sdk-toolchain/pull/835
