### ISSUE TITLE
Clicked on player event

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#98]
On many scenes, it would be great to be able to have custom behavior when clicking on another player. This would be essential for any shooters.

A global event could announce when a player has been clicked, and return an object for that player with data about them.

This is connected to another RFC about player data, as we should need to know what player was clicked, and be able to consistently refer to that player to do things like attach entities to them.

This feature calls for changing the default behavior of opening the profile window when clicking on another player. My suggestion is to map this functionality to pressing E on a player, to leave the click free for more fast-paced game functionalities like shooting or other mechanics. The world team agrees with this design decision, but they first need to implement the change on their end.

**Comment by pbosio** [comment]
renderer: https://github.com/decentraland/unity-renderer/pull/1685
sdk: https://github.com/decentraland/js-sdk-toolchain/pull/69
posix: https://github.com/decentraland/posix/pull/11
