### ISSUE TITLE
Restricted actions only need permissions in portable experiences

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#985]
Today you always need to add the ALLOW_TO_TRIGGER_AVATAR_EMOTE and ALLOW_TO_MOVE_PLAYER_INSIDE_SCENE permissions to play an avatar animation or to teleport the player. This applies to scenes, to portable experiences, and smart wearables.

In portable experiences and smart wearables, adding these permissions results in showing a warning to the player. In this case it's worth it and we want to keep this behavior.

In scenes, however, this permission is not being used at all. We want to get rid of it, so that creators are able to just play avatar animations and teleport the player without adding anything to scene.json. This is because it adds unnecessary friction. Removing this restriction will make it easier for content creators using smart items too, when we're able to do these kinds of actions

**Comment by pravusjif** [comment]
This will probably require fixing [this 'isPortableExperience' property](https://github.com/decentraland/unity-renderer/blob/a1568f673f2bac2757523ae6e656552680d84b3e/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs#L38) that is not working correctly (or at all) at the moment.
