### ISSUE TITLE
Entity switch up on hot reload

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#987]
When doing hot reload, sometimes some entities get messed up. It seems like some components aren't cleaned up, and are assigned to the wrong entity.

In the "rotating-platforms" scene, from Goerli Plaza, I see it happen 100% of the time. 
https://github.com/decentraland/sdk7-goerli-plaza/tree/main/rotating-platforms

1) Open the scene, it loads fine
2) Just add an enter and save one of its files
3) The scene reloads with weird things in places they shouldn't be, and things that should be static rotating.

In this video, we start with the scene working fine, then I do hot reload and it gets messed up.

https://github.com/decentraland/sdk/assets/3507907/e4fba6fa-c941-4d8f-8c57-b301a79e4932

The "moving-platforms" scene also has this problem, although its effects are less obvious.

This seems to only affect some scenes, possibly depends on how entity ids line up.

**Comment by nearnshaw** [comment]
This may or may not be related, but running around Goerli Plaza I also came across some random cases that look like the same bug
Some entities rotated or shifted for a second after loading, then stopped, but remained in the wrong position

I could not find a way to reproduce these, they only happened once. The scenes loaded fine if I walked away and came back


![Image](https://github.com/decentraland/sdk/assets/3507907/290bd563-fcfa-4797-b00b-b5a02b989aa2)
![Image](https://github.com/decentraland/sdk/assets/3507907/8f0d74ca-4646-4017-a12a-50851b04784e)

**Comment by nearnshaw** [comment]
Similarly to the previous comments, I also saw EMPTY PARCELS with displaced entities
This is also quite random and hard to reproduce



![Image](https://github.com/decentraland/sdk/assets/3507907/c98c7bfa-b7db-49d4-b81a-a93de5b38d5c)

**Comment by pravusjif** [comment]
There was a bug in the Tween component, tackled at https://github.com/decentraland/unity-renderer/pull/5972

**Comment by pravusjif** [comment]
Fix merged, will reach production with next explorer + sdk release (probably next monday 27)
