### ISSUE TITLE
UI Entities from SDK7 showing on other scenes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#989]
It seems that in some strange corener cases, there are entities from an SDK7 scene showing on other scenes

In this case, the UI from an SDK7 scene is showing in Genesis Plaza (SDK6)
![image](https://github.com/decentraland/sdk/assets/3507907/3b7d46b1-6933-4e3c-81b5-b362402b5cde)

This was reported by Ani, it's unclear how exactly to reproduce, but in this case she had just been at another scene before. 

It seems to suggest that sometimes some UI entities don't get cleaned up

Same bug also seen here by Stoyan:
![image](https://github.com/decentraland/sdk/assets/3507907/08dfb5f8-11c0-4892-9f5d-c8f382694f90)

**Comment by pravusjif** [comment]
So apparently a way of reproducing this should be by going into a separate world that uses an sdk7 scene, and going mack to Genesis Plaza

**Comment by pravusjif** [comment]
Apparently this is not happening anymore, if it appears again we'll re-open
