### ISSUE TITLE
SDK7 7.3.24 introduced an issue with buttons losing 'blocking', even if they have onMouseDown properties.

### ISSUE THREAD

**Issue by cfravel** [decentraland/sdk#990]
An issue introduced in DCL SDK7 release 7.3.24
causes buttons in some 2D UI configurations to fail to be blocking, 
even if they have onMouseDown properties.

The issue is reproducable in 7.3.24 and 7.3.25, but not in 7.3.23

Here is a simple scene, based on 7.3.24 Create Scene, which demonstrates the issue:
https://gitlab.com/dcl-tech/button-block-fail

To demonstrate the issue:
1) Download and run the scene
2) Notice that the Toggle UI button is blocking.  
3) Click it // the UI expands
4) !!! Button 2 is not blocking (even though it has an onMouseDown property)
5) Click the Toggle UI button // the UI becomes small again
6) !!! Now the original Toggle UI button on the the Small UI is no longer blocking either

**Comment by cfravel** [comment]
@pravusjif 
This is probably related to
https://github.com/decentraland/unity-renderer/pull/5819

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-renderer/pull/5862.

@cfravel thanks a lot for the example project, it was crucial to be able to reproduce the issue. Until the fix reaches production (most likely next monday), you could use `explorer-branch=fix/sdk7-pointer-event-pointer-blocker` which contains the fix, or `explorer-branch=dev` (that last one only after I get to merge my PR)

**Comment by pravusjif** [comment]
The fix has been merged. Will reach production on monday afternon most likely.
